
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * WARNING: This is an internal file that is subject to change!
 *
 * 🛑 Under no circumstances should you import this file directly! 🛑
 *
 * All exports from this file are wrapped under a `Prisma` namespace object in the client.ts file.
 * While this enables partial backward compatibility, it is not part of the stable public API.
 *
 * If you are looking for your Models, Enums, and Input Types, please import them from the respective
 * model files in the `model` directory!
 */

import * as runtime from "@prisma/client/runtime/client"
import type * as Prisma from "../models.js"
import { type PrismaClient } from "./class.js"

export type * from '../models.js'

export type DMMF = typeof runtime.DMMF

export type PrismaPromise<T> = runtime.Types.Public.PrismaPromise<T>

/**
 * Prisma Errors
 */

export const PrismaClientKnownRequestError = runtime.PrismaClientKnownRequestError
export type PrismaClientKnownRequestError = runtime.PrismaClientKnownRequestError

export const PrismaClientUnknownRequestError = runtime.PrismaClientUnknownRequestError
export type PrismaClientUnknownRequestError = runtime.PrismaClientUnknownRequestError

export const PrismaClientRustPanicError = runtime.PrismaClientRustPanicError
export type PrismaClientRustPanicError = runtime.PrismaClientRustPanicError

export const PrismaClientInitializationError = runtime.PrismaClientInitializationError
export type PrismaClientInitializationError = runtime.PrismaClientInitializationError

export const PrismaClientValidationError = runtime.PrismaClientValidationError
export type PrismaClientValidationError = runtime.PrismaClientValidationError

/**
 * Re-export of sql-template-tag
 */
export const sql = runtime.sqltag
export const empty = runtime.empty
export const join = runtime.join
export const raw = runtime.raw
export const Sql = runtime.Sql
export type Sql = runtime.Sql



/**
 * Decimal.js
 */
export const Decimal = runtime.Decimal
export type Decimal = runtime.Decimal

export type DecimalJsLike = runtime.DecimalJsLike

/**
* Extensions
*/
export type Extension = runtime.Types.Extensions.UserArgs
export const getExtensionContext = runtime.Extensions.getExtensionContext
export type Args<T, F extends runtime.Operation> = runtime.Types.Public.Args<T, F>
export type Payload<T, F extends runtime.Operation = never> = runtime.Types.Public.Payload<T, F>
export type Result<T, A, F extends runtime.Operation> = runtime.Types.Public.Result<T, A, F>
export type Exact<A, W> = runtime.Types.Public.Exact<A, W>

export type PrismaVersion = {
  client: string
  engine: string
}

/**
 * Prisma Client JS version: 7.2.0
 * Query Engine version: 0c8ef2ce45c83248ab3df073180d5eda9e8be7a3
 */
export const prismaVersion: PrismaVersion = {
  client: "7.2.0",
  engine: "0c8ef2ce45c83248ab3df073180d5eda9e8be7a3"
}

/**
 * Utility Types
 */

export type Bytes = runtime.Bytes
export type JsonObject = runtime.JsonObject
export type JsonArray = runtime.JsonArray
export type JsonValue = runtime.JsonValue
export type InputJsonObject = runtime.InputJsonObject
export type InputJsonArray = runtime.InputJsonArray
export type InputJsonValue = runtime.InputJsonValue


export const NullTypes = {
  DbNull: runtime.NullTypes.DbNull as (new (secret: never) => typeof runtime.DbNull),
  JsonNull: runtime.NullTypes.JsonNull as (new (secret: never) => typeof runtime.JsonNull),
  AnyNull: runtime.NullTypes.AnyNull as (new (secret: never) => typeof runtime.AnyNull),
}
/**
 * Helper for filtering JSON entries that have `null` on the database (empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const DbNull = runtime.DbNull

/**
 * Helper for filtering JSON entries that have JSON `null` values (not empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const JsonNull = runtime.JsonNull

/**
 * Helper for filtering JSON entries that are `Prisma.DbNull` or `Prisma.JsonNull`
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const AnyNull = runtime.AnyNull


type SelectAndInclude = {
  select: any
  include: any
}

type SelectAndOmit = {
  select: any
  omit: any
}

/**
 * From T, pick a set of properties whose keys are in the union K
 */
type Prisma__Pick<T, K extends keyof T> = {
    [P in K]: T[P];
};

export type Enumerable<T> = T | Array<T>;

/**
 * Subset
 * @desc From `T` pick properties that exist in `U`. Simple version of Intersection
 */
export type Subset<T, U> = {
  [key in keyof T]: key extends keyof U ? T[key] : never;
};

/**
 * SelectSubset
 * @desc From `T` pick properties that exist in `U`. Simple version of Intersection.
 * Additionally, it validates, if both select and include are present. If the case, it errors.
 */
export type SelectSubset<T, U> = {
  [key in keyof T]: key extends keyof U ? T[key] : never
} &
  (T extends SelectAndInclude
    ? 'Please either choose `select` or `include`.'
    : T extends SelectAndOmit
      ? 'Please either choose `select` or `omit`.'
      : {})

/**
 * Subset + Intersection
 * @desc From `T` pick properties that exist in `U` and intersect `K`
 */
export type SubsetIntersection<T, U, K> = {
  [key in keyof T]: key extends keyof U ? T[key] : never
} &
  K

type Without<T, U> = { [P in Exclude<keyof T, keyof U>]?: never };

/**
 * XOR is needed to have a real mutually exclusive union type
 * https://stackoverflow.com/questions/42123407/does-typescript-support-mutually-exclusive-types
 */
export type XOR<T, U> =
  T extends object ?
  U extends object ?
    (Without<T, U> & U) | (Without<U, T> & T)
  : U : T


/**
 * Is T a Record?
 */
type IsObject<T extends any> = T extends Array<any>
? False
: T extends Date
? False
: T extends Uint8Array
? False
: T extends BigInt
? False
: T extends object
? True
: False


/**
 * If it's T[], return T
 */
export type UnEnumerate<T extends unknown> = T extends Array<infer U> ? U : T

/**
 * From ts-toolbelt
 */

type __Either<O extends object, K extends Key> = Omit<O, K> &
  {
    // Merge all but K
    [P in K]: Prisma__Pick<O, P & keyof O> // With K possibilities
  }[K]

type EitherStrict<O extends object, K extends Key> = Strict<__Either<O, K>>

type EitherLoose<O extends object, K extends Key> = ComputeRaw<__Either<O, K>>

type _Either<
  O extends object,
  K extends Key,
  strict extends Boolean
> = {
  1: EitherStrict<O, K>
  0: EitherLoose<O, K>
}[strict]

export type Either<
  O extends object,
  K extends Key,
  strict extends Boolean = 1
> = O extends unknown ? _Either<O, K, strict> : never

export type Union = any

export type PatchUndefined<O extends object, O1 extends object> = {
  [K in keyof O]: O[K] extends undefined ? At<O1, K> : O[K]
} & {}

/** Helper Types for "Merge" **/
export type IntersectOf<U extends Union> = (
  U extends unknown ? (k: U) => void : never
) extends (k: infer I) => void
  ? I
  : never

export type Overwrite<O extends object, O1 extends object> = {
    [K in keyof O]: K extends keyof O1 ? O1[K] : O[K];
} & {};

type _Merge<U extends object> = IntersectOf<Overwrite<U, {
    [K in keyof U]-?: At<U, K>;
}>>;

type Key = string | number | symbol;
type AtStrict<O extends object, K extends Key> = O[K & keyof O];
type AtLoose<O extends object, K extends Key> = O extends unknown ? AtStrict<O, K> : never;
export type At<O extends object, K extends Key, strict extends Boolean = 1> = {
    1: AtStrict<O, K>;
    0: AtLoose<O, K>;
}[strict];

export type ComputeRaw<A extends any> = A extends Function ? A : {
  [K in keyof A]: A[K];
} & {};

export type OptionalFlat<O> = {
  [K in keyof O]?: O[K];
} & {};

type _Record<K extends keyof any, T> = {
  [P in K]: T;
};

// cause typescript not to expand types and preserve names
type NoExpand<T> = T extends unknown ? T : never;

// this type assumes the passed object is entirely optional
export type AtLeast<O extends object, K extends string> = NoExpand<
  O extends unknown
  ? | (K extends keyof O ? { [P in K]: O[P] } & O : O)
    | {[P in keyof O as P extends K ? P : never]-?: O[P]} & O
  : never>;

type _Strict<U, _U = U> = U extends unknown ? U & OptionalFlat<_Record<Exclude<Keys<_U>, keyof U>, never>> : never;

export type Strict<U extends object> = ComputeRaw<_Strict<U>>;
/** End Helper Types for "Merge" **/

export type Merge<U extends object> = ComputeRaw<_Merge<Strict<U>>>;

export type Boolean = True | False

export type True = 1

export type False = 0

export type Not<B extends Boolean> = {
  0: 1
  1: 0
}[B]

export type Extends<A1 extends any, A2 extends any> = [A1] extends [never]
  ? 0 // anything `never` is false
  : A1 extends A2
  ? 1
  : 0

export type Has<U extends Union, U1 extends Union> = Not<
  Extends<Exclude<U1, U>, U1>
>

export type Or<B1 extends Boolean, B2 extends Boolean> = {
  0: {
    0: 0
    1: 1
  }
  1: {
    0: 1
    1: 1
  }
}[B1][B2]

export type Keys<U extends Union> = U extends unknown ? keyof U : never

export type GetScalarType<T, O> = O extends object ? {
  [P in keyof T]: P extends keyof O
    ? O[P]
    : never
} : never

type FieldPaths<
  T,
  U = Omit<T, '_avg' | '_sum' | '_count' | '_min' | '_max'>
> = IsObject<T> extends True ? U : T

export type GetHavingFields<T> = {
  [K in keyof T]: Or<
    Or<Extends<'OR', K>, Extends<'AND', K>>,
    Extends<'NOT', K>
  > extends True
    ? // infer is only needed to not hit TS limit
      // based on the brilliant idea of Pierre-Antoine Mills
      // https://github.com/microsoft/TypeScript/issues/30188#issuecomment-478938437
      T[K] extends infer TK
      ? GetHavingFields<UnEnumerate<TK> extends object ? Merge<UnEnumerate<TK>> : never>
      : never
    : {} extends FieldPaths<T[K]>
    ? never
    : K
}[keyof T]

/**
 * Convert tuple to union
 */
type _TupleToUnion<T> = T extends (infer E)[] ? E : never
type TupleToUnion<K extends readonly any[]> = _TupleToUnion<K>
export type MaybeTupleToUnion<T> = T extends any[] ? TupleToUnion<T> : T

/**
 * Like `Pick`, but additionally can also accept an array of keys
 */
export type PickEnumerable<T, K extends Enumerable<keyof T> | keyof T> = Prisma__Pick<T, MaybeTupleToUnion<K>>

/**
 * Exclude all keys with underscores
 */
export type ExcludeUnderscoreKeys<T extends string> = T extends `_${string}` ? never : T


export type FieldRef<Model, FieldType> = runtime.FieldRef<Model, FieldType>

type FieldRefInputType<Model, FieldType> = Model extends never ? never : FieldRef<Model, FieldType>


export const ModelName = {
  Entity: 'Entity',
  Attribute: 'Attribute',
  Value: 'Value',
  KVSet: 'KVSet',
  KV: 'KV',
  Range: 'Range',
  AttrType: 'AttrType',
  Template: 'Template',
  Query: 'Query',
  TableE: 'TableE',
  ColumnE: 'ColumnE',
  RowEAV: 'RowEAV'
} as const

export type ModelName = (typeof ModelName)[keyof typeof ModelName]



export interface TypeMapCb<GlobalOmitOptions = {}> extends runtime.Types.Utils.Fn<{extArgs: runtime.Types.Extensions.InternalArgs }, runtime.Types.Utils.Record<string, any>> {
  returns: TypeMap<this['params']['extArgs'], GlobalOmitOptions>
}

export type TypeMap<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> = {
  globalOmitOptions: {
    omit: GlobalOmitOptions
  }
  meta: {
    modelProps: "entity" | "attribute" | "value" | "kVSet" | "kV" | "range" | "attrType" | "template" | "query" | "tableE" | "columnE" | "rowEAV"
    txIsolationLevel: TransactionIsolationLevel
  }
  model: {
    Entity: {
      payload: Prisma.$EntityPayload<ExtArgs>
      fields: Prisma.EntityFieldRefs
      operations: {
        findUnique: {
          args: Prisma.EntityFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$EntityPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.EntityFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$EntityPayload>
        }
        findFirst: {
          args: Prisma.EntityFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$EntityPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.EntityFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$EntityPayload>
        }
        findMany: {
          args: Prisma.EntityFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$EntityPayload>[]
        }
        create: {
          args: Prisma.EntityCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$EntityPayload>
        }
        createMany: {
          args: Prisma.EntityCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.EntityCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$EntityPayload>[]
        }
        delete: {
          args: Prisma.EntityDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$EntityPayload>
        }
        update: {
          args: Prisma.EntityUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$EntityPayload>
        }
        deleteMany: {
          args: Prisma.EntityDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.EntityUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.EntityUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$EntityPayload>[]
        }
        upsert: {
          args: Prisma.EntityUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$EntityPayload>
        }
        aggregate: {
          args: Prisma.EntityAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateEntity>
        }
        groupBy: {
          args: Prisma.EntityGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.EntityGroupByOutputType>[]
        }
        count: {
          args: Prisma.EntityCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.EntityCountAggregateOutputType> | number
        }
      }
    }
    Attribute: {
      payload: Prisma.$AttributePayload<ExtArgs>
      fields: Prisma.AttributeFieldRefs
      operations: {
        findUnique: {
          args: Prisma.AttributeFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AttributePayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.AttributeFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AttributePayload>
        }
        findFirst: {
          args: Prisma.AttributeFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AttributePayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.AttributeFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AttributePayload>
        }
        findMany: {
          args: Prisma.AttributeFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AttributePayload>[]
        }
        create: {
          args: Prisma.AttributeCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AttributePayload>
        }
        createMany: {
          args: Prisma.AttributeCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.AttributeCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AttributePayload>[]
        }
        delete: {
          args: Prisma.AttributeDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AttributePayload>
        }
        update: {
          args: Prisma.AttributeUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AttributePayload>
        }
        deleteMany: {
          args: Prisma.AttributeDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.AttributeUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.AttributeUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AttributePayload>[]
        }
        upsert: {
          args: Prisma.AttributeUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AttributePayload>
        }
        aggregate: {
          args: Prisma.AttributeAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateAttribute>
        }
        groupBy: {
          args: Prisma.AttributeGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AttributeGroupByOutputType>[]
        }
        count: {
          args: Prisma.AttributeCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AttributeCountAggregateOutputType> | number
        }
      }
    }
    Value: {
      payload: Prisma.$ValuePayload<ExtArgs>
      fields: Prisma.ValueFieldRefs
      operations: {
        findUnique: {
          args: Prisma.ValueFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ValuePayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.ValueFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ValuePayload>
        }
        findFirst: {
          args: Prisma.ValueFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ValuePayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.ValueFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ValuePayload>
        }
        findMany: {
          args: Prisma.ValueFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ValuePayload>[]
        }
        create: {
          args: Prisma.ValueCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ValuePayload>
        }
        createMany: {
          args: Prisma.ValueCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.ValueCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ValuePayload>[]
        }
        delete: {
          args: Prisma.ValueDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ValuePayload>
        }
        update: {
          args: Prisma.ValueUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ValuePayload>
        }
        deleteMany: {
          args: Prisma.ValueDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.ValueUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.ValueUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ValuePayload>[]
        }
        upsert: {
          args: Prisma.ValueUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ValuePayload>
        }
        aggregate: {
          args: Prisma.ValueAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateValue>
        }
        groupBy: {
          args: Prisma.ValueGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.ValueGroupByOutputType>[]
        }
        count: {
          args: Prisma.ValueCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.ValueCountAggregateOutputType> | number
        }
      }
    }
    KVSet: {
      payload: Prisma.$KVSetPayload<ExtArgs>
      fields: Prisma.KVSetFieldRefs
      operations: {
        findUnique: {
          args: Prisma.KVSetFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$KVSetPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.KVSetFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$KVSetPayload>
        }
        findFirst: {
          args: Prisma.KVSetFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$KVSetPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.KVSetFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$KVSetPayload>
        }
        findMany: {
          args: Prisma.KVSetFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$KVSetPayload>[]
        }
        create: {
          args: Prisma.KVSetCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$KVSetPayload>
        }
        createMany: {
          args: Prisma.KVSetCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.KVSetCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$KVSetPayload>[]
        }
        delete: {
          args: Prisma.KVSetDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$KVSetPayload>
        }
        update: {
          args: Prisma.KVSetUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$KVSetPayload>
        }
        deleteMany: {
          args: Prisma.KVSetDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.KVSetUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.KVSetUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$KVSetPayload>[]
        }
        upsert: {
          args: Prisma.KVSetUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$KVSetPayload>
        }
        aggregate: {
          args: Prisma.KVSetAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateKVSet>
        }
        groupBy: {
          args: Prisma.KVSetGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.KVSetGroupByOutputType>[]
        }
        count: {
          args: Prisma.KVSetCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.KVSetCountAggregateOutputType> | number
        }
      }
    }
    KV: {
      payload: Prisma.$KVPayload<ExtArgs>
      fields: Prisma.KVFieldRefs
      operations: {
        findUnique: {
          args: Prisma.KVFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$KVPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.KVFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$KVPayload>
        }
        findFirst: {
          args: Prisma.KVFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$KVPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.KVFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$KVPayload>
        }
        findMany: {
          args: Prisma.KVFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$KVPayload>[]
        }
        create: {
          args: Prisma.KVCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$KVPayload>
        }
        createMany: {
          args: Prisma.KVCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.KVCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$KVPayload>[]
        }
        delete: {
          args: Prisma.KVDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$KVPayload>
        }
        update: {
          args: Prisma.KVUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$KVPayload>
        }
        deleteMany: {
          args: Prisma.KVDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.KVUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.KVUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$KVPayload>[]
        }
        upsert: {
          args: Prisma.KVUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$KVPayload>
        }
        aggregate: {
          args: Prisma.KVAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateKV>
        }
        groupBy: {
          args: Prisma.KVGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.KVGroupByOutputType>[]
        }
        count: {
          args: Prisma.KVCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.KVCountAggregateOutputType> | number
        }
      }
    }
    Range: {
      payload: Prisma.$RangePayload<ExtArgs>
      fields: Prisma.RangeFieldRefs
      operations: {
        findUnique: {
          args: Prisma.RangeFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$RangePayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.RangeFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$RangePayload>
        }
        findFirst: {
          args: Prisma.RangeFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$RangePayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.RangeFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$RangePayload>
        }
        findMany: {
          args: Prisma.RangeFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$RangePayload>[]
        }
        create: {
          args: Prisma.RangeCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$RangePayload>
        }
        createMany: {
          args: Prisma.RangeCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.RangeCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$RangePayload>[]
        }
        delete: {
          args: Prisma.RangeDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$RangePayload>
        }
        update: {
          args: Prisma.RangeUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$RangePayload>
        }
        deleteMany: {
          args: Prisma.RangeDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.RangeUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.RangeUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$RangePayload>[]
        }
        upsert: {
          args: Prisma.RangeUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$RangePayload>
        }
        aggregate: {
          args: Prisma.RangeAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateRange>
        }
        groupBy: {
          args: Prisma.RangeGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.RangeGroupByOutputType>[]
        }
        count: {
          args: Prisma.RangeCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.RangeCountAggregateOutputType> | number
        }
      }
    }
    AttrType: {
      payload: Prisma.$AttrTypePayload<ExtArgs>
      fields: Prisma.AttrTypeFieldRefs
      operations: {
        findUnique: {
          args: Prisma.AttrTypeFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AttrTypePayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.AttrTypeFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AttrTypePayload>
        }
        findFirst: {
          args: Prisma.AttrTypeFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AttrTypePayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.AttrTypeFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AttrTypePayload>
        }
        findMany: {
          args: Prisma.AttrTypeFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AttrTypePayload>[]
        }
        create: {
          args: Prisma.AttrTypeCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AttrTypePayload>
        }
        createMany: {
          args: Prisma.AttrTypeCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.AttrTypeCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AttrTypePayload>[]
        }
        delete: {
          args: Prisma.AttrTypeDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AttrTypePayload>
        }
        update: {
          args: Prisma.AttrTypeUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AttrTypePayload>
        }
        deleteMany: {
          args: Prisma.AttrTypeDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.AttrTypeUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.AttrTypeUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AttrTypePayload>[]
        }
        upsert: {
          args: Prisma.AttrTypeUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AttrTypePayload>
        }
        aggregate: {
          args: Prisma.AttrTypeAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateAttrType>
        }
        groupBy: {
          args: Prisma.AttrTypeGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AttrTypeGroupByOutputType>[]
        }
        count: {
          args: Prisma.AttrTypeCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AttrTypeCountAggregateOutputType> | number
        }
      }
    }
    Template: {
      payload: Prisma.$TemplatePayload<ExtArgs>
      fields: Prisma.TemplateFieldRefs
      operations: {
        findUnique: {
          args: Prisma.TemplateFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$TemplatePayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.TemplateFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$TemplatePayload>
        }
        findFirst: {
          args: Prisma.TemplateFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$TemplatePayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.TemplateFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$TemplatePayload>
        }
        findMany: {
          args: Prisma.TemplateFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$TemplatePayload>[]
        }
        create: {
          args: Prisma.TemplateCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$TemplatePayload>
        }
        createMany: {
          args: Prisma.TemplateCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.TemplateCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$TemplatePayload>[]
        }
        delete: {
          args: Prisma.TemplateDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$TemplatePayload>
        }
        update: {
          args: Prisma.TemplateUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$TemplatePayload>
        }
        deleteMany: {
          args: Prisma.TemplateDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.TemplateUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.TemplateUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$TemplatePayload>[]
        }
        upsert: {
          args: Prisma.TemplateUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$TemplatePayload>
        }
        aggregate: {
          args: Prisma.TemplateAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateTemplate>
        }
        groupBy: {
          args: Prisma.TemplateGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.TemplateGroupByOutputType>[]
        }
        count: {
          args: Prisma.TemplateCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.TemplateCountAggregateOutputType> | number
        }
      }
    }
    Query: {
      payload: Prisma.$QueryPayload<ExtArgs>
      fields: Prisma.QueryFieldRefs
      operations: {
        findUnique: {
          args: Prisma.QueryFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$QueryPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.QueryFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$QueryPayload>
        }
        findFirst: {
          args: Prisma.QueryFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$QueryPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.QueryFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$QueryPayload>
        }
        findMany: {
          args: Prisma.QueryFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$QueryPayload>[]
        }
        create: {
          args: Prisma.QueryCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$QueryPayload>
        }
        createMany: {
          args: Prisma.QueryCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.QueryCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$QueryPayload>[]
        }
        delete: {
          args: Prisma.QueryDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$QueryPayload>
        }
        update: {
          args: Prisma.QueryUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$QueryPayload>
        }
        deleteMany: {
          args: Prisma.QueryDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.QueryUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.QueryUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$QueryPayload>[]
        }
        upsert: {
          args: Prisma.QueryUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$QueryPayload>
        }
        aggregate: {
          args: Prisma.QueryAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateQuery>
        }
        groupBy: {
          args: Prisma.QueryGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.QueryGroupByOutputType>[]
        }
        count: {
          args: Prisma.QueryCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.QueryCountAggregateOutputType> | number
        }
      }
    }
    TableE: {
      payload: Prisma.$TableEPayload<ExtArgs>
      fields: Prisma.TableEFieldRefs
      operations: {
        findUnique: {
          args: Prisma.TableEFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$TableEPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.TableEFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$TableEPayload>
        }
        findFirst: {
          args: Prisma.TableEFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$TableEPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.TableEFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$TableEPayload>
        }
        findMany: {
          args: Prisma.TableEFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$TableEPayload>[]
        }
        create: {
          args: Prisma.TableECreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$TableEPayload>
        }
        createMany: {
          args: Prisma.TableECreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.TableECreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$TableEPayload>[]
        }
        delete: {
          args: Prisma.TableEDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$TableEPayload>
        }
        update: {
          args: Prisma.TableEUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$TableEPayload>
        }
        deleteMany: {
          args: Prisma.TableEDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.TableEUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.TableEUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$TableEPayload>[]
        }
        upsert: {
          args: Prisma.TableEUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$TableEPayload>
        }
        aggregate: {
          args: Prisma.TableEAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateTableE>
        }
        groupBy: {
          args: Prisma.TableEGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.TableEGroupByOutputType>[]
        }
        count: {
          args: Prisma.TableECountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.TableECountAggregateOutputType> | number
        }
      }
    }
    ColumnE: {
      payload: Prisma.$ColumnEPayload<ExtArgs>
      fields: Prisma.ColumnEFieldRefs
      operations: {
        findUnique: {
          args: Prisma.ColumnEFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ColumnEPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.ColumnEFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ColumnEPayload>
        }
        findFirst: {
          args: Prisma.ColumnEFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ColumnEPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.ColumnEFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ColumnEPayload>
        }
        findMany: {
          args: Prisma.ColumnEFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ColumnEPayload>[]
        }
        create: {
          args: Prisma.ColumnECreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ColumnEPayload>
        }
        createMany: {
          args: Prisma.ColumnECreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.ColumnECreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ColumnEPayload>[]
        }
        delete: {
          args: Prisma.ColumnEDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ColumnEPayload>
        }
        update: {
          args: Prisma.ColumnEUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ColumnEPayload>
        }
        deleteMany: {
          args: Prisma.ColumnEDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.ColumnEUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.ColumnEUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ColumnEPayload>[]
        }
        upsert: {
          args: Prisma.ColumnEUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ColumnEPayload>
        }
        aggregate: {
          args: Prisma.ColumnEAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateColumnE>
        }
        groupBy: {
          args: Prisma.ColumnEGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.ColumnEGroupByOutputType>[]
        }
        count: {
          args: Prisma.ColumnECountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.ColumnECountAggregateOutputType> | number
        }
      }
    }
    RowEAV: {
      payload: Prisma.$RowEAVPayload<ExtArgs>
      fields: Prisma.RowEAVFieldRefs
      operations: {
        findUnique: {
          args: Prisma.RowEAVFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$RowEAVPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.RowEAVFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$RowEAVPayload>
        }
        findFirst: {
          args: Prisma.RowEAVFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$RowEAVPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.RowEAVFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$RowEAVPayload>
        }
        findMany: {
          args: Prisma.RowEAVFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$RowEAVPayload>[]
        }
        create: {
          args: Prisma.RowEAVCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$RowEAVPayload>
        }
        createMany: {
          args: Prisma.RowEAVCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.RowEAVCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$RowEAVPayload>[]
        }
        delete: {
          args: Prisma.RowEAVDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$RowEAVPayload>
        }
        update: {
          args: Prisma.RowEAVUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$RowEAVPayload>
        }
        deleteMany: {
          args: Prisma.RowEAVDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.RowEAVUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.RowEAVUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$RowEAVPayload>[]
        }
        upsert: {
          args: Prisma.RowEAVUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$RowEAVPayload>
        }
        aggregate: {
          args: Prisma.RowEAVAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateRowEAV>
        }
        groupBy: {
          args: Prisma.RowEAVGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.RowEAVGroupByOutputType>[]
        }
        count: {
          args: Prisma.RowEAVCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.RowEAVCountAggregateOutputType> | number
        }
      }
    }
  }
} & {
  other: {
    payload: any
    operations: {
      $executeRaw: {
        args: [query: TemplateStringsArray | Sql, ...values: any[]],
        result: any
      }
      $executeRawUnsafe: {
        args: [query: string, ...values: any[]],
        result: any
      }
      $queryRaw: {
        args: [query: TemplateStringsArray | Sql, ...values: any[]],
        result: any
      }
      $queryRawUnsafe: {
        args: [query: string, ...values: any[]],
        result: any
      }
    }
  }
}

/**
 * Enums
 */

export const TransactionIsolationLevel = runtime.makeStrictEnum({
  ReadUncommitted: 'ReadUncommitted',
  ReadCommitted: 'ReadCommitted',
  RepeatableRead: 'RepeatableRead',
  Serializable: 'Serializable'
} as const)

export type TransactionIsolationLevel = (typeof TransactionIsolationLevel)[keyof typeof TransactionIsolationLevel]


export const EntityScalarFieldEnum = {
  id: 'id',
  name: 'name',
  createdAt: 'createdAt'
} as const

export type EntityScalarFieldEnum = (typeof EntityScalarFieldEnum)[keyof typeof EntityScalarFieldEnum]


export const AttributeScalarFieldEnum = {
  id: 'id',
  name: 'name',
  typeId: 'typeId',
  rangeId: 'rangeId',
  KVSetId: 'KVSetId'
} as const

export type AttributeScalarFieldEnum = (typeof AttributeScalarFieldEnum)[keyof typeof AttributeScalarFieldEnum]


export const ValueScalarFieldEnum = {
  id: 'id',
  ts: 'ts',
  ent: 'ent',
  att: 'att',
  strVal: 'strVal',
  numVal: 'numVal',
  dtVal: 'dtVal',
  blbVal: 'blbVal',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  deletedAt: 'deletedAt'
} as const

export type ValueScalarFieldEnum = (typeof ValueScalarFieldEnum)[keyof typeof ValueScalarFieldEnum]


export const KVSetScalarFieldEnum = {
  id: 'id',
  name: 'name'
} as const

export type KVSetScalarFieldEnum = (typeof KVSetScalarFieldEnum)[keyof typeof KVSetScalarFieldEnum]


export const KVScalarFieldEnum = {
  id: 'id',
  setId: 'setId',
  key: 'key',
  value: 'value'
} as const

export type KVScalarFieldEnum = (typeof KVScalarFieldEnum)[keyof typeof KVScalarFieldEnum]


export const RangeScalarFieldEnum = {
  id: 'id',
  min: 'min',
  max: 'max'
} as const

export type RangeScalarFieldEnum = (typeof RangeScalarFieldEnum)[keyof typeof RangeScalarFieldEnum]


export const AttrTypeScalarFieldEnum = {
  id: 'id',
  name: 'name'
} as const

export type AttrTypeScalarFieldEnum = (typeof AttrTypeScalarFieldEnum)[keyof typeof AttrTypeScalarFieldEnum]


export const TemplateScalarFieldEnum = {
  id: 'id',
  name: 'name'
} as const

export type TemplateScalarFieldEnum = (typeof TemplateScalarFieldEnum)[keyof typeof TemplateScalarFieldEnum]


export const QueryScalarFieldEnum = {
  id: 'id',
  name: 'name',
  params: 'params'
} as const

export type QueryScalarFieldEnum = (typeof QueryScalarFieldEnum)[keyof typeof QueryScalarFieldEnum]


export const TableEScalarFieldEnum = {
  id: 'id',
  name: 'name'
} as const

export type TableEScalarFieldEnum = (typeof TableEScalarFieldEnum)[keyof typeof TableEScalarFieldEnum]


export const ColumnEScalarFieldEnum = {
  id: 'id',
  col: 'col',
  tab: 'tab',
  key: 'key',
  name: 'name',
  typ: 'typ',
  ran: 'ran',
  kvs: 'kvs'
} as const

export type ColumnEScalarFieldEnum = (typeof ColumnEScalarFieldEnum)[keyof typeof ColumnEScalarFieldEnum]


export const RowEAVScalarFieldEnum = {
  id: 'id',
  row: 'row',
  col: 'col',
  strVal: 'strVal',
  numVal: 'numVal',
  dtVal: 'dtVal',
  blbVal: 'blbVal',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  deletedAt: 'deletedAt'
} as const

export type RowEAVScalarFieldEnum = (typeof RowEAVScalarFieldEnum)[keyof typeof RowEAVScalarFieldEnum]


export const SortOrder = {
  asc: 'asc',
  desc: 'desc'
} as const

export type SortOrder = (typeof SortOrder)[keyof typeof SortOrder]


export const QueryMode = {
  default: 'default',
  insensitive: 'insensitive'
} as const

export type QueryMode = (typeof QueryMode)[keyof typeof QueryMode]


export const NullsOrder = {
  first: 'first',
  last: 'last'
} as const

export type NullsOrder = (typeof NullsOrder)[keyof typeof NullsOrder]



/**
 * Field references
 */


/**
 * Reference to a field of type 'Int'
 */
export type IntFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'Int'>
    


/**
 * Reference to a field of type 'Int[]'
 */
export type ListIntFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'Int[]'>
    


/**
 * Reference to a field of type 'String'
 */
export type StringFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'String'>
    


/**
 * Reference to a field of type 'String[]'
 */
export type ListStringFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'String[]'>
    


/**
 * Reference to a field of type 'DateTime'
 */
export type DateTimeFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'DateTime'>
    


/**
 * Reference to a field of type 'DateTime[]'
 */
export type ListDateTimeFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'DateTime[]'>
    


/**
 * Reference to a field of type 'Float'
 */
export type FloatFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'Float'>
    


/**
 * Reference to a field of type 'Float[]'
 */
export type ListFloatFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'Float[]'>
    


/**
 * Reference to a field of type 'Bytes'
 */
export type BytesFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'Bytes'>
    


/**
 * Reference to a field of type 'Bytes[]'
 */
export type ListBytesFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'Bytes[]'>
    

/**
 * Batch Payload for updateMany & deleteMany & createMany
 */
export type BatchPayload = {
  count: number
}

export const defineExtension = runtime.Extensions.defineExtension as unknown as runtime.Types.Extensions.ExtendsHook<"define", TypeMapCb, runtime.Types.Extensions.DefaultArgs>
export type DefaultPrismaClient = PrismaClient
export type ErrorFormat = 'pretty' | 'colorless' | 'minimal'
export type PrismaClientOptions = ({
  /**
   * Instance of a Driver Adapter, e.g., like one provided by `@prisma/adapter-pg`.
   */
  adapter: runtime.SqlDriverAdapterFactory
  accelerateUrl?: never
} | {
  /**
   * Prisma Accelerate URL allowing the client to connect through Accelerate instead of a direct database.
   */
  accelerateUrl: string
  adapter?: never
}) & {
  /**
   * @default "colorless"
   */
  errorFormat?: ErrorFormat
  /**
   * @example
   * ```
   * // Shorthand for `emit: 'stdout'`
   * log: ['query', 'info', 'warn', 'error']
   * 
   * // Emit as events only
   * log: [
   *   { emit: 'event', level: 'query' },
   *   { emit: 'event', level: 'info' },
   *   { emit: 'event', level: 'warn' }
   *   { emit: 'event', level: 'error' }
   * ]
   * 
   * / Emit as events and log to stdout
   * og: [
   *  { emit: 'stdout', level: 'query' },
   *  { emit: 'stdout', level: 'info' },
   *  { emit: 'stdout', level: 'warn' }
   *  { emit: 'stdout', level: 'error' }
   * 
   * ```
   * Read more in our [docs](https://pris.ly/d/logging).
   */
  log?: (LogLevel | LogDefinition)[]
  /**
   * The default values for transactionOptions
   * maxWait ?= 2000
   * timeout ?= 5000
   */
  transactionOptions?: {
    maxWait?: number
    timeout?: number
    isolationLevel?: TransactionIsolationLevel
  }
  /**
   * Global configuration for omitting model fields by default.
   * 
   * @example
   * ```
   * const prisma = new PrismaClient({
   *   omit: {
   *     user: {
   *       password: true
   *     }
   *   }
   * })
   * ```
   */
  omit?: GlobalOmitConfig
  /**
   * SQL commenter plugins that add metadata to SQL queries as comments.
   * Comments follow the sqlcommenter format: https://google.github.io/sqlcommenter/
   * 
   * @example
   * ```
   * const prisma = new PrismaClient({
   *   adapter,
   *   comments: [
   *     traceContext(),
   *     queryInsights(),
   *   ],
   * })
   * ```
   */
  comments?: runtime.SqlCommenterPlugin[]
}
export type GlobalOmitConfig = {
  entity?: Prisma.EntityOmit
  attribute?: Prisma.AttributeOmit
  value?: Prisma.ValueOmit
  kVSet?: Prisma.KVSetOmit
  kV?: Prisma.KVOmit
  range?: Prisma.RangeOmit
  attrType?: Prisma.AttrTypeOmit
  template?: Prisma.TemplateOmit
  query?: Prisma.QueryOmit
  tableE?: Prisma.TableEOmit
  columnE?: Prisma.ColumnEOmit
  rowEAV?: Prisma.RowEAVOmit
}

/* Types for Logging */
export type LogLevel = 'info' | 'query' | 'warn' | 'error'
export type LogDefinition = {
  level: LogLevel
  emit: 'stdout' | 'event'
}

export type CheckIsLogLevel<T> = T extends LogLevel ? T : never;

export type GetLogType<T> = CheckIsLogLevel<
  T extends LogDefinition ? T['level'] : T
>;

export type GetEvents<T extends any[]> = T extends Array<LogLevel | LogDefinition>
  ? GetLogType<T[number]>
  : never;

export type QueryEvent = {
  timestamp: Date
  query: string
  params: string
  duration: number
  target: string
}

export type LogEvent = {
  timestamp: Date
  message: string
  target: string
}
/* End Types for Logging */


export type PrismaAction =
  | 'findUnique'
  | 'findUniqueOrThrow'
  | 'findMany'
  | 'findFirst'
  | 'findFirstOrThrow'
  | 'create'
  | 'createMany'
  | 'createManyAndReturn'
  | 'update'
  | 'updateMany'
  | 'updateManyAndReturn'
  | 'upsert'
  | 'delete'
  | 'deleteMany'
  | 'executeRaw'
  | 'queryRaw'
  | 'aggregate'
  | 'count'
  | 'runCommandRaw'
  | 'findRaw'
  | 'groupBy'

/**
 * `PrismaClient` proxy available in interactive transactions.
 */
export type TransactionClient = Omit<DefaultPrismaClient, runtime.ITXClientDenyList>

