
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * WARNING: This is an internal file that is subject to change!
 *
 * 🛑 Under no circumstances should you import this file directly! 🛑
 *
 * All exports from this file are wrapped under a `Prisma` namespace object in the browser.ts file.
 * While this enables partial backward compatibility, it is not part of the stable public API.
 *
 * If you are looking for your Models, Enums, and Input Types, please import them from the respective
 * model files in the `model` directory!
 */

import * as runtime from "@prisma/client/runtime/index-browser"

export type * from '../models.js'
export type * from './prismaNamespace.js'

export const Decimal = runtime.Decimal


export const NullTypes = {
  DbNull: runtime.NullTypes.DbNull as (new (secret: never) => typeof runtime.DbNull),
  JsonNull: runtime.NullTypes.JsonNull as (new (secret: never) => typeof runtime.JsonNull),
  AnyNull: runtime.NullTypes.AnyNull as (new (secret: never) => typeof runtime.AnyNull),
}
/**
 * Helper for filtering JSON entries that have `null` on the database (empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const DbNull = runtime.DbNull

/**
 * Helper for filtering JSON entries that have JSON `null` values (not empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const JsonNull = runtime.JsonNull

/**
 * Helper for filtering JSON entries that are `Prisma.DbNull` or `Prisma.JsonNull`
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const AnyNull = runtime.AnyNull


export const ModelName = {
  Entity: 'Entity',
  Attribute: 'Attribute',
  Value: 'Value',
  KVSet: 'KVSet',
  KV: 'KV',
  Range: 'Range',
  AttrType: 'AttrType',
  Template: 'Template',
  Query: 'Query',
  TableE: 'TableE',
  ColumnE: 'ColumnE',
  RowEAV: 'RowEAV'
} as const

export type ModelName = (typeof ModelName)[keyof typeof ModelName]

/*
 * Enums
 */

export const TransactionIsolationLevel = {
  ReadUncommitted: 'ReadUncommitted',
  ReadCommitted: 'ReadCommitted',
  RepeatableRead: 'RepeatableRead',
  Serializable: 'Serializable'
} as const

export type TransactionIsolationLevel = (typeof TransactionIsolationLevel)[keyof typeof TransactionIsolationLevel]


export const EntityScalarFieldEnum = {
  id: 'id',
  name: 'name',
  createdAt: 'createdAt'
} as const

export type EntityScalarFieldEnum = (typeof EntityScalarFieldEnum)[keyof typeof EntityScalarFieldEnum]


export const AttributeScalarFieldEnum = {
  id: 'id',
  name: 'name',
  typeId: 'typeId',
  rangeId: 'rangeId',
  KVSetId: 'KVSetId'
} as const

export type AttributeScalarFieldEnum = (typeof AttributeScalarFieldEnum)[keyof typeof AttributeScalarFieldEnum]


export const ValueScalarFieldEnum = {
  id: 'id',
  ts: 'ts',
  ent: 'ent',
  att: 'att',
  strVal: 'strVal',
  numVal: 'numVal',
  dtVal: 'dtVal',
  blbVal: 'blbVal',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  deletedAt: 'deletedAt'
} as const

export type ValueScalarFieldEnum = (typeof ValueScalarFieldEnum)[keyof typeof ValueScalarFieldEnum]


export const KVSetScalarFieldEnum = {
  id: 'id',
  name: 'name'
} as const

export type KVSetScalarFieldEnum = (typeof KVSetScalarFieldEnum)[keyof typeof KVSetScalarFieldEnum]


export const KVScalarFieldEnum = {
  id: 'id',
  setId: 'setId',
  key: 'key',
  value: 'value'
} as const

export type KVScalarFieldEnum = (typeof KVScalarFieldEnum)[keyof typeof KVScalarFieldEnum]


export const RangeScalarFieldEnum = {
  id: 'id',
  min: 'min',
  max: 'max'
} as const

export type RangeScalarFieldEnum = (typeof RangeScalarFieldEnum)[keyof typeof RangeScalarFieldEnum]


export const AttrTypeScalarFieldEnum = {
  id: 'id',
  name: 'name'
} as const

export type AttrTypeScalarFieldEnum = (typeof AttrTypeScalarFieldEnum)[keyof typeof AttrTypeScalarFieldEnum]


export const TemplateScalarFieldEnum = {
  id: 'id',
  name: 'name'
} as const

export type TemplateScalarFieldEnum = (typeof TemplateScalarFieldEnum)[keyof typeof TemplateScalarFieldEnum]


export const QueryScalarFieldEnum = {
  id: 'id',
  name: 'name',
  params: 'params'
} as const

export type QueryScalarFieldEnum = (typeof QueryScalarFieldEnum)[keyof typeof QueryScalarFieldEnum]


export const TableEScalarFieldEnum = {
  id: 'id',
  name: 'name'
} as const

export type TableEScalarFieldEnum = (typeof TableEScalarFieldEnum)[keyof typeof TableEScalarFieldEnum]


export const ColumnEScalarFieldEnum = {
  id: 'id',
  col: 'col',
  tab: 'tab',
  key: 'key',
  name: 'name',
  typ: 'typ',
  ran: 'ran',
  kvs: 'kvs'
} as const

export type ColumnEScalarFieldEnum = (typeof ColumnEScalarFieldEnum)[keyof typeof ColumnEScalarFieldEnum]


export const RowEAVScalarFieldEnum = {
  id: 'id',
  row: 'row',
  col: 'col',
  strVal: 'strVal',
  numVal: 'numVal',
  dtVal: 'dtVal',
  blbVal: 'blbVal'
} as const

export type RowEAVScalarFieldEnum = (typeof RowEAVScalarFieldEnum)[keyof typeof RowEAVScalarFieldEnum]


export const SortOrder = {
  asc: 'asc',
  desc: 'desc'
} as const

export type SortOrder = (typeof SortOrder)[keyof typeof SortOrder]


export const QueryMode = {
  default: 'default',
  insensitive: 'insensitive'
} as const

export type QueryMode = (typeof QueryMode)[keyof typeof QueryMode]


export const NullsOrder = {
  first: 'first',
  last: 'last'
} as const

export type NullsOrder = (typeof NullsOrder)[keyof typeof NullsOrder]

