
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file should be your main import to use Prisma-related types and utilities in a browser. 
 * Use it to get access to models, enums, and input types.
 * 
 * This file does not contain a `PrismaClient` class, nor several other helpers that are intended as server-side only.
 * See `client.ts` for the standard, server-side entry point.
 *
 * 🟢 You can import this file directly.
 */

import * as Prisma from './internal/prismaNamespaceBrowser.js'
export { Prisma }
export * as $Enums from './enums.js'
export * from './enums.js';
/**
 * Model Entity
 * 
 */
export type Entity = Prisma.EntityModel
/**
 * Model Attribute
 * 
 */
export type Attribute = Prisma.AttributeModel
/**
 * Model Value
 * 
 */
export type Value = Prisma.ValueModel
/**
 * Model KVSet
 * 
 */
export type KVSet = Prisma.KVSetModel
/**
 * Model KV
 * 
 */
export type KV = Prisma.KVModel
/**
 * Model Range
 * 
 */
export type Range = Prisma.RangeModel
/**
 * Model AttrType
 * 
 */
export type AttrType = Prisma.AttrTypeModel
/**
 * Model Template
 * 
 */
export type Template = Prisma.TemplateModel
/**
 * Model Query
 * 
 */
export type Query = Prisma.QueryModel
/**
 * Model TableE
 * 
 */
export type TableE = Prisma.TableEModel
/**
 * Model ColumnE
 * 
 */
export type ColumnE = Prisma.ColumnEModel
/**
 * Model Table1
 * 
 */
export type Table1 = Prisma.Table1Model
