
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `AttrType` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model AttrType
 * 
 */
export type AttrTypeModel = runtime.Types.Result.DefaultSelection<Prisma.$AttrTypePayload>

export type AggregateAttrType = {
  _count: AttrTypeCountAggregateOutputType | null
  _avg: AttrTypeAvgAggregateOutputType | null
  _sum: AttrTypeSumAggregateOutputType | null
  _min: AttrTypeMinAggregateOutputType | null
  _max: AttrTypeMaxAggregateOutputType | null
}

export type AttrTypeAvgAggregateOutputType = {
  id: number | null
}

export type AttrTypeSumAggregateOutputType = {
  id: number | null
}

export type AttrTypeMinAggregateOutputType = {
  id: number | null
  name: string | null
}

export type AttrTypeMaxAggregateOutputType = {
  id: number | null
  name: string | null
}

export type AttrTypeCountAggregateOutputType = {
  id: number
  name: number
  _all: number
}


export type AttrTypeAvgAggregateInputType = {
  id?: true
}

export type AttrTypeSumAggregateInputType = {
  id?: true
}

export type AttrTypeMinAggregateInputType = {
  id?: true
  name?: true
}

export type AttrTypeMaxAggregateInputType = {
  id?: true
  name?: true
}

export type AttrTypeCountAggregateInputType = {
  id?: true
  name?: true
  _all?: true
}

export type AttrTypeAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which AttrType to aggregate.
   */
  where?: Prisma.AttrTypeWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of AttrTypes to fetch.
   */
  orderBy?: Prisma.AttrTypeOrderByWithRelationInput | Prisma.AttrTypeOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.AttrTypeWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` AttrTypes from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` AttrTypes.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned AttrTypes
  **/
  _count?: true | AttrTypeCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: AttrTypeAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: AttrTypeSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: AttrTypeMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: AttrTypeMaxAggregateInputType
}

export type GetAttrTypeAggregateType<T extends AttrTypeAggregateArgs> = {
      [P in keyof T & keyof AggregateAttrType]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateAttrType[P]>
    : Prisma.GetScalarType<T[P], AggregateAttrType[P]>
}




export type AttrTypeGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.AttrTypeWhereInput
  orderBy?: Prisma.AttrTypeOrderByWithAggregationInput | Prisma.AttrTypeOrderByWithAggregationInput[]
  by: Prisma.AttrTypeScalarFieldEnum[] | Prisma.AttrTypeScalarFieldEnum
  having?: Prisma.AttrTypeScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: AttrTypeCountAggregateInputType | true
  _avg?: AttrTypeAvgAggregateInputType
  _sum?: AttrTypeSumAggregateInputType
  _min?: AttrTypeMinAggregateInputType
  _max?: AttrTypeMaxAggregateInputType
}

export type AttrTypeGroupByOutputType = {
  id: number
  name: string
  _count: AttrTypeCountAggregateOutputType | null
  _avg: AttrTypeAvgAggregateOutputType | null
  _sum: AttrTypeSumAggregateOutputType | null
  _min: AttrTypeMinAggregateOutputType | null
  _max: AttrTypeMaxAggregateOutputType | null
}

type GetAttrTypeGroupByPayload<T extends AttrTypeGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<AttrTypeGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof AttrTypeGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], AttrTypeGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], AttrTypeGroupByOutputType[P]>
      }
    >
  >



export type AttrTypeWhereInput = {
  AND?: Prisma.AttrTypeWhereInput | Prisma.AttrTypeWhereInput[]
  OR?: Prisma.AttrTypeWhereInput[]
  NOT?: Prisma.AttrTypeWhereInput | Prisma.AttrTypeWhereInput[]
  id?: Prisma.IntFilter<"AttrType"> | number
  name?: Prisma.StringFilter<"AttrType"> | string
  attributes?: Prisma.AttributeListRelationFilter
}

export type AttrTypeOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  attributes?: Prisma.AttributeOrderByRelationAggregateInput
}

export type AttrTypeWhereUniqueInput = Prisma.AtLeast<{
  id?: number
  AND?: Prisma.AttrTypeWhereInput | Prisma.AttrTypeWhereInput[]
  OR?: Prisma.AttrTypeWhereInput[]
  NOT?: Prisma.AttrTypeWhereInput | Prisma.AttrTypeWhereInput[]
  name?: Prisma.StringFilter<"AttrType"> | string
  attributes?: Prisma.AttributeListRelationFilter
}, "id">

export type AttrTypeOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  _count?: Prisma.AttrTypeCountOrderByAggregateInput
  _avg?: Prisma.AttrTypeAvgOrderByAggregateInput
  _max?: Prisma.AttrTypeMaxOrderByAggregateInput
  _min?: Prisma.AttrTypeMinOrderByAggregateInput
  _sum?: Prisma.AttrTypeSumOrderByAggregateInput
}

export type AttrTypeScalarWhereWithAggregatesInput = {
  AND?: Prisma.AttrTypeScalarWhereWithAggregatesInput | Prisma.AttrTypeScalarWhereWithAggregatesInput[]
  OR?: Prisma.AttrTypeScalarWhereWithAggregatesInput[]
  NOT?: Prisma.AttrTypeScalarWhereWithAggregatesInput | Prisma.AttrTypeScalarWhereWithAggregatesInput[]
  id?: Prisma.IntWithAggregatesFilter<"AttrType"> | number
  name?: Prisma.StringWithAggregatesFilter<"AttrType"> | string
}

export type AttrTypeCreateInput = {
  name: string
  attributes?: Prisma.AttributeCreateNestedManyWithoutTypeInput
}

export type AttrTypeUncheckedCreateInput = {
  id?: number
  name: string
  attributes?: Prisma.AttributeUncheckedCreateNestedManyWithoutTypeInput
}

export type AttrTypeUpdateInput = {
  name?: Prisma.StringFieldUpdateOperationsInput | string
  attributes?: Prisma.AttributeUpdateManyWithoutTypeNestedInput
}

export type AttrTypeUncheckedUpdateInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  name?: Prisma.StringFieldUpdateOperationsInput | string
  attributes?: Prisma.AttributeUncheckedUpdateManyWithoutTypeNestedInput
}

export type AttrTypeCreateManyInput = {
  id?: number
  name: string
}

export type AttrTypeUpdateManyMutationInput = {
  name?: Prisma.StringFieldUpdateOperationsInput | string
}

export type AttrTypeUncheckedUpdateManyInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  name?: Prisma.StringFieldUpdateOperationsInput | string
}

export type AttrTypeScalarRelationFilter = {
  is?: Prisma.AttrTypeWhereInput
  isNot?: Prisma.AttrTypeWhereInput
}

export type AttrTypeCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
}

export type AttrTypeAvgOrderByAggregateInput = {
  id?: Prisma.SortOrder
}

export type AttrTypeMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
}

export type AttrTypeMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
}

export type AttrTypeSumOrderByAggregateInput = {
  id?: Prisma.SortOrder
}

export type AttrTypeCreateNestedOneWithoutAttributesInput = {
  create?: Prisma.XOR<Prisma.AttrTypeCreateWithoutAttributesInput, Prisma.AttrTypeUncheckedCreateWithoutAttributesInput>
  connectOrCreate?: Prisma.AttrTypeCreateOrConnectWithoutAttributesInput
  connect?: Prisma.AttrTypeWhereUniqueInput
}

export type AttrTypeUpdateOneRequiredWithoutAttributesNestedInput = {
  create?: Prisma.XOR<Prisma.AttrTypeCreateWithoutAttributesInput, Prisma.AttrTypeUncheckedCreateWithoutAttributesInput>
  connectOrCreate?: Prisma.AttrTypeCreateOrConnectWithoutAttributesInput
  upsert?: Prisma.AttrTypeUpsertWithoutAttributesInput
  connect?: Prisma.AttrTypeWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.AttrTypeUpdateToOneWithWhereWithoutAttributesInput, Prisma.AttrTypeUpdateWithoutAttributesInput>, Prisma.AttrTypeUncheckedUpdateWithoutAttributesInput>
}

export type AttrTypeCreateWithoutAttributesInput = {
  name: string
}

export type AttrTypeUncheckedCreateWithoutAttributesInput = {
  id?: number
  name: string
}

export type AttrTypeCreateOrConnectWithoutAttributesInput = {
  where: Prisma.AttrTypeWhereUniqueInput
  create: Prisma.XOR<Prisma.AttrTypeCreateWithoutAttributesInput, Prisma.AttrTypeUncheckedCreateWithoutAttributesInput>
}

export type AttrTypeUpsertWithoutAttributesInput = {
  update: Prisma.XOR<Prisma.AttrTypeUpdateWithoutAttributesInput, Prisma.AttrTypeUncheckedUpdateWithoutAttributesInput>
  create: Prisma.XOR<Prisma.AttrTypeCreateWithoutAttributesInput, Prisma.AttrTypeUncheckedCreateWithoutAttributesInput>
  where?: Prisma.AttrTypeWhereInput
}

export type AttrTypeUpdateToOneWithWhereWithoutAttributesInput = {
  where?: Prisma.AttrTypeWhereInput
  data: Prisma.XOR<Prisma.AttrTypeUpdateWithoutAttributesInput, Prisma.AttrTypeUncheckedUpdateWithoutAttributesInput>
}

export type AttrTypeUpdateWithoutAttributesInput = {
  name?: Prisma.StringFieldUpdateOperationsInput | string
}

export type AttrTypeUncheckedUpdateWithoutAttributesInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  name?: Prisma.StringFieldUpdateOperationsInput | string
}


/**
 * Count Type AttrTypeCountOutputType
 */

export type AttrTypeCountOutputType = {
  attributes: number
}

export type AttrTypeCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  attributes?: boolean | AttrTypeCountOutputTypeCountAttributesArgs
}

/**
 * AttrTypeCountOutputType without action
 */
export type AttrTypeCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AttrTypeCountOutputType
   */
  select?: Prisma.AttrTypeCountOutputTypeSelect<ExtArgs> | null
}

/**
 * AttrTypeCountOutputType without action
 */
export type AttrTypeCountOutputTypeCountAttributesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.AttributeWhereInput
}


export type AttrTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  attributes?: boolean | Prisma.AttrType$attributesArgs<ExtArgs>
  _count?: boolean | Prisma.AttrTypeCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["attrType"]>

export type AttrTypeSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
}, ExtArgs["result"]["attrType"]>

export type AttrTypeSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
}, ExtArgs["result"]["attrType"]>

export type AttrTypeSelectScalar = {
  id?: boolean
  name?: boolean
}

export type AttrTypeOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "name", ExtArgs["result"]["attrType"]>
export type AttrTypeInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  attributes?: boolean | Prisma.AttrType$attributesArgs<ExtArgs>
  _count?: boolean | Prisma.AttrTypeCountOutputTypeDefaultArgs<ExtArgs>
}
export type AttrTypeIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}
export type AttrTypeIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}

export type $AttrTypePayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "AttrType"
  objects: {
    attributes: Prisma.$AttributePayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: number
    name: string
  }, ExtArgs["result"]["attrType"]>
  composites: {}
}

export type AttrTypeGetPayload<S extends boolean | null | undefined | AttrTypeDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$AttrTypePayload, S>

export type AttrTypeCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<AttrTypeFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: AttrTypeCountAggregateInputType | true
  }

export interface AttrTypeDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['AttrType'], meta: { name: 'AttrType' } }
  /**
   * Find zero or one AttrType that matches the filter.
   * @param {AttrTypeFindUniqueArgs} args - Arguments to find a AttrType
   * @example
   * // Get one AttrType
   * const attrType = await prisma.attrType.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends AttrTypeFindUniqueArgs>(args: Prisma.SelectSubset<T, AttrTypeFindUniqueArgs<ExtArgs>>): Prisma.Prisma__AttrTypeClient<runtime.Types.Result.GetResult<Prisma.$AttrTypePayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one AttrType that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {AttrTypeFindUniqueOrThrowArgs} args - Arguments to find a AttrType
   * @example
   * // Get one AttrType
   * const attrType = await prisma.attrType.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends AttrTypeFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, AttrTypeFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__AttrTypeClient<runtime.Types.Result.GetResult<Prisma.$AttrTypePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first AttrType that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AttrTypeFindFirstArgs} args - Arguments to find a AttrType
   * @example
   * // Get one AttrType
   * const attrType = await prisma.attrType.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends AttrTypeFindFirstArgs>(args?: Prisma.SelectSubset<T, AttrTypeFindFirstArgs<ExtArgs>>): Prisma.Prisma__AttrTypeClient<runtime.Types.Result.GetResult<Prisma.$AttrTypePayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first AttrType that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AttrTypeFindFirstOrThrowArgs} args - Arguments to find a AttrType
   * @example
   * // Get one AttrType
   * const attrType = await prisma.attrType.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends AttrTypeFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, AttrTypeFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__AttrTypeClient<runtime.Types.Result.GetResult<Prisma.$AttrTypePayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more AttrTypes that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AttrTypeFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all AttrTypes
   * const attrTypes = await prisma.attrType.findMany()
   * 
   * // Get first 10 AttrTypes
   * const attrTypes = await prisma.attrType.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const attrTypeWithIdOnly = await prisma.attrType.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends AttrTypeFindManyArgs>(args?: Prisma.SelectSubset<T, AttrTypeFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$AttrTypePayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a AttrType.
   * @param {AttrTypeCreateArgs} args - Arguments to create a AttrType.
   * @example
   * // Create one AttrType
   * const AttrType = await prisma.attrType.create({
   *   data: {
   *     // ... data to create a AttrType
   *   }
   * })
   * 
   */
  create<T extends AttrTypeCreateArgs>(args: Prisma.SelectSubset<T, AttrTypeCreateArgs<ExtArgs>>): Prisma.Prisma__AttrTypeClient<runtime.Types.Result.GetResult<Prisma.$AttrTypePayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many AttrTypes.
   * @param {AttrTypeCreateManyArgs} args - Arguments to create many AttrTypes.
   * @example
   * // Create many AttrTypes
   * const attrType = await prisma.attrType.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends AttrTypeCreateManyArgs>(args?: Prisma.SelectSubset<T, AttrTypeCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many AttrTypes and returns the data saved in the database.
   * @param {AttrTypeCreateManyAndReturnArgs} args - Arguments to create many AttrTypes.
   * @example
   * // Create many AttrTypes
   * const attrType = await prisma.attrType.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many AttrTypes and only return the `id`
   * const attrTypeWithIdOnly = await prisma.attrType.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends AttrTypeCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, AttrTypeCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$AttrTypePayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a AttrType.
   * @param {AttrTypeDeleteArgs} args - Arguments to delete one AttrType.
   * @example
   * // Delete one AttrType
   * const AttrType = await prisma.attrType.delete({
   *   where: {
   *     // ... filter to delete one AttrType
   *   }
   * })
   * 
   */
  delete<T extends AttrTypeDeleteArgs>(args: Prisma.SelectSubset<T, AttrTypeDeleteArgs<ExtArgs>>): Prisma.Prisma__AttrTypeClient<runtime.Types.Result.GetResult<Prisma.$AttrTypePayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one AttrType.
   * @param {AttrTypeUpdateArgs} args - Arguments to update one AttrType.
   * @example
   * // Update one AttrType
   * const attrType = await prisma.attrType.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends AttrTypeUpdateArgs>(args: Prisma.SelectSubset<T, AttrTypeUpdateArgs<ExtArgs>>): Prisma.Prisma__AttrTypeClient<runtime.Types.Result.GetResult<Prisma.$AttrTypePayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more AttrTypes.
   * @param {AttrTypeDeleteManyArgs} args - Arguments to filter AttrTypes to delete.
   * @example
   * // Delete a few AttrTypes
   * const { count } = await prisma.attrType.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends AttrTypeDeleteManyArgs>(args?: Prisma.SelectSubset<T, AttrTypeDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more AttrTypes.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AttrTypeUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many AttrTypes
   * const attrType = await prisma.attrType.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends AttrTypeUpdateManyArgs>(args: Prisma.SelectSubset<T, AttrTypeUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more AttrTypes and returns the data updated in the database.
   * @param {AttrTypeUpdateManyAndReturnArgs} args - Arguments to update many AttrTypes.
   * @example
   * // Update many AttrTypes
   * const attrType = await prisma.attrType.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more AttrTypes and only return the `id`
   * const attrTypeWithIdOnly = await prisma.attrType.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends AttrTypeUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, AttrTypeUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$AttrTypePayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one AttrType.
   * @param {AttrTypeUpsertArgs} args - Arguments to update or create a AttrType.
   * @example
   * // Update or create a AttrType
   * const attrType = await prisma.attrType.upsert({
   *   create: {
   *     // ... data to create a AttrType
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the AttrType we want to update
   *   }
   * })
   */
  upsert<T extends AttrTypeUpsertArgs>(args: Prisma.SelectSubset<T, AttrTypeUpsertArgs<ExtArgs>>): Prisma.Prisma__AttrTypeClient<runtime.Types.Result.GetResult<Prisma.$AttrTypePayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of AttrTypes.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AttrTypeCountArgs} args - Arguments to filter AttrTypes to count.
   * @example
   * // Count the number of AttrTypes
   * const count = await prisma.attrType.count({
   *   where: {
   *     // ... the filter for the AttrTypes we want to count
   *   }
   * })
  **/
  count<T extends AttrTypeCountArgs>(
    args?: Prisma.Subset<T, AttrTypeCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], AttrTypeCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a AttrType.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AttrTypeAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends AttrTypeAggregateArgs>(args: Prisma.Subset<T, AttrTypeAggregateArgs>): Prisma.PrismaPromise<GetAttrTypeAggregateType<T>>

  /**
   * Group by AttrType.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AttrTypeGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends AttrTypeGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: AttrTypeGroupByArgs['orderBy'] }
      : { orderBy?: AttrTypeGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, AttrTypeGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetAttrTypeGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the AttrType model
 */
readonly fields: AttrTypeFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for AttrType.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__AttrTypeClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  attributes<T extends Prisma.AttrType$attributesArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.AttrType$attributesArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$AttributePayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the AttrType model
 */
export interface AttrTypeFieldRefs {
  readonly id: Prisma.FieldRef<"AttrType", 'Int'>
  readonly name: Prisma.FieldRef<"AttrType", 'String'>
}
    

// Custom InputTypes
/**
 * AttrType findUnique
 */
export type AttrTypeFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AttrType
   */
  select?: Prisma.AttrTypeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AttrType
   */
  omit?: Prisma.AttrTypeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AttrTypeInclude<ExtArgs> | null
  /**
   * Filter, which AttrType to fetch.
   */
  where: Prisma.AttrTypeWhereUniqueInput
}

/**
 * AttrType findUniqueOrThrow
 */
export type AttrTypeFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AttrType
   */
  select?: Prisma.AttrTypeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AttrType
   */
  omit?: Prisma.AttrTypeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AttrTypeInclude<ExtArgs> | null
  /**
   * Filter, which AttrType to fetch.
   */
  where: Prisma.AttrTypeWhereUniqueInput
}

/**
 * AttrType findFirst
 */
export type AttrTypeFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AttrType
   */
  select?: Prisma.AttrTypeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AttrType
   */
  omit?: Prisma.AttrTypeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AttrTypeInclude<ExtArgs> | null
  /**
   * Filter, which AttrType to fetch.
   */
  where?: Prisma.AttrTypeWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of AttrTypes to fetch.
   */
  orderBy?: Prisma.AttrTypeOrderByWithRelationInput | Prisma.AttrTypeOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for AttrTypes.
   */
  cursor?: Prisma.AttrTypeWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` AttrTypes from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` AttrTypes.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of AttrTypes.
   */
  distinct?: Prisma.AttrTypeScalarFieldEnum | Prisma.AttrTypeScalarFieldEnum[]
}

/**
 * AttrType findFirstOrThrow
 */
export type AttrTypeFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AttrType
   */
  select?: Prisma.AttrTypeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AttrType
   */
  omit?: Prisma.AttrTypeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AttrTypeInclude<ExtArgs> | null
  /**
   * Filter, which AttrType to fetch.
   */
  where?: Prisma.AttrTypeWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of AttrTypes to fetch.
   */
  orderBy?: Prisma.AttrTypeOrderByWithRelationInput | Prisma.AttrTypeOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for AttrTypes.
   */
  cursor?: Prisma.AttrTypeWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` AttrTypes from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` AttrTypes.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of AttrTypes.
   */
  distinct?: Prisma.AttrTypeScalarFieldEnum | Prisma.AttrTypeScalarFieldEnum[]
}

/**
 * AttrType findMany
 */
export type AttrTypeFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AttrType
   */
  select?: Prisma.AttrTypeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AttrType
   */
  omit?: Prisma.AttrTypeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AttrTypeInclude<ExtArgs> | null
  /**
   * Filter, which AttrTypes to fetch.
   */
  where?: Prisma.AttrTypeWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of AttrTypes to fetch.
   */
  orderBy?: Prisma.AttrTypeOrderByWithRelationInput | Prisma.AttrTypeOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing AttrTypes.
   */
  cursor?: Prisma.AttrTypeWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` AttrTypes from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` AttrTypes.
   */
  skip?: number
  distinct?: Prisma.AttrTypeScalarFieldEnum | Prisma.AttrTypeScalarFieldEnum[]
}

/**
 * AttrType create
 */
export type AttrTypeCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AttrType
   */
  select?: Prisma.AttrTypeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AttrType
   */
  omit?: Prisma.AttrTypeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AttrTypeInclude<ExtArgs> | null
  /**
   * The data needed to create a AttrType.
   */
  data: Prisma.XOR<Prisma.AttrTypeCreateInput, Prisma.AttrTypeUncheckedCreateInput>
}

/**
 * AttrType createMany
 */
export type AttrTypeCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many AttrTypes.
   */
  data: Prisma.AttrTypeCreateManyInput | Prisma.AttrTypeCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * AttrType createManyAndReturn
 */
export type AttrTypeCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AttrType
   */
  select?: Prisma.AttrTypeSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the AttrType
   */
  omit?: Prisma.AttrTypeOmit<ExtArgs> | null
  /**
   * The data used to create many AttrTypes.
   */
  data: Prisma.AttrTypeCreateManyInput | Prisma.AttrTypeCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * AttrType update
 */
export type AttrTypeUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AttrType
   */
  select?: Prisma.AttrTypeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AttrType
   */
  omit?: Prisma.AttrTypeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AttrTypeInclude<ExtArgs> | null
  /**
   * The data needed to update a AttrType.
   */
  data: Prisma.XOR<Prisma.AttrTypeUpdateInput, Prisma.AttrTypeUncheckedUpdateInput>
  /**
   * Choose, which AttrType to update.
   */
  where: Prisma.AttrTypeWhereUniqueInput
}

/**
 * AttrType updateMany
 */
export type AttrTypeUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update AttrTypes.
   */
  data: Prisma.XOR<Prisma.AttrTypeUpdateManyMutationInput, Prisma.AttrTypeUncheckedUpdateManyInput>
  /**
   * Filter which AttrTypes to update
   */
  where?: Prisma.AttrTypeWhereInput
  /**
   * Limit how many AttrTypes to update.
   */
  limit?: number
}

/**
 * AttrType updateManyAndReturn
 */
export type AttrTypeUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AttrType
   */
  select?: Prisma.AttrTypeSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the AttrType
   */
  omit?: Prisma.AttrTypeOmit<ExtArgs> | null
  /**
   * The data used to update AttrTypes.
   */
  data: Prisma.XOR<Prisma.AttrTypeUpdateManyMutationInput, Prisma.AttrTypeUncheckedUpdateManyInput>
  /**
   * Filter which AttrTypes to update
   */
  where?: Prisma.AttrTypeWhereInput
  /**
   * Limit how many AttrTypes to update.
   */
  limit?: number
}

/**
 * AttrType upsert
 */
export type AttrTypeUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AttrType
   */
  select?: Prisma.AttrTypeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AttrType
   */
  omit?: Prisma.AttrTypeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AttrTypeInclude<ExtArgs> | null
  /**
   * The filter to search for the AttrType to update in case it exists.
   */
  where: Prisma.AttrTypeWhereUniqueInput
  /**
   * In case the AttrType found by the `where` argument doesn't exist, create a new AttrType with this data.
   */
  create: Prisma.XOR<Prisma.AttrTypeCreateInput, Prisma.AttrTypeUncheckedCreateInput>
  /**
   * In case the AttrType was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.AttrTypeUpdateInput, Prisma.AttrTypeUncheckedUpdateInput>
}

/**
 * AttrType delete
 */
export type AttrTypeDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AttrType
   */
  select?: Prisma.AttrTypeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AttrType
   */
  omit?: Prisma.AttrTypeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AttrTypeInclude<ExtArgs> | null
  /**
   * Filter which AttrType to delete.
   */
  where: Prisma.AttrTypeWhereUniqueInput
}

/**
 * AttrType deleteMany
 */
export type AttrTypeDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which AttrTypes to delete
   */
  where?: Prisma.AttrTypeWhereInput
  /**
   * Limit how many AttrTypes to delete.
   */
  limit?: number
}

/**
 * AttrType.attributes
 */
export type AttrType$attributesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Attribute
   */
  select?: Prisma.AttributeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Attribute
   */
  omit?: Prisma.AttributeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AttributeInclude<ExtArgs> | null
  where?: Prisma.AttributeWhereInput
  orderBy?: Prisma.AttributeOrderByWithRelationInput | Prisma.AttributeOrderByWithRelationInput[]
  cursor?: Prisma.AttributeWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.AttributeScalarFieldEnum | Prisma.AttributeScalarFieldEnum[]
}

/**
 * AttrType without action
 */
export type AttrTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AttrType
   */
  select?: Prisma.AttrTypeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AttrType
   */
  omit?: Prisma.AttrTypeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AttrTypeInclude<ExtArgs> | null
}
