
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `KV` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model KV
 * 
 */
export type KVModel = runtime.Types.Result.DefaultSelection<Prisma.$KVPayload>

export type AggregateKV = {
  _count: KVCountAggregateOutputType | null
  _avg: KVAvgAggregateOutputType | null
  _sum: KVSumAggregateOutputType | null
  _min: KVMinAggregateOutputType | null
  _max: KVMaxAggregateOutputType | null
}

export type KVAvgAggregateOutputType = {
  id: number | null
  setId: number | null
  key: number | null
}

export type KVSumAggregateOutputType = {
  id: number | null
  setId: number | null
  key: number | null
}

export type KVMinAggregateOutputType = {
  id: number | null
  setId: number | null
  key: number | null
  value: string | null
}

export type KVMaxAggregateOutputType = {
  id: number | null
  setId: number | null
  key: number | null
  value: string | null
}

export type KVCountAggregateOutputType = {
  id: number
  setId: number
  key: number
  value: number
  _all: number
}


export type KVAvgAggregateInputType = {
  id?: true
  setId?: true
  key?: true
}

export type KVSumAggregateInputType = {
  id?: true
  setId?: true
  key?: true
}

export type KVMinAggregateInputType = {
  id?: true
  setId?: true
  key?: true
  value?: true
}

export type KVMaxAggregateInputType = {
  id?: true
  setId?: true
  key?: true
  value?: true
}

export type KVCountAggregateInputType = {
  id?: true
  setId?: true
  key?: true
  value?: true
  _all?: true
}

export type KVAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which KV to aggregate.
   */
  where?: Prisma.KVWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of KVS to fetch.
   */
  orderBy?: Prisma.KVOrderByWithRelationInput | Prisma.KVOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.KVWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` KVS from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` KVS.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned KVS
  **/
  _count?: true | KVCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: KVAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: KVSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: KVMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: KVMaxAggregateInputType
}

export type GetKVAggregateType<T extends KVAggregateArgs> = {
      [P in keyof T & keyof AggregateKV]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateKV[P]>
    : Prisma.GetScalarType<T[P], AggregateKV[P]>
}




export type KVGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.KVWhereInput
  orderBy?: Prisma.KVOrderByWithAggregationInput | Prisma.KVOrderByWithAggregationInput[]
  by: Prisma.KVScalarFieldEnum[] | Prisma.KVScalarFieldEnum
  having?: Prisma.KVScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: KVCountAggregateInputType | true
  _avg?: KVAvgAggregateInputType
  _sum?: KVSumAggregateInputType
  _min?: KVMinAggregateInputType
  _max?: KVMaxAggregateInputType
}

export type KVGroupByOutputType = {
  id: number
  setId: number
  key: number
  value: string
  _count: KVCountAggregateOutputType | null
  _avg: KVAvgAggregateOutputType | null
  _sum: KVSumAggregateOutputType | null
  _min: KVMinAggregateOutputType | null
  _max: KVMaxAggregateOutputType | null
}

type GetKVGroupByPayload<T extends KVGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<KVGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof KVGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], KVGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], KVGroupByOutputType[P]>
      }
    >
  >



export type KVWhereInput = {
  AND?: Prisma.KVWhereInput | Prisma.KVWhereInput[]
  OR?: Prisma.KVWhereInput[]
  NOT?: Prisma.KVWhereInput | Prisma.KVWhereInput[]
  id?: Prisma.IntFilter<"KV"> | number
  setId?: Prisma.IntFilter<"KV"> | number
  key?: Prisma.IntFilter<"KV"> | number
  value?: Prisma.StringFilter<"KV"> | string
  set?: Prisma.XOR<Prisma.KVSetScalarRelationFilter, Prisma.KVSetWhereInput>
}

export type KVOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  setId?: Prisma.SortOrder
  key?: Prisma.SortOrder
  value?: Prisma.SortOrder
  set?: Prisma.KVSetOrderByWithRelationInput
}

export type KVWhereUniqueInput = Prisma.AtLeast<{
  id?: number
  setId_key?: Prisma.KVSetIdKeyCompoundUniqueInput
  AND?: Prisma.KVWhereInput | Prisma.KVWhereInput[]
  OR?: Prisma.KVWhereInput[]
  NOT?: Prisma.KVWhereInput | Prisma.KVWhereInput[]
  setId?: Prisma.IntFilter<"KV"> | number
  key?: Prisma.IntFilter<"KV"> | number
  value?: Prisma.StringFilter<"KV"> | string
  set?: Prisma.XOR<Prisma.KVSetScalarRelationFilter, Prisma.KVSetWhereInput>
}, "id" | "setId_key">

export type KVOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  setId?: Prisma.SortOrder
  key?: Prisma.SortOrder
  value?: Prisma.SortOrder
  _count?: Prisma.KVCountOrderByAggregateInput
  _avg?: Prisma.KVAvgOrderByAggregateInput
  _max?: Prisma.KVMaxOrderByAggregateInput
  _min?: Prisma.KVMinOrderByAggregateInput
  _sum?: Prisma.KVSumOrderByAggregateInput
}

export type KVScalarWhereWithAggregatesInput = {
  AND?: Prisma.KVScalarWhereWithAggregatesInput | Prisma.KVScalarWhereWithAggregatesInput[]
  OR?: Prisma.KVScalarWhereWithAggregatesInput[]
  NOT?: Prisma.KVScalarWhereWithAggregatesInput | Prisma.KVScalarWhereWithAggregatesInput[]
  id?: Prisma.IntWithAggregatesFilter<"KV"> | number
  setId?: Prisma.IntWithAggregatesFilter<"KV"> | number
  key?: Prisma.IntWithAggregatesFilter<"KV"> | number
  value?: Prisma.StringWithAggregatesFilter<"KV"> | string
}

export type KVCreateInput = {
  key: number
  value: string
  set: Prisma.KVSetCreateNestedOneWithoutValuesInput
}

export type KVUncheckedCreateInput = {
  id?: number
  setId: number
  key: number
  value: string
}

export type KVUpdateInput = {
  key?: Prisma.IntFieldUpdateOperationsInput | number
  value?: Prisma.StringFieldUpdateOperationsInput | string
  set?: Prisma.KVSetUpdateOneRequiredWithoutValuesNestedInput
}

export type KVUncheckedUpdateInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  setId?: Prisma.IntFieldUpdateOperationsInput | number
  key?: Prisma.IntFieldUpdateOperationsInput | number
  value?: Prisma.StringFieldUpdateOperationsInput | string
}

export type KVCreateManyInput = {
  id?: number
  setId: number
  key: number
  value: string
}

export type KVUpdateManyMutationInput = {
  key?: Prisma.IntFieldUpdateOperationsInput | number
  value?: Prisma.StringFieldUpdateOperationsInput | string
}

export type KVUncheckedUpdateManyInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  setId?: Prisma.IntFieldUpdateOperationsInput | number
  key?: Prisma.IntFieldUpdateOperationsInput | number
  value?: Prisma.StringFieldUpdateOperationsInput | string
}

export type KVListRelationFilter = {
  every?: Prisma.KVWhereInput
  some?: Prisma.KVWhereInput
  none?: Prisma.KVWhereInput
}

export type KVOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type KVSetIdKeyCompoundUniqueInput = {
  setId: number
  key: number
}

export type KVCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  setId?: Prisma.SortOrder
  key?: Prisma.SortOrder
  value?: Prisma.SortOrder
}

export type KVAvgOrderByAggregateInput = {
  id?: Prisma.SortOrder
  setId?: Prisma.SortOrder
  key?: Prisma.SortOrder
}

export type KVMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  setId?: Prisma.SortOrder
  key?: Prisma.SortOrder
  value?: Prisma.SortOrder
}

export type KVMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  setId?: Prisma.SortOrder
  key?: Prisma.SortOrder
  value?: Prisma.SortOrder
}

export type KVSumOrderByAggregateInput = {
  id?: Prisma.SortOrder
  setId?: Prisma.SortOrder
  key?: Prisma.SortOrder
}

export type KVCreateNestedManyWithoutSetInput = {
  create?: Prisma.XOR<Prisma.KVCreateWithoutSetInput, Prisma.KVUncheckedCreateWithoutSetInput> | Prisma.KVCreateWithoutSetInput[] | Prisma.KVUncheckedCreateWithoutSetInput[]
  connectOrCreate?: Prisma.KVCreateOrConnectWithoutSetInput | Prisma.KVCreateOrConnectWithoutSetInput[]
  createMany?: Prisma.KVCreateManySetInputEnvelope
  connect?: Prisma.KVWhereUniqueInput | Prisma.KVWhereUniqueInput[]
}

export type KVUncheckedCreateNestedManyWithoutSetInput = {
  create?: Prisma.XOR<Prisma.KVCreateWithoutSetInput, Prisma.KVUncheckedCreateWithoutSetInput> | Prisma.KVCreateWithoutSetInput[] | Prisma.KVUncheckedCreateWithoutSetInput[]
  connectOrCreate?: Prisma.KVCreateOrConnectWithoutSetInput | Prisma.KVCreateOrConnectWithoutSetInput[]
  createMany?: Prisma.KVCreateManySetInputEnvelope
  connect?: Prisma.KVWhereUniqueInput | Prisma.KVWhereUniqueInput[]
}

export type KVUpdateManyWithoutSetNestedInput = {
  create?: Prisma.XOR<Prisma.KVCreateWithoutSetInput, Prisma.KVUncheckedCreateWithoutSetInput> | Prisma.KVCreateWithoutSetInput[] | Prisma.KVUncheckedCreateWithoutSetInput[]
  connectOrCreate?: Prisma.KVCreateOrConnectWithoutSetInput | Prisma.KVCreateOrConnectWithoutSetInput[]
  upsert?: Prisma.KVUpsertWithWhereUniqueWithoutSetInput | Prisma.KVUpsertWithWhereUniqueWithoutSetInput[]
  createMany?: Prisma.KVCreateManySetInputEnvelope
  set?: Prisma.KVWhereUniqueInput | Prisma.KVWhereUniqueInput[]
  disconnect?: Prisma.KVWhereUniqueInput | Prisma.KVWhereUniqueInput[]
  delete?: Prisma.KVWhereUniqueInput | Prisma.KVWhereUniqueInput[]
  connect?: Prisma.KVWhereUniqueInput | Prisma.KVWhereUniqueInput[]
  update?: Prisma.KVUpdateWithWhereUniqueWithoutSetInput | Prisma.KVUpdateWithWhereUniqueWithoutSetInput[]
  updateMany?: Prisma.KVUpdateManyWithWhereWithoutSetInput | Prisma.KVUpdateManyWithWhereWithoutSetInput[]
  deleteMany?: Prisma.KVScalarWhereInput | Prisma.KVScalarWhereInput[]
}

export type KVUncheckedUpdateManyWithoutSetNestedInput = {
  create?: Prisma.XOR<Prisma.KVCreateWithoutSetInput, Prisma.KVUncheckedCreateWithoutSetInput> | Prisma.KVCreateWithoutSetInput[] | Prisma.KVUncheckedCreateWithoutSetInput[]
  connectOrCreate?: Prisma.KVCreateOrConnectWithoutSetInput | Prisma.KVCreateOrConnectWithoutSetInput[]
  upsert?: Prisma.KVUpsertWithWhereUniqueWithoutSetInput | Prisma.KVUpsertWithWhereUniqueWithoutSetInput[]
  createMany?: Prisma.KVCreateManySetInputEnvelope
  set?: Prisma.KVWhereUniqueInput | Prisma.KVWhereUniqueInput[]
  disconnect?: Prisma.KVWhereUniqueInput | Prisma.KVWhereUniqueInput[]
  delete?: Prisma.KVWhereUniqueInput | Prisma.KVWhereUniqueInput[]
  connect?: Prisma.KVWhereUniqueInput | Prisma.KVWhereUniqueInput[]
  update?: Prisma.KVUpdateWithWhereUniqueWithoutSetInput | Prisma.KVUpdateWithWhereUniqueWithoutSetInput[]
  updateMany?: Prisma.KVUpdateManyWithWhereWithoutSetInput | Prisma.KVUpdateManyWithWhereWithoutSetInput[]
  deleteMany?: Prisma.KVScalarWhereInput | Prisma.KVScalarWhereInput[]
}

export type KVCreateWithoutSetInput = {
  key: number
  value: string
}

export type KVUncheckedCreateWithoutSetInput = {
  id?: number
  key: number
  value: string
}

export type KVCreateOrConnectWithoutSetInput = {
  where: Prisma.KVWhereUniqueInput
  create: Prisma.XOR<Prisma.KVCreateWithoutSetInput, Prisma.KVUncheckedCreateWithoutSetInput>
}

export type KVCreateManySetInputEnvelope = {
  data: Prisma.KVCreateManySetInput | Prisma.KVCreateManySetInput[]
  skipDuplicates?: boolean
}

export type KVUpsertWithWhereUniqueWithoutSetInput = {
  where: Prisma.KVWhereUniqueInput
  update: Prisma.XOR<Prisma.KVUpdateWithoutSetInput, Prisma.KVUncheckedUpdateWithoutSetInput>
  create: Prisma.XOR<Prisma.KVCreateWithoutSetInput, Prisma.KVUncheckedCreateWithoutSetInput>
}

export type KVUpdateWithWhereUniqueWithoutSetInput = {
  where: Prisma.KVWhereUniqueInput
  data: Prisma.XOR<Prisma.KVUpdateWithoutSetInput, Prisma.KVUncheckedUpdateWithoutSetInput>
}

export type KVUpdateManyWithWhereWithoutSetInput = {
  where: Prisma.KVScalarWhereInput
  data: Prisma.XOR<Prisma.KVUpdateManyMutationInput, Prisma.KVUncheckedUpdateManyWithoutSetInput>
}

export type KVScalarWhereInput = {
  AND?: Prisma.KVScalarWhereInput | Prisma.KVScalarWhereInput[]
  OR?: Prisma.KVScalarWhereInput[]
  NOT?: Prisma.KVScalarWhereInput | Prisma.KVScalarWhereInput[]
  id?: Prisma.IntFilter<"KV"> | number
  setId?: Prisma.IntFilter<"KV"> | number
  key?: Prisma.IntFilter<"KV"> | number
  value?: Prisma.StringFilter<"KV"> | string
}

export type KVCreateManySetInput = {
  id?: number
  key: number
  value: string
}

export type KVUpdateWithoutSetInput = {
  key?: Prisma.IntFieldUpdateOperationsInput | number
  value?: Prisma.StringFieldUpdateOperationsInput | string
}

export type KVUncheckedUpdateWithoutSetInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  key?: Prisma.IntFieldUpdateOperationsInput | number
  value?: Prisma.StringFieldUpdateOperationsInput | string
}

export type KVUncheckedUpdateManyWithoutSetInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  key?: Prisma.IntFieldUpdateOperationsInput | number
  value?: Prisma.StringFieldUpdateOperationsInput | string
}



export type KVSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  setId?: boolean
  key?: boolean
  value?: boolean
  set?: boolean | Prisma.KVSetDefaultArgs<ExtArgs>
}, ExtArgs["result"]["kV"]>

export type KVSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  setId?: boolean
  key?: boolean
  value?: boolean
  set?: boolean | Prisma.KVSetDefaultArgs<ExtArgs>
}, ExtArgs["result"]["kV"]>

export type KVSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  setId?: boolean
  key?: boolean
  value?: boolean
  set?: boolean | Prisma.KVSetDefaultArgs<ExtArgs>
}, ExtArgs["result"]["kV"]>

export type KVSelectScalar = {
  id?: boolean
  setId?: boolean
  key?: boolean
  value?: boolean
}

export type KVOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "setId" | "key" | "value", ExtArgs["result"]["kV"]>
export type KVInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  set?: boolean | Prisma.KVSetDefaultArgs<ExtArgs>
}
export type KVIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  set?: boolean | Prisma.KVSetDefaultArgs<ExtArgs>
}
export type KVIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  set?: boolean | Prisma.KVSetDefaultArgs<ExtArgs>
}

export type $KVPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "KV"
  objects: {
    set: Prisma.$KVSetPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: number
    setId: number
    key: number
    value: string
  }, ExtArgs["result"]["kV"]>
  composites: {}
}

export type KVGetPayload<S extends boolean | null | undefined | KVDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$KVPayload, S>

export type KVCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<KVFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: KVCountAggregateInputType | true
  }

export interface KVDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['KV'], meta: { name: 'KV' } }
  /**
   * Find zero or one KV that matches the filter.
   * @param {KVFindUniqueArgs} args - Arguments to find a KV
   * @example
   * // Get one KV
   * const kV = await prisma.kV.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends KVFindUniqueArgs>(args: Prisma.SelectSubset<T, KVFindUniqueArgs<ExtArgs>>): Prisma.Prisma__KVClient<runtime.Types.Result.GetResult<Prisma.$KVPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one KV that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {KVFindUniqueOrThrowArgs} args - Arguments to find a KV
   * @example
   * // Get one KV
   * const kV = await prisma.kV.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends KVFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, KVFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__KVClient<runtime.Types.Result.GetResult<Prisma.$KVPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first KV that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {KVFindFirstArgs} args - Arguments to find a KV
   * @example
   * // Get one KV
   * const kV = await prisma.kV.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends KVFindFirstArgs>(args?: Prisma.SelectSubset<T, KVFindFirstArgs<ExtArgs>>): Prisma.Prisma__KVClient<runtime.Types.Result.GetResult<Prisma.$KVPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first KV that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {KVFindFirstOrThrowArgs} args - Arguments to find a KV
   * @example
   * // Get one KV
   * const kV = await prisma.kV.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends KVFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, KVFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__KVClient<runtime.Types.Result.GetResult<Prisma.$KVPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more KVS that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {KVFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all KVS
   * const kVS = await prisma.kV.findMany()
   * 
   * // Get first 10 KVS
   * const kVS = await prisma.kV.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const kVWithIdOnly = await prisma.kV.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends KVFindManyArgs>(args?: Prisma.SelectSubset<T, KVFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$KVPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a KV.
   * @param {KVCreateArgs} args - Arguments to create a KV.
   * @example
   * // Create one KV
   * const KV = await prisma.kV.create({
   *   data: {
   *     // ... data to create a KV
   *   }
   * })
   * 
   */
  create<T extends KVCreateArgs>(args: Prisma.SelectSubset<T, KVCreateArgs<ExtArgs>>): Prisma.Prisma__KVClient<runtime.Types.Result.GetResult<Prisma.$KVPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many KVS.
   * @param {KVCreateManyArgs} args - Arguments to create many KVS.
   * @example
   * // Create many KVS
   * const kV = await prisma.kV.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends KVCreateManyArgs>(args?: Prisma.SelectSubset<T, KVCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many KVS and returns the data saved in the database.
   * @param {KVCreateManyAndReturnArgs} args - Arguments to create many KVS.
   * @example
   * // Create many KVS
   * const kV = await prisma.kV.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many KVS and only return the `id`
   * const kVWithIdOnly = await prisma.kV.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends KVCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, KVCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$KVPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a KV.
   * @param {KVDeleteArgs} args - Arguments to delete one KV.
   * @example
   * // Delete one KV
   * const KV = await prisma.kV.delete({
   *   where: {
   *     // ... filter to delete one KV
   *   }
   * })
   * 
   */
  delete<T extends KVDeleteArgs>(args: Prisma.SelectSubset<T, KVDeleteArgs<ExtArgs>>): Prisma.Prisma__KVClient<runtime.Types.Result.GetResult<Prisma.$KVPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one KV.
   * @param {KVUpdateArgs} args - Arguments to update one KV.
   * @example
   * // Update one KV
   * const kV = await prisma.kV.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends KVUpdateArgs>(args: Prisma.SelectSubset<T, KVUpdateArgs<ExtArgs>>): Prisma.Prisma__KVClient<runtime.Types.Result.GetResult<Prisma.$KVPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more KVS.
   * @param {KVDeleteManyArgs} args - Arguments to filter KVS to delete.
   * @example
   * // Delete a few KVS
   * const { count } = await prisma.kV.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends KVDeleteManyArgs>(args?: Prisma.SelectSubset<T, KVDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more KVS.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {KVUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many KVS
   * const kV = await prisma.kV.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends KVUpdateManyArgs>(args: Prisma.SelectSubset<T, KVUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more KVS and returns the data updated in the database.
   * @param {KVUpdateManyAndReturnArgs} args - Arguments to update many KVS.
   * @example
   * // Update many KVS
   * const kV = await prisma.kV.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more KVS and only return the `id`
   * const kVWithIdOnly = await prisma.kV.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends KVUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, KVUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$KVPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one KV.
   * @param {KVUpsertArgs} args - Arguments to update or create a KV.
   * @example
   * // Update or create a KV
   * const kV = await prisma.kV.upsert({
   *   create: {
   *     // ... data to create a KV
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the KV we want to update
   *   }
   * })
   */
  upsert<T extends KVUpsertArgs>(args: Prisma.SelectSubset<T, KVUpsertArgs<ExtArgs>>): Prisma.Prisma__KVClient<runtime.Types.Result.GetResult<Prisma.$KVPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of KVS.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {KVCountArgs} args - Arguments to filter KVS to count.
   * @example
   * // Count the number of KVS
   * const count = await prisma.kV.count({
   *   where: {
   *     // ... the filter for the KVS we want to count
   *   }
   * })
  **/
  count<T extends KVCountArgs>(
    args?: Prisma.Subset<T, KVCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], KVCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a KV.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {KVAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends KVAggregateArgs>(args: Prisma.Subset<T, KVAggregateArgs>): Prisma.PrismaPromise<GetKVAggregateType<T>>

  /**
   * Group by KV.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {KVGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends KVGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: KVGroupByArgs['orderBy'] }
      : { orderBy?: KVGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, KVGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetKVGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the KV model
 */
readonly fields: KVFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for KV.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__KVClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  set<T extends Prisma.KVSetDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.KVSetDefaultArgs<ExtArgs>>): Prisma.Prisma__KVSetClient<runtime.Types.Result.GetResult<Prisma.$KVSetPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the KV model
 */
export interface KVFieldRefs {
  readonly id: Prisma.FieldRef<"KV", 'Int'>
  readonly setId: Prisma.FieldRef<"KV", 'Int'>
  readonly key: Prisma.FieldRef<"KV", 'Int'>
  readonly value: Prisma.FieldRef<"KV", 'String'>
}
    

// Custom InputTypes
/**
 * KV findUnique
 */
export type KVFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the KV
   */
  select?: Prisma.KVSelect<ExtArgs> | null
  /**
   * Omit specific fields from the KV
   */
  omit?: Prisma.KVOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.KVInclude<ExtArgs> | null
  /**
   * Filter, which KV to fetch.
   */
  where: Prisma.KVWhereUniqueInput
}

/**
 * KV findUniqueOrThrow
 */
export type KVFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the KV
   */
  select?: Prisma.KVSelect<ExtArgs> | null
  /**
   * Omit specific fields from the KV
   */
  omit?: Prisma.KVOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.KVInclude<ExtArgs> | null
  /**
   * Filter, which KV to fetch.
   */
  where: Prisma.KVWhereUniqueInput
}

/**
 * KV findFirst
 */
export type KVFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the KV
   */
  select?: Prisma.KVSelect<ExtArgs> | null
  /**
   * Omit specific fields from the KV
   */
  omit?: Prisma.KVOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.KVInclude<ExtArgs> | null
  /**
   * Filter, which KV to fetch.
   */
  where?: Prisma.KVWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of KVS to fetch.
   */
  orderBy?: Prisma.KVOrderByWithRelationInput | Prisma.KVOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for KVS.
   */
  cursor?: Prisma.KVWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` KVS from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` KVS.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of KVS.
   */
  distinct?: Prisma.KVScalarFieldEnum | Prisma.KVScalarFieldEnum[]
}

/**
 * KV findFirstOrThrow
 */
export type KVFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the KV
   */
  select?: Prisma.KVSelect<ExtArgs> | null
  /**
   * Omit specific fields from the KV
   */
  omit?: Prisma.KVOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.KVInclude<ExtArgs> | null
  /**
   * Filter, which KV to fetch.
   */
  where?: Prisma.KVWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of KVS to fetch.
   */
  orderBy?: Prisma.KVOrderByWithRelationInput | Prisma.KVOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for KVS.
   */
  cursor?: Prisma.KVWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` KVS from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` KVS.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of KVS.
   */
  distinct?: Prisma.KVScalarFieldEnum | Prisma.KVScalarFieldEnum[]
}

/**
 * KV findMany
 */
export type KVFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the KV
   */
  select?: Prisma.KVSelect<ExtArgs> | null
  /**
   * Omit specific fields from the KV
   */
  omit?: Prisma.KVOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.KVInclude<ExtArgs> | null
  /**
   * Filter, which KVS to fetch.
   */
  where?: Prisma.KVWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of KVS to fetch.
   */
  orderBy?: Prisma.KVOrderByWithRelationInput | Prisma.KVOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing KVS.
   */
  cursor?: Prisma.KVWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` KVS from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` KVS.
   */
  skip?: number
  distinct?: Prisma.KVScalarFieldEnum | Prisma.KVScalarFieldEnum[]
}

/**
 * KV create
 */
export type KVCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the KV
   */
  select?: Prisma.KVSelect<ExtArgs> | null
  /**
   * Omit specific fields from the KV
   */
  omit?: Prisma.KVOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.KVInclude<ExtArgs> | null
  /**
   * The data needed to create a KV.
   */
  data: Prisma.XOR<Prisma.KVCreateInput, Prisma.KVUncheckedCreateInput>
}

/**
 * KV createMany
 */
export type KVCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many KVS.
   */
  data: Prisma.KVCreateManyInput | Prisma.KVCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * KV createManyAndReturn
 */
export type KVCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the KV
   */
  select?: Prisma.KVSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the KV
   */
  omit?: Prisma.KVOmit<ExtArgs> | null
  /**
   * The data used to create many KVS.
   */
  data: Prisma.KVCreateManyInput | Prisma.KVCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.KVIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * KV update
 */
export type KVUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the KV
   */
  select?: Prisma.KVSelect<ExtArgs> | null
  /**
   * Omit specific fields from the KV
   */
  omit?: Prisma.KVOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.KVInclude<ExtArgs> | null
  /**
   * The data needed to update a KV.
   */
  data: Prisma.XOR<Prisma.KVUpdateInput, Prisma.KVUncheckedUpdateInput>
  /**
   * Choose, which KV to update.
   */
  where: Prisma.KVWhereUniqueInput
}

/**
 * KV updateMany
 */
export type KVUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update KVS.
   */
  data: Prisma.XOR<Prisma.KVUpdateManyMutationInput, Prisma.KVUncheckedUpdateManyInput>
  /**
   * Filter which KVS to update
   */
  where?: Prisma.KVWhereInput
  /**
   * Limit how many KVS to update.
   */
  limit?: number
}

/**
 * KV updateManyAndReturn
 */
export type KVUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the KV
   */
  select?: Prisma.KVSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the KV
   */
  omit?: Prisma.KVOmit<ExtArgs> | null
  /**
   * The data used to update KVS.
   */
  data: Prisma.XOR<Prisma.KVUpdateManyMutationInput, Prisma.KVUncheckedUpdateManyInput>
  /**
   * Filter which KVS to update
   */
  where?: Prisma.KVWhereInput
  /**
   * Limit how many KVS to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.KVIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * KV upsert
 */
export type KVUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the KV
   */
  select?: Prisma.KVSelect<ExtArgs> | null
  /**
   * Omit specific fields from the KV
   */
  omit?: Prisma.KVOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.KVInclude<ExtArgs> | null
  /**
   * The filter to search for the KV to update in case it exists.
   */
  where: Prisma.KVWhereUniqueInput
  /**
   * In case the KV found by the `where` argument doesn't exist, create a new KV with this data.
   */
  create: Prisma.XOR<Prisma.KVCreateInput, Prisma.KVUncheckedCreateInput>
  /**
   * In case the KV was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.KVUpdateInput, Prisma.KVUncheckedUpdateInput>
}

/**
 * KV delete
 */
export type KVDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the KV
   */
  select?: Prisma.KVSelect<ExtArgs> | null
  /**
   * Omit specific fields from the KV
   */
  omit?: Prisma.KVOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.KVInclude<ExtArgs> | null
  /**
   * Filter which KV to delete.
   */
  where: Prisma.KVWhereUniqueInput
}

/**
 * KV deleteMany
 */
export type KVDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which KVS to delete
   */
  where?: Prisma.KVWhereInput
  /**
   * Limit how many KVS to delete.
   */
  limit?: number
}

/**
 * KV without action
 */
export type KVDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the KV
   */
  select?: Prisma.KVSelect<ExtArgs> | null
  /**
   * Omit specific fields from the KV
   */
  omit?: Prisma.KVOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.KVInclude<ExtArgs> | null
}
