
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `KVSet` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model KVSet
 * 
 */
export type KVSetModel = runtime.Types.Result.DefaultSelection<Prisma.$KVSetPayload>

export type AggregateKVSet = {
  _count: KVSetCountAggregateOutputType | null
  _avg: KVSetAvgAggregateOutputType | null
  _sum: KVSetSumAggregateOutputType | null
  _min: KVSetMinAggregateOutputType | null
  _max: KVSetMaxAggregateOutputType | null
}

export type KVSetAvgAggregateOutputType = {
  id: number | null
}

export type KVSetSumAggregateOutputType = {
  id: number | null
}

export type KVSetMinAggregateOutputType = {
  id: number | null
  name: string | null
}

export type KVSetMaxAggregateOutputType = {
  id: number | null
  name: string | null
}

export type KVSetCountAggregateOutputType = {
  id: number
  name: number
  _all: number
}


export type KVSetAvgAggregateInputType = {
  id?: true
}

export type KVSetSumAggregateInputType = {
  id?: true
}

export type KVSetMinAggregateInputType = {
  id?: true
  name?: true
}

export type KVSetMaxAggregateInputType = {
  id?: true
  name?: true
}

export type KVSetCountAggregateInputType = {
  id?: true
  name?: true
  _all?: true
}

export type KVSetAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which KVSet to aggregate.
   */
  where?: Prisma.KVSetWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of KVSets to fetch.
   */
  orderBy?: Prisma.KVSetOrderByWithRelationInput | Prisma.KVSetOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.KVSetWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` KVSets from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` KVSets.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned KVSets
  **/
  _count?: true | KVSetCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: KVSetAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: KVSetSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: KVSetMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: KVSetMaxAggregateInputType
}

export type GetKVSetAggregateType<T extends KVSetAggregateArgs> = {
      [P in keyof T & keyof AggregateKVSet]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateKVSet[P]>
    : Prisma.GetScalarType<T[P], AggregateKVSet[P]>
}




export type KVSetGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.KVSetWhereInput
  orderBy?: Prisma.KVSetOrderByWithAggregationInput | Prisma.KVSetOrderByWithAggregationInput[]
  by: Prisma.KVSetScalarFieldEnum[] | Prisma.KVSetScalarFieldEnum
  having?: Prisma.KVSetScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: KVSetCountAggregateInputType | true
  _avg?: KVSetAvgAggregateInputType
  _sum?: KVSetSumAggregateInputType
  _min?: KVSetMinAggregateInputType
  _max?: KVSetMaxAggregateInputType
}

export type KVSetGroupByOutputType = {
  id: number
  name: string
  _count: KVSetCountAggregateOutputType | null
  _avg: KVSetAvgAggregateOutputType | null
  _sum: KVSetSumAggregateOutputType | null
  _min: KVSetMinAggregateOutputType | null
  _max: KVSetMaxAggregateOutputType | null
}

type GetKVSetGroupByPayload<T extends KVSetGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<KVSetGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof KVSetGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], KVSetGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], KVSetGroupByOutputType[P]>
      }
    >
  >



export type KVSetWhereInput = {
  AND?: Prisma.KVSetWhereInput | Prisma.KVSetWhereInput[]
  OR?: Prisma.KVSetWhereInput[]
  NOT?: Prisma.KVSetWhereInput | Prisma.KVSetWhereInput[]
  id?: Prisma.IntFilter<"KVSet"> | number
  name?: Prisma.StringFilter<"KVSet"> | string
  values?: Prisma.KVListRelationFilter
  attributes?: Prisma.AttributeListRelationFilter
}

export type KVSetOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  values?: Prisma.KVOrderByRelationAggregateInput
  attributes?: Prisma.AttributeOrderByRelationAggregateInput
}

export type KVSetWhereUniqueInput = Prisma.AtLeast<{
  id?: number
  AND?: Prisma.KVSetWhereInput | Prisma.KVSetWhereInput[]
  OR?: Prisma.KVSetWhereInput[]
  NOT?: Prisma.KVSetWhereInput | Prisma.KVSetWhereInput[]
  name?: Prisma.StringFilter<"KVSet"> | string
  values?: Prisma.KVListRelationFilter
  attributes?: Prisma.AttributeListRelationFilter
}, "id">

export type KVSetOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  _count?: Prisma.KVSetCountOrderByAggregateInput
  _avg?: Prisma.KVSetAvgOrderByAggregateInput
  _max?: Prisma.KVSetMaxOrderByAggregateInput
  _min?: Prisma.KVSetMinOrderByAggregateInput
  _sum?: Prisma.KVSetSumOrderByAggregateInput
}

export type KVSetScalarWhereWithAggregatesInput = {
  AND?: Prisma.KVSetScalarWhereWithAggregatesInput | Prisma.KVSetScalarWhereWithAggregatesInput[]
  OR?: Prisma.KVSetScalarWhereWithAggregatesInput[]
  NOT?: Prisma.KVSetScalarWhereWithAggregatesInput | Prisma.KVSetScalarWhereWithAggregatesInput[]
  id?: Prisma.IntWithAggregatesFilter<"KVSet"> | number
  name?: Prisma.StringWithAggregatesFilter<"KVSet"> | string
}

export type KVSetCreateInput = {
  name: string
  values?: Prisma.KVCreateNestedManyWithoutSetInput
  attributes?: Prisma.AttributeCreateNestedManyWithoutKVSetInput
}

export type KVSetUncheckedCreateInput = {
  id?: number
  name: string
  values?: Prisma.KVUncheckedCreateNestedManyWithoutSetInput
  attributes?: Prisma.AttributeUncheckedCreateNestedManyWithoutKVSetInput
}

export type KVSetUpdateInput = {
  name?: Prisma.StringFieldUpdateOperationsInput | string
  values?: Prisma.KVUpdateManyWithoutSetNestedInput
  attributes?: Prisma.AttributeUpdateManyWithoutKVSetNestedInput
}

export type KVSetUncheckedUpdateInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  name?: Prisma.StringFieldUpdateOperationsInput | string
  values?: Prisma.KVUncheckedUpdateManyWithoutSetNestedInput
  attributes?: Prisma.AttributeUncheckedUpdateManyWithoutKVSetNestedInput
}

export type KVSetCreateManyInput = {
  id?: number
  name: string
}

export type KVSetUpdateManyMutationInput = {
  name?: Prisma.StringFieldUpdateOperationsInput | string
}

export type KVSetUncheckedUpdateManyInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  name?: Prisma.StringFieldUpdateOperationsInput | string
}

export type KVSetNullableScalarRelationFilter = {
  is?: Prisma.KVSetWhereInput | null
  isNot?: Prisma.KVSetWhereInput | null
}

export type KVSetCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
}

export type KVSetAvgOrderByAggregateInput = {
  id?: Prisma.SortOrder
}

export type KVSetMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
}

export type KVSetMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
}

export type KVSetSumOrderByAggregateInput = {
  id?: Prisma.SortOrder
}

export type KVSetScalarRelationFilter = {
  is?: Prisma.KVSetWhereInput
  isNot?: Prisma.KVSetWhereInput
}

export type KVSetCreateNestedOneWithoutAttributesInput = {
  create?: Prisma.XOR<Prisma.KVSetCreateWithoutAttributesInput, Prisma.KVSetUncheckedCreateWithoutAttributesInput>
  connectOrCreate?: Prisma.KVSetCreateOrConnectWithoutAttributesInput
  connect?: Prisma.KVSetWhereUniqueInput
}

export type KVSetUpdateOneWithoutAttributesNestedInput = {
  create?: Prisma.XOR<Prisma.KVSetCreateWithoutAttributesInput, Prisma.KVSetUncheckedCreateWithoutAttributesInput>
  connectOrCreate?: Prisma.KVSetCreateOrConnectWithoutAttributesInput
  upsert?: Prisma.KVSetUpsertWithoutAttributesInput
  disconnect?: Prisma.KVSetWhereInput | boolean
  delete?: Prisma.KVSetWhereInput | boolean
  connect?: Prisma.KVSetWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.KVSetUpdateToOneWithWhereWithoutAttributesInput, Prisma.KVSetUpdateWithoutAttributesInput>, Prisma.KVSetUncheckedUpdateWithoutAttributesInput>
}

export type KVSetCreateNestedOneWithoutValuesInput = {
  create?: Prisma.XOR<Prisma.KVSetCreateWithoutValuesInput, Prisma.KVSetUncheckedCreateWithoutValuesInput>
  connectOrCreate?: Prisma.KVSetCreateOrConnectWithoutValuesInput
  connect?: Prisma.KVSetWhereUniqueInput
}

export type KVSetUpdateOneRequiredWithoutValuesNestedInput = {
  create?: Prisma.XOR<Prisma.KVSetCreateWithoutValuesInput, Prisma.KVSetUncheckedCreateWithoutValuesInput>
  connectOrCreate?: Prisma.KVSetCreateOrConnectWithoutValuesInput
  upsert?: Prisma.KVSetUpsertWithoutValuesInput
  connect?: Prisma.KVSetWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.KVSetUpdateToOneWithWhereWithoutValuesInput, Prisma.KVSetUpdateWithoutValuesInput>, Prisma.KVSetUncheckedUpdateWithoutValuesInput>
}

export type KVSetCreateWithoutAttributesInput = {
  name: string
  values?: Prisma.KVCreateNestedManyWithoutSetInput
}

export type KVSetUncheckedCreateWithoutAttributesInput = {
  id?: number
  name: string
  values?: Prisma.KVUncheckedCreateNestedManyWithoutSetInput
}

export type KVSetCreateOrConnectWithoutAttributesInput = {
  where: Prisma.KVSetWhereUniqueInput
  create: Prisma.XOR<Prisma.KVSetCreateWithoutAttributesInput, Prisma.KVSetUncheckedCreateWithoutAttributesInput>
}

export type KVSetUpsertWithoutAttributesInput = {
  update: Prisma.XOR<Prisma.KVSetUpdateWithoutAttributesInput, Prisma.KVSetUncheckedUpdateWithoutAttributesInput>
  create: Prisma.XOR<Prisma.KVSetCreateWithoutAttributesInput, Prisma.KVSetUncheckedCreateWithoutAttributesInput>
  where?: Prisma.KVSetWhereInput
}

export type KVSetUpdateToOneWithWhereWithoutAttributesInput = {
  where?: Prisma.KVSetWhereInput
  data: Prisma.XOR<Prisma.KVSetUpdateWithoutAttributesInput, Prisma.KVSetUncheckedUpdateWithoutAttributesInput>
}

export type KVSetUpdateWithoutAttributesInput = {
  name?: Prisma.StringFieldUpdateOperationsInput | string
  values?: Prisma.KVUpdateManyWithoutSetNestedInput
}

export type KVSetUncheckedUpdateWithoutAttributesInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  name?: Prisma.StringFieldUpdateOperationsInput | string
  values?: Prisma.KVUncheckedUpdateManyWithoutSetNestedInput
}

export type KVSetCreateWithoutValuesInput = {
  name: string
  attributes?: Prisma.AttributeCreateNestedManyWithoutKVSetInput
}

export type KVSetUncheckedCreateWithoutValuesInput = {
  id?: number
  name: string
  attributes?: Prisma.AttributeUncheckedCreateNestedManyWithoutKVSetInput
}

export type KVSetCreateOrConnectWithoutValuesInput = {
  where: Prisma.KVSetWhereUniqueInput
  create: Prisma.XOR<Prisma.KVSetCreateWithoutValuesInput, Prisma.KVSetUncheckedCreateWithoutValuesInput>
}

export type KVSetUpsertWithoutValuesInput = {
  update: Prisma.XOR<Prisma.KVSetUpdateWithoutValuesInput, Prisma.KVSetUncheckedUpdateWithoutValuesInput>
  create: Prisma.XOR<Prisma.KVSetCreateWithoutValuesInput, Prisma.KVSetUncheckedCreateWithoutValuesInput>
  where?: Prisma.KVSetWhereInput
}

export type KVSetUpdateToOneWithWhereWithoutValuesInput = {
  where?: Prisma.KVSetWhereInput
  data: Prisma.XOR<Prisma.KVSetUpdateWithoutValuesInput, Prisma.KVSetUncheckedUpdateWithoutValuesInput>
}

export type KVSetUpdateWithoutValuesInput = {
  name?: Prisma.StringFieldUpdateOperationsInput | string
  attributes?: Prisma.AttributeUpdateManyWithoutKVSetNestedInput
}

export type KVSetUncheckedUpdateWithoutValuesInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  name?: Prisma.StringFieldUpdateOperationsInput | string
  attributes?: Prisma.AttributeUncheckedUpdateManyWithoutKVSetNestedInput
}


/**
 * Count Type KVSetCountOutputType
 */

export type KVSetCountOutputType = {
  values: number
  attributes: number
}

export type KVSetCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  values?: boolean | KVSetCountOutputTypeCountValuesArgs
  attributes?: boolean | KVSetCountOutputTypeCountAttributesArgs
}

/**
 * KVSetCountOutputType without action
 */
export type KVSetCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the KVSetCountOutputType
   */
  select?: Prisma.KVSetCountOutputTypeSelect<ExtArgs> | null
}

/**
 * KVSetCountOutputType without action
 */
export type KVSetCountOutputTypeCountValuesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.KVWhereInput
}

/**
 * KVSetCountOutputType without action
 */
export type KVSetCountOutputTypeCountAttributesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.AttributeWhereInput
}


export type KVSetSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  values?: boolean | Prisma.KVSet$valuesArgs<ExtArgs>
  attributes?: boolean | Prisma.KVSet$attributesArgs<ExtArgs>
  _count?: boolean | Prisma.KVSetCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["kVSet"]>

export type KVSetSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
}, ExtArgs["result"]["kVSet"]>

export type KVSetSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
}, ExtArgs["result"]["kVSet"]>

export type KVSetSelectScalar = {
  id?: boolean
  name?: boolean
}

export type KVSetOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "name", ExtArgs["result"]["kVSet"]>
export type KVSetInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  values?: boolean | Prisma.KVSet$valuesArgs<ExtArgs>
  attributes?: boolean | Prisma.KVSet$attributesArgs<ExtArgs>
  _count?: boolean | Prisma.KVSetCountOutputTypeDefaultArgs<ExtArgs>
}
export type KVSetIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}
export type KVSetIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}

export type $KVSetPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "KVSet"
  objects: {
    values: Prisma.$KVPayload<ExtArgs>[]
    attributes: Prisma.$AttributePayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: number
    name: string
  }, ExtArgs["result"]["kVSet"]>
  composites: {}
}

export type KVSetGetPayload<S extends boolean | null | undefined | KVSetDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$KVSetPayload, S>

export type KVSetCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<KVSetFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: KVSetCountAggregateInputType | true
  }

export interface KVSetDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['KVSet'], meta: { name: 'KVSet' } }
  /**
   * Find zero or one KVSet that matches the filter.
   * @param {KVSetFindUniqueArgs} args - Arguments to find a KVSet
   * @example
   * // Get one KVSet
   * const kVSet = await prisma.kVSet.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends KVSetFindUniqueArgs>(args: Prisma.SelectSubset<T, KVSetFindUniqueArgs<ExtArgs>>): Prisma.Prisma__KVSetClient<runtime.Types.Result.GetResult<Prisma.$KVSetPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one KVSet that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {KVSetFindUniqueOrThrowArgs} args - Arguments to find a KVSet
   * @example
   * // Get one KVSet
   * const kVSet = await prisma.kVSet.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends KVSetFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, KVSetFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__KVSetClient<runtime.Types.Result.GetResult<Prisma.$KVSetPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first KVSet that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {KVSetFindFirstArgs} args - Arguments to find a KVSet
   * @example
   * // Get one KVSet
   * const kVSet = await prisma.kVSet.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends KVSetFindFirstArgs>(args?: Prisma.SelectSubset<T, KVSetFindFirstArgs<ExtArgs>>): Prisma.Prisma__KVSetClient<runtime.Types.Result.GetResult<Prisma.$KVSetPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first KVSet that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {KVSetFindFirstOrThrowArgs} args - Arguments to find a KVSet
   * @example
   * // Get one KVSet
   * const kVSet = await prisma.kVSet.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends KVSetFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, KVSetFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__KVSetClient<runtime.Types.Result.GetResult<Prisma.$KVSetPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more KVSets that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {KVSetFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all KVSets
   * const kVSets = await prisma.kVSet.findMany()
   * 
   * // Get first 10 KVSets
   * const kVSets = await prisma.kVSet.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const kVSetWithIdOnly = await prisma.kVSet.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends KVSetFindManyArgs>(args?: Prisma.SelectSubset<T, KVSetFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$KVSetPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a KVSet.
   * @param {KVSetCreateArgs} args - Arguments to create a KVSet.
   * @example
   * // Create one KVSet
   * const KVSet = await prisma.kVSet.create({
   *   data: {
   *     // ... data to create a KVSet
   *   }
   * })
   * 
   */
  create<T extends KVSetCreateArgs>(args: Prisma.SelectSubset<T, KVSetCreateArgs<ExtArgs>>): Prisma.Prisma__KVSetClient<runtime.Types.Result.GetResult<Prisma.$KVSetPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many KVSets.
   * @param {KVSetCreateManyArgs} args - Arguments to create many KVSets.
   * @example
   * // Create many KVSets
   * const kVSet = await prisma.kVSet.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends KVSetCreateManyArgs>(args?: Prisma.SelectSubset<T, KVSetCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many KVSets and returns the data saved in the database.
   * @param {KVSetCreateManyAndReturnArgs} args - Arguments to create many KVSets.
   * @example
   * // Create many KVSets
   * const kVSet = await prisma.kVSet.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many KVSets and only return the `id`
   * const kVSetWithIdOnly = await prisma.kVSet.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends KVSetCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, KVSetCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$KVSetPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a KVSet.
   * @param {KVSetDeleteArgs} args - Arguments to delete one KVSet.
   * @example
   * // Delete one KVSet
   * const KVSet = await prisma.kVSet.delete({
   *   where: {
   *     // ... filter to delete one KVSet
   *   }
   * })
   * 
   */
  delete<T extends KVSetDeleteArgs>(args: Prisma.SelectSubset<T, KVSetDeleteArgs<ExtArgs>>): Prisma.Prisma__KVSetClient<runtime.Types.Result.GetResult<Prisma.$KVSetPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one KVSet.
   * @param {KVSetUpdateArgs} args - Arguments to update one KVSet.
   * @example
   * // Update one KVSet
   * const kVSet = await prisma.kVSet.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends KVSetUpdateArgs>(args: Prisma.SelectSubset<T, KVSetUpdateArgs<ExtArgs>>): Prisma.Prisma__KVSetClient<runtime.Types.Result.GetResult<Prisma.$KVSetPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more KVSets.
   * @param {KVSetDeleteManyArgs} args - Arguments to filter KVSets to delete.
   * @example
   * // Delete a few KVSets
   * const { count } = await prisma.kVSet.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends KVSetDeleteManyArgs>(args?: Prisma.SelectSubset<T, KVSetDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more KVSets.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {KVSetUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many KVSets
   * const kVSet = await prisma.kVSet.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends KVSetUpdateManyArgs>(args: Prisma.SelectSubset<T, KVSetUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more KVSets and returns the data updated in the database.
   * @param {KVSetUpdateManyAndReturnArgs} args - Arguments to update many KVSets.
   * @example
   * // Update many KVSets
   * const kVSet = await prisma.kVSet.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more KVSets and only return the `id`
   * const kVSetWithIdOnly = await prisma.kVSet.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends KVSetUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, KVSetUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$KVSetPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one KVSet.
   * @param {KVSetUpsertArgs} args - Arguments to update or create a KVSet.
   * @example
   * // Update or create a KVSet
   * const kVSet = await prisma.kVSet.upsert({
   *   create: {
   *     // ... data to create a KVSet
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the KVSet we want to update
   *   }
   * })
   */
  upsert<T extends KVSetUpsertArgs>(args: Prisma.SelectSubset<T, KVSetUpsertArgs<ExtArgs>>): Prisma.Prisma__KVSetClient<runtime.Types.Result.GetResult<Prisma.$KVSetPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of KVSets.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {KVSetCountArgs} args - Arguments to filter KVSets to count.
   * @example
   * // Count the number of KVSets
   * const count = await prisma.kVSet.count({
   *   where: {
   *     // ... the filter for the KVSets we want to count
   *   }
   * })
  **/
  count<T extends KVSetCountArgs>(
    args?: Prisma.Subset<T, KVSetCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], KVSetCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a KVSet.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {KVSetAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends KVSetAggregateArgs>(args: Prisma.Subset<T, KVSetAggregateArgs>): Prisma.PrismaPromise<GetKVSetAggregateType<T>>

  /**
   * Group by KVSet.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {KVSetGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends KVSetGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: KVSetGroupByArgs['orderBy'] }
      : { orderBy?: KVSetGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, KVSetGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetKVSetGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the KVSet model
 */
readonly fields: KVSetFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for KVSet.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__KVSetClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  values<T extends Prisma.KVSet$valuesArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.KVSet$valuesArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$KVPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  attributes<T extends Prisma.KVSet$attributesArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.KVSet$attributesArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$AttributePayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the KVSet model
 */
export interface KVSetFieldRefs {
  readonly id: Prisma.FieldRef<"KVSet", 'Int'>
  readonly name: Prisma.FieldRef<"KVSet", 'String'>
}
    

// Custom InputTypes
/**
 * KVSet findUnique
 */
export type KVSetFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the KVSet
   */
  select?: Prisma.KVSetSelect<ExtArgs> | null
  /**
   * Omit specific fields from the KVSet
   */
  omit?: Prisma.KVSetOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.KVSetInclude<ExtArgs> | null
  /**
   * Filter, which KVSet to fetch.
   */
  where: Prisma.KVSetWhereUniqueInput
}

/**
 * KVSet findUniqueOrThrow
 */
export type KVSetFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the KVSet
   */
  select?: Prisma.KVSetSelect<ExtArgs> | null
  /**
   * Omit specific fields from the KVSet
   */
  omit?: Prisma.KVSetOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.KVSetInclude<ExtArgs> | null
  /**
   * Filter, which KVSet to fetch.
   */
  where: Prisma.KVSetWhereUniqueInput
}

/**
 * KVSet findFirst
 */
export type KVSetFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the KVSet
   */
  select?: Prisma.KVSetSelect<ExtArgs> | null
  /**
   * Omit specific fields from the KVSet
   */
  omit?: Prisma.KVSetOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.KVSetInclude<ExtArgs> | null
  /**
   * Filter, which KVSet to fetch.
   */
  where?: Prisma.KVSetWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of KVSets to fetch.
   */
  orderBy?: Prisma.KVSetOrderByWithRelationInput | Prisma.KVSetOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for KVSets.
   */
  cursor?: Prisma.KVSetWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` KVSets from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` KVSets.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of KVSets.
   */
  distinct?: Prisma.KVSetScalarFieldEnum | Prisma.KVSetScalarFieldEnum[]
}

/**
 * KVSet findFirstOrThrow
 */
export type KVSetFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the KVSet
   */
  select?: Prisma.KVSetSelect<ExtArgs> | null
  /**
   * Omit specific fields from the KVSet
   */
  omit?: Prisma.KVSetOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.KVSetInclude<ExtArgs> | null
  /**
   * Filter, which KVSet to fetch.
   */
  where?: Prisma.KVSetWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of KVSets to fetch.
   */
  orderBy?: Prisma.KVSetOrderByWithRelationInput | Prisma.KVSetOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for KVSets.
   */
  cursor?: Prisma.KVSetWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` KVSets from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` KVSets.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of KVSets.
   */
  distinct?: Prisma.KVSetScalarFieldEnum | Prisma.KVSetScalarFieldEnum[]
}

/**
 * KVSet findMany
 */
export type KVSetFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the KVSet
   */
  select?: Prisma.KVSetSelect<ExtArgs> | null
  /**
   * Omit specific fields from the KVSet
   */
  omit?: Prisma.KVSetOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.KVSetInclude<ExtArgs> | null
  /**
   * Filter, which KVSets to fetch.
   */
  where?: Prisma.KVSetWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of KVSets to fetch.
   */
  orderBy?: Prisma.KVSetOrderByWithRelationInput | Prisma.KVSetOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing KVSets.
   */
  cursor?: Prisma.KVSetWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` KVSets from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` KVSets.
   */
  skip?: number
  distinct?: Prisma.KVSetScalarFieldEnum | Prisma.KVSetScalarFieldEnum[]
}

/**
 * KVSet create
 */
export type KVSetCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the KVSet
   */
  select?: Prisma.KVSetSelect<ExtArgs> | null
  /**
   * Omit specific fields from the KVSet
   */
  omit?: Prisma.KVSetOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.KVSetInclude<ExtArgs> | null
  /**
   * The data needed to create a KVSet.
   */
  data: Prisma.XOR<Prisma.KVSetCreateInput, Prisma.KVSetUncheckedCreateInput>
}

/**
 * KVSet createMany
 */
export type KVSetCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many KVSets.
   */
  data: Prisma.KVSetCreateManyInput | Prisma.KVSetCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * KVSet createManyAndReturn
 */
export type KVSetCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the KVSet
   */
  select?: Prisma.KVSetSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the KVSet
   */
  omit?: Prisma.KVSetOmit<ExtArgs> | null
  /**
   * The data used to create many KVSets.
   */
  data: Prisma.KVSetCreateManyInput | Prisma.KVSetCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * KVSet update
 */
export type KVSetUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the KVSet
   */
  select?: Prisma.KVSetSelect<ExtArgs> | null
  /**
   * Omit specific fields from the KVSet
   */
  omit?: Prisma.KVSetOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.KVSetInclude<ExtArgs> | null
  /**
   * The data needed to update a KVSet.
   */
  data: Prisma.XOR<Prisma.KVSetUpdateInput, Prisma.KVSetUncheckedUpdateInput>
  /**
   * Choose, which KVSet to update.
   */
  where: Prisma.KVSetWhereUniqueInput
}

/**
 * KVSet updateMany
 */
export type KVSetUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update KVSets.
   */
  data: Prisma.XOR<Prisma.KVSetUpdateManyMutationInput, Prisma.KVSetUncheckedUpdateManyInput>
  /**
   * Filter which KVSets to update
   */
  where?: Prisma.KVSetWhereInput
  /**
   * Limit how many KVSets to update.
   */
  limit?: number
}

/**
 * KVSet updateManyAndReturn
 */
export type KVSetUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the KVSet
   */
  select?: Prisma.KVSetSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the KVSet
   */
  omit?: Prisma.KVSetOmit<ExtArgs> | null
  /**
   * The data used to update KVSets.
   */
  data: Prisma.XOR<Prisma.KVSetUpdateManyMutationInput, Prisma.KVSetUncheckedUpdateManyInput>
  /**
   * Filter which KVSets to update
   */
  where?: Prisma.KVSetWhereInput
  /**
   * Limit how many KVSets to update.
   */
  limit?: number
}

/**
 * KVSet upsert
 */
export type KVSetUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the KVSet
   */
  select?: Prisma.KVSetSelect<ExtArgs> | null
  /**
   * Omit specific fields from the KVSet
   */
  omit?: Prisma.KVSetOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.KVSetInclude<ExtArgs> | null
  /**
   * The filter to search for the KVSet to update in case it exists.
   */
  where: Prisma.KVSetWhereUniqueInput
  /**
   * In case the KVSet found by the `where` argument doesn't exist, create a new KVSet with this data.
   */
  create: Prisma.XOR<Prisma.KVSetCreateInput, Prisma.KVSetUncheckedCreateInput>
  /**
   * In case the KVSet was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.KVSetUpdateInput, Prisma.KVSetUncheckedUpdateInput>
}

/**
 * KVSet delete
 */
export type KVSetDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the KVSet
   */
  select?: Prisma.KVSetSelect<ExtArgs> | null
  /**
   * Omit specific fields from the KVSet
   */
  omit?: Prisma.KVSetOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.KVSetInclude<ExtArgs> | null
  /**
   * Filter which KVSet to delete.
   */
  where: Prisma.KVSetWhereUniqueInput
}

/**
 * KVSet deleteMany
 */
export type KVSetDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which KVSets to delete
   */
  where?: Prisma.KVSetWhereInput
  /**
   * Limit how many KVSets to delete.
   */
  limit?: number
}

/**
 * KVSet.values
 */
export type KVSet$valuesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the KV
   */
  select?: Prisma.KVSelect<ExtArgs> | null
  /**
   * Omit specific fields from the KV
   */
  omit?: Prisma.KVOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.KVInclude<ExtArgs> | null
  where?: Prisma.KVWhereInput
  orderBy?: Prisma.KVOrderByWithRelationInput | Prisma.KVOrderByWithRelationInput[]
  cursor?: Prisma.KVWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.KVScalarFieldEnum | Prisma.KVScalarFieldEnum[]
}

/**
 * KVSet.attributes
 */
export type KVSet$attributesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Attribute
   */
  select?: Prisma.AttributeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Attribute
   */
  omit?: Prisma.AttributeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AttributeInclude<ExtArgs> | null
  where?: Prisma.AttributeWhereInput
  orderBy?: Prisma.AttributeOrderByWithRelationInput | Prisma.AttributeOrderByWithRelationInput[]
  cursor?: Prisma.AttributeWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.AttributeScalarFieldEnum | Prisma.AttributeScalarFieldEnum[]
}

/**
 * KVSet without action
 */
export type KVSetDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the KVSet
   */
  select?: Prisma.KVSetSelect<ExtArgs> | null
  /**
   * Omit specific fields from the KVSet
   */
  omit?: Prisma.KVSetOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.KVSetInclude<ExtArgs> | null
}
