
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `Range` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model Range
 * 
 */
export type RangeModel = runtime.Types.Result.DefaultSelection<Prisma.$RangePayload>

export type AggregateRange = {
  _count: RangeCountAggregateOutputType | null
  _avg: RangeAvgAggregateOutputType | null
  _sum: RangeSumAggregateOutputType | null
  _min: RangeMinAggregateOutputType | null
  _max: RangeMaxAggregateOutputType | null
}

export type RangeAvgAggregateOutputType = {
  id: number | null
  min: number | null
  max: number | null
}

export type RangeSumAggregateOutputType = {
  id: number | null
  min: number | null
  max: number | null
}

export type RangeMinAggregateOutputType = {
  id: number | null
  min: number | null
  max: number | null
}

export type RangeMaxAggregateOutputType = {
  id: number | null
  min: number | null
  max: number | null
}

export type RangeCountAggregateOutputType = {
  id: number
  min: number
  max: number
  _all: number
}


export type RangeAvgAggregateInputType = {
  id?: true
  min?: true
  max?: true
}

export type RangeSumAggregateInputType = {
  id?: true
  min?: true
  max?: true
}

export type RangeMinAggregateInputType = {
  id?: true
  min?: true
  max?: true
}

export type RangeMaxAggregateInputType = {
  id?: true
  min?: true
  max?: true
}

export type RangeCountAggregateInputType = {
  id?: true
  min?: true
  max?: true
  _all?: true
}

export type RangeAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Range to aggregate.
   */
  where?: Prisma.RangeWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Ranges to fetch.
   */
  orderBy?: Prisma.RangeOrderByWithRelationInput | Prisma.RangeOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.RangeWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Ranges from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Ranges.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Ranges
  **/
  _count?: true | RangeCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: RangeAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: RangeSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: RangeMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: RangeMaxAggregateInputType
}

export type GetRangeAggregateType<T extends RangeAggregateArgs> = {
      [P in keyof T & keyof AggregateRange]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateRange[P]>
    : Prisma.GetScalarType<T[P], AggregateRange[P]>
}




export type RangeGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.RangeWhereInput
  orderBy?: Prisma.RangeOrderByWithAggregationInput | Prisma.RangeOrderByWithAggregationInput[]
  by: Prisma.RangeScalarFieldEnum[] | Prisma.RangeScalarFieldEnum
  having?: Prisma.RangeScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: RangeCountAggregateInputType | true
  _avg?: RangeAvgAggregateInputType
  _sum?: RangeSumAggregateInputType
  _min?: RangeMinAggregateInputType
  _max?: RangeMaxAggregateInputType
}

export type RangeGroupByOutputType = {
  id: number
  min: number | null
  max: number | null
  _count: RangeCountAggregateOutputType | null
  _avg: RangeAvgAggregateOutputType | null
  _sum: RangeSumAggregateOutputType | null
  _min: RangeMinAggregateOutputType | null
  _max: RangeMaxAggregateOutputType | null
}

type GetRangeGroupByPayload<T extends RangeGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<RangeGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof RangeGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], RangeGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], RangeGroupByOutputType[P]>
      }
    >
  >



export type RangeWhereInput = {
  AND?: Prisma.RangeWhereInput | Prisma.RangeWhereInput[]
  OR?: Prisma.RangeWhereInput[]
  NOT?: Prisma.RangeWhereInput | Prisma.RangeWhereInput[]
  id?: Prisma.IntFilter<"Range"> | number
  min?: Prisma.FloatNullableFilter<"Range"> | number | null
  max?: Prisma.FloatNullableFilter<"Range"> | number | null
  attributes?: Prisma.AttributeListRelationFilter
}

export type RangeOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  min?: Prisma.SortOrderInput | Prisma.SortOrder
  max?: Prisma.SortOrderInput | Prisma.SortOrder
  attributes?: Prisma.AttributeOrderByRelationAggregateInput
}

export type RangeWhereUniqueInput = Prisma.AtLeast<{
  id?: number
  AND?: Prisma.RangeWhereInput | Prisma.RangeWhereInput[]
  OR?: Prisma.RangeWhereInput[]
  NOT?: Prisma.RangeWhereInput | Prisma.RangeWhereInput[]
  min?: Prisma.FloatNullableFilter<"Range"> | number | null
  max?: Prisma.FloatNullableFilter<"Range"> | number | null
  attributes?: Prisma.AttributeListRelationFilter
}, "id">

export type RangeOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  min?: Prisma.SortOrderInput | Prisma.SortOrder
  max?: Prisma.SortOrderInput | Prisma.SortOrder
  _count?: Prisma.RangeCountOrderByAggregateInput
  _avg?: Prisma.RangeAvgOrderByAggregateInput
  _max?: Prisma.RangeMaxOrderByAggregateInput
  _min?: Prisma.RangeMinOrderByAggregateInput
  _sum?: Prisma.RangeSumOrderByAggregateInput
}

export type RangeScalarWhereWithAggregatesInput = {
  AND?: Prisma.RangeScalarWhereWithAggregatesInput | Prisma.RangeScalarWhereWithAggregatesInput[]
  OR?: Prisma.RangeScalarWhereWithAggregatesInput[]
  NOT?: Prisma.RangeScalarWhereWithAggregatesInput | Prisma.RangeScalarWhereWithAggregatesInput[]
  id?: Prisma.IntWithAggregatesFilter<"Range"> | number
  min?: Prisma.FloatNullableWithAggregatesFilter<"Range"> | number | null
  max?: Prisma.FloatNullableWithAggregatesFilter<"Range"> | number | null
}

export type RangeCreateInput = {
  min?: number | null
  max?: number | null
  attributes?: Prisma.AttributeCreateNestedManyWithoutRangeInput
}

export type RangeUncheckedCreateInput = {
  id?: number
  min?: number | null
  max?: number | null
  attributes?: Prisma.AttributeUncheckedCreateNestedManyWithoutRangeInput
}

export type RangeUpdateInput = {
  min?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  max?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  attributes?: Prisma.AttributeUpdateManyWithoutRangeNestedInput
}

export type RangeUncheckedUpdateInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  min?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  max?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  attributes?: Prisma.AttributeUncheckedUpdateManyWithoutRangeNestedInput
}

export type RangeCreateManyInput = {
  id?: number
  min?: number | null
  max?: number | null
}

export type RangeUpdateManyMutationInput = {
  min?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  max?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
}

export type RangeUncheckedUpdateManyInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  min?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  max?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
}

export type RangeNullableScalarRelationFilter = {
  is?: Prisma.RangeWhereInput | null
  isNot?: Prisma.RangeWhereInput | null
}

export type RangeCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  min?: Prisma.SortOrder
  max?: Prisma.SortOrder
}

export type RangeAvgOrderByAggregateInput = {
  id?: Prisma.SortOrder
  min?: Prisma.SortOrder
  max?: Prisma.SortOrder
}

export type RangeMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  min?: Prisma.SortOrder
  max?: Prisma.SortOrder
}

export type RangeMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  min?: Prisma.SortOrder
  max?: Prisma.SortOrder
}

export type RangeSumOrderByAggregateInput = {
  id?: Prisma.SortOrder
  min?: Prisma.SortOrder
  max?: Prisma.SortOrder
}

export type RangeCreateNestedOneWithoutAttributesInput = {
  create?: Prisma.XOR<Prisma.RangeCreateWithoutAttributesInput, Prisma.RangeUncheckedCreateWithoutAttributesInput>
  connectOrCreate?: Prisma.RangeCreateOrConnectWithoutAttributesInput
  connect?: Prisma.RangeWhereUniqueInput
}

export type RangeUpdateOneWithoutAttributesNestedInput = {
  create?: Prisma.XOR<Prisma.RangeCreateWithoutAttributesInput, Prisma.RangeUncheckedCreateWithoutAttributesInput>
  connectOrCreate?: Prisma.RangeCreateOrConnectWithoutAttributesInput
  upsert?: Prisma.RangeUpsertWithoutAttributesInput
  disconnect?: Prisma.RangeWhereInput | boolean
  delete?: Prisma.RangeWhereInput | boolean
  connect?: Prisma.RangeWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.RangeUpdateToOneWithWhereWithoutAttributesInput, Prisma.RangeUpdateWithoutAttributesInput>, Prisma.RangeUncheckedUpdateWithoutAttributesInput>
}

export type RangeCreateWithoutAttributesInput = {
  min?: number | null
  max?: number | null
}

export type RangeUncheckedCreateWithoutAttributesInput = {
  id?: number
  min?: number | null
  max?: number | null
}

export type RangeCreateOrConnectWithoutAttributesInput = {
  where: Prisma.RangeWhereUniqueInput
  create: Prisma.XOR<Prisma.RangeCreateWithoutAttributesInput, Prisma.RangeUncheckedCreateWithoutAttributesInput>
}

export type RangeUpsertWithoutAttributesInput = {
  update: Prisma.XOR<Prisma.RangeUpdateWithoutAttributesInput, Prisma.RangeUncheckedUpdateWithoutAttributesInput>
  create: Prisma.XOR<Prisma.RangeCreateWithoutAttributesInput, Prisma.RangeUncheckedCreateWithoutAttributesInput>
  where?: Prisma.RangeWhereInput
}

export type RangeUpdateToOneWithWhereWithoutAttributesInput = {
  where?: Prisma.RangeWhereInput
  data: Prisma.XOR<Prisma.RangeUpdateWithoutAttributesInput, Prisma.RangeUncheckedUpdateWithoutAttributesInput>
}

export type RangeUpdateWithoutAttributesInput = {
  min?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  max?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
}

export type RangeUncheckedUpdateWithoutAttributesInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  min?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  max?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
}


/**
 * Count Type RangeCountOutputType
 */

export type RangeCountOutputType = {
  attributes: number
}

export type RangeCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  attributes?: boolean | RangeCountOutputTypeCountAttributesArgs
}

/**
 * RangeCountOutputType without action
 */
export type RangeCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RangeCountOutputType
   */
  select?: Prisma.RangeCountOutputTypeSelect<ExtArgs> | null
}

/**
 * RangeCountOutputType without action
 */
export type RangeCountOutputTypeCountAttributesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.AttributeWhereInput
}


export type RangeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  min?: boolean
  max?: boolean
  attributes?: boolean | Prisma.Range$attributesArgs<ExtArgs>
  _count?: boolean | Prisma.RangeCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["range"]>

export type RangeSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  min?: boolean
  max?: boolean
}, ExtArgs["result"]["range"]>

export type RangeSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  min?: boolean
  max?: boolean
}, ExtArgs["result"]["range"]>

export type RangeSelectScalar = {
  id?: boolean
  min?: boolean
  max?: boolean
}

export type RangeOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "min" | "max", ExtArgs["result"]["range"]>
export type RangeInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  attributes?: boolean | Prisma.Range$attributesArgs<ExtArgs>
  _count?: boolean | Prisma.RangeCountOutputTypeDefaultArgs<ExtArgs>
}
export type RangeIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}
export type RangeIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}

export type $RangePayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Range"
  objects: {
    attributes: Prisma.$AttributePayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: number
    min: number | null
    max: number | null
  }, ExtArgs["result"]["range"]>
  composites: {}
}

export type RangeGetPayload<S extends boolean | null | undefined | RangeDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$RangePayload, S>

export type RangeCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<RangeFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: RangeCountAggregateInputType | true
  }

export interface RangeDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Range'], meta: { name: 'Range' } }
  /**
   * Find zero or one Range that matches the filter.
   * @param {RangeFindUniqueArgs} args - Arguments to find a Range
   * @example
   * // Get one Range
   * const range = await prisma.range.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends RangeFindUniqueArgs>(args: Prisma.SelectSubset<T, RangeFindUniqueArgs<ExtArgs>>): Prisma.Prisma__RangeClient<runtime.Types.Result.GetResult<Prisma.$RangePayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Range that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {RangeFindUniqueOrThrowArgs} args - Arguments to find a Range
   * @example
   * // Get one Range
   * const range = await prisma.range.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends RangeFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, RangeFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__RangeClient<runtime.Types.Result.GetResult<Prisma.$RangePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Range that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RangeFindFirstArgs} args - Arguments to find a Range
   * @example
   * // Get one Range
   * const range = await prisma.range.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends RangeFindFirstArgs>(args?: Prisma.SelectSubset<T, RangeFindFirstArgs<ExtArgs>>): Prisma.Prisma__RangeClient<runtime.Types.Result.GetResult<Prisma.$RangePayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Range that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RangeFindFirstOrThrowArgs} args - Arguments to find a Range
   * @example
   * // Get one Range
   * const range = await prisma.range.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends RangeFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, RangeFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__RangeClient<runtime.Types.Result.GetResult<Prisma.$RangePayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Ranges that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RangeFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Ranges
   * const ranges = await prisma.range.findMany()
   * 
   * // Get first 10 Ranges
   * const ranges = await prisma.range.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const rangeWithIdOnly = await prisma.range.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends RangeFindManyArgs>(args?: Prisma.SelectSubset<T, RangeFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$RangePayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Range.
   * @param {RangeCreateArgs} args - Arguments to create a Range.
   * @example
   * // Create one Range
   * const Range = await prisma.range.create({
   *   data: {
   *     // ... data to create a Range
   *   }
   * })
   * 
   */
  create<T extends RangeCreateArgs>(args: Prisma.SelectSubset<T, RangeCreateArgs<ExtArgs>>): Prisma.Prisma__RangeClient<runtime.Types.Result.GetResult<Prisma.$RangePayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Ranges.
   * @param {RangeCreateManyArgs} args - Arguments to create many Ranges.
   * @example
   * // Create many Ranges
   * const range = await prisma.range.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends RangeCreateManyArgs>(args?: Prisma.SelectSubset<T, RangeCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Ranges and returns the data saved in the database.
   * @param {RangeCreateManyAndReturnArgs} args - Arguments to create many Ranges.
   * @example
   * // Create many Ranges
   * const range = await prisma.range.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Ranges and only return the `id`
   * const rangeWithIdOnly = await prisma.range.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends RangeCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, RangeCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$RangePayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Range.
   * @param {RangeDeleteArgs} args - Arguments to delete one Range.
   * @example
   * // Delete one Range
   * const Range = await prisma.range.delete({
   *   where: {
   *     // ... filter to delete one Range
   *   }
   * })
   * 
   */
  delete<T extends RangeDeleteArgs>(args: Prisma.SelectSubset<T, RangeDeleteArgs<ExtArgs>>): Prisma.Prisma__RangeClient<runtime.Types.Result.GetResult<Prisma.$RangePayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Range.
   * @param {RangeUpdateArgs} args - Arguments to update one Range.
   * @example
   * // Update one Range
   * const range = await prisma.range.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends RangeUpdateArgs>(args: Prisma.SelectSubset<T, RangeUpdateArgs<ExtArgs>>): Prisma.Prisma__RangeClient<runtime.Types.Result.GetResult<Prisma.$RangePayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Ranges.
   * @param {RangeDeleteManyArgs} args - Arguments to filter Ranges to delete.
   * @example
   * // Delete a few Ranges
   * const { count } = await prisma.range.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends RangeDeleteManyArgs>(args?: Prisma.SelectSubset<T, RangeDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Ranges.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RangeUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Ranges
   * const range = await prisma.range.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends RangeUpdateManyArgs>(args: Prisma.SelectSubset<T, RangeUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Ranges and returns the data updated in the database.
   * @param {RangeUpdateManyAndReturnArgs} args - Arguments to update many Ranges.
   * @example
   * // Update many Ranges
   * const range = await prisma.range.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Ranges and only return the `id`
   * const rangeWithIdOnly = await prisma.range.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends RangeUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, RangeUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$RangePayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Range.
   * @param {RangeUpsertArgs} args - Arguments to update or create a Range.
   * @example
   * // Update or create a Range
   * const range = await prisma.range.upsert({
   *   create: {
   *     // ... data to create a Range
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Range we want to update
   *   }
   * })
   */
  upsert<T extends RangeUpsertArgs>(args: Prisma.SelectSubset<T, RangeUpsertArgs<ExtArgs>>): Prisma.Prisma__RangeClient<runtime.Types.Result.GetResult<Prisma.$RangePayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Ranges.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RangeCountArgs} args - Arguments to filter Ranges to count.
   * @example
   * // Count the number of Ranges
   * const count = await prisma.range.count({
   *   where: {
   *     // ... the filter for the Ranges we want to count
   *   }
   * })
  **/
  count<T extends RangeCountArgs>(
    args?: Prisma.Subset<T, RangeCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], RangeCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Range.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RangeAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends RangeAggregateArgs>(args: Prisma.Subset<T, RangeAggregateArgs>): Prisma.PrismaPromise<GetRangeAggregateType<T>>

  /**
   * Group by Range.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RangeGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends RangeGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: RangeGroupByArgs['orderBy'] }
      : { orderBy?: RangeGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, RangeGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetRangeGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Range model
 */
readonly fields: RangeFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Range.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__RangeClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  attributes<T extends Prisma.Range$attributesArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Range$attributesArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$AttributePayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Range model
 */
export interface RangeFieldRefs {
  readonly id: Prisma.FieldRef<"Range", 'Int'>
  readonly min: Prisma.FieldRef<"Range", 'Float'>
  readonly max: Prisma.FieldRef<"Range", 'Float'>
}
    

// Custom InputTypes
/**
 * Range findUnique
 */
export type RangeFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Range
   */
  select?: Prisma.RangeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Range
   */
  omit?: Prisma.RangeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RangeInclude<ExtArgs> | null
  /**
   * Filter, which Range to fetch.
   */
  where: Prisma.RangeWhereUniqueInput
}

/**
 * Range findUniqueOrThrow
 */
export type RangeFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Range
   */
  select?: Prisma.RangeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Range
   */
  omit?: Prisma.RangeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RangeInclude<ExtArgs> | null
  /**
   * Filter, which Range to fetch.
   */
  where: Prisma.RangeWhereUniqueInput
}

/**
 * Range findFirst
 */
export type RangeFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Range
   */
  select?: Prisma.RangeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Range
   */
  omit?: Prisma.RangeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RangeInclude<ExtArgs> | null
  /**
   * Filter, which Range to fetch.
   */
  where?: Prisma.RangeWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Ranges to fetch.
   */
  orderBy?: Prisma.RangeOrderByWithRelationInput | Prisma.RangeOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Ranges.
   */
  cursor?: Prisma.RangeWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Ranges from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Ranges.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Ranges.
   */
  distinct?: Prisma.RangeScalarFieldEnum | Prisma.RangeScalarFieldEnum[]
}

/**
 * Range findFirstOrThrow
 */
export type RangeFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Range
   */
  select?: Prisma.RangeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Range
   */
  omit?: Prisma.RangeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RangeInclude<ExtArgs> | null
  /**
   * Filter, which Range to fetch.
   */
  where?: Prisma.RangeWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Ranges to fetch.
   */
  orderBy?: Prisma.RangeOrderByWithRelationInput | Prisma.RangeOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Ranges.
   */
  cursor?: Prisma.RangeWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Ranges from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Ranges.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Ranges.
   */
  distinct?: Prisma.RangeScalarFieldEnum | Prisma.RangeScalarFieldEnum[]
}

/**
 * Range findMany
 */
export type RangeFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Range
   */
  select?: Prisma.RangeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Range
   */
  omit?: Prisma.RangeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RangeInclude<ExtArgs> | null
  /**
   * Filter, which Ranges to fetch.
   */
  where?: Prisma.RangeWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Ranges to fetch.
   */
  orderBy?: Prisma.RangeOrderByWithRelationInput | Prisma.RangeOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Ranges.
   */
  cursor?: Prisma.RangeWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Ranges from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Ranges.
   */
  skip?: number
  distinct?: Prisma.RangeScalarFieldEnum | Prisma.RangeScalarFieldEnum[]
}

/**
 * Range create
 */
export type RangeCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Range
   */
  select?: Prisma.RangeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Range
   */
  omit?: Prisma.RangeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RangeInclude<ExtArgs> | null
  /**
   * The data needed to create a Range.
   */
  data?: Prisma.XOR<Prisma.RangeCreateInput, Prisma.RangeUncheckedCreateInput>
}

/**
 * Range createMany
 */
export type RangeCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Ranges.
   */
  data: Prisma.RangeCreateManyInput | Prisma.RangeCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Range createManyAndReturn
 */
export type RangeCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Range
   */
  select?: Prisma.RangeSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Range
   */
  omit?: Prisma.RangeOmit<ExtArgs> | null
  /**
   * The data used to create many Ranges.
   */
  data: Prisma.RangeCreateManyInput | Prisma.RangeCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Range update
 */
export type RangeUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Range
   */
  select?: Prisma.RangeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Range
   */
  omit?: Prisma.RangeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RangeInclude<ExtArgs> | null
  /**
   * The data needed to update a Range.
   */
  data: Prisma.XOR<Prisma.RangeUpdateInput, Prisma.RangeUncheckedUpdateInput>
  /**
   * Choose, which Range to update.
   */
  where: Prisma.RangeWhereUniqueInput
}

/**
 * Range updateMany
 */
export type RangeUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Ranges.
   */
  data: Prisma.XOR<Prisma.RangeUpdateManyMutationInput, Prisma.RangeUncheckedUpdateManyInput>
  /**
   * Filter which Ranges to update
   */
  where?: Prisma.RangeWhereInput
  /**
   * Limit how many Ranges to update.
   */
  limit?: number
}

/**
 * Range updateManyAndReturn
 */
export type RangeUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Range
   */
  select?: Prisma.RangeSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Range
   */
  omit?: Prisma.RangeOmit<ExtArgs> | null
  /**
   * The data used to update Ranges.
   */
  data: Prisma.XOR<Prisma.RangeUpdateManyMutationInput, Prisma.RangeUncheckedUpdateManyInput>
  /**
   * Filter which Ranges to update
   */
  where?: Prisma.RangeWhereInput
  /**
   * Limit how many Ranges to update.
   */
  limit?: number
}

/**
 * Range upsert
 */
export type RangeUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Range
   */
  select?: Prisma.RangeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Range
   */
  omit?: Prisma.RangeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RangeInclude<ExtArgs> | null
  /**
   * The filter to search for the Range to update in case it exists.
   */
  where: Prisma.RangeWhereUniqueInput
  /**
   * In case the Range found by the `where` argument doesn't exist, create a new Range with this data.
   */
  create: Prisma.XOR<Prisma.RangeCreateInput, Prisma.RangeUncheckedCreateInput>
  /**
   * In case the Range was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.RangeUpdateInput, Prisma.RangeUncheckedUpdateInput>
}

/**
 * Range delete
 */
export type RangeDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Range
   */
  select?: Prisma.RangeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Range
   */
  omit?: Prisma.RangeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RangeInclude<ExtArgs> | null
  /**
   * Filter which Range to delete.
   */
  where: Prisma.RangeWhereUniqueInput
}

/**
 * Range deleteMany
 */
export type RangeDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Ranges to delete
   */
  where?: Prisma.RangeWhereInput
  /**
   * Limit how many Ranges to delete.
   */
  limit?: number
}

/**
 * Range.attributes
 */
export type Range$attributesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Attribute
   */
  select?: Prisma.AttributeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Attribute
   */
  omit?: Prisma.AttributeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AttributeInclude<ExtArgs> | null
  where?: Prisma.AttributeWhereInput
  orderBy?: Prisma.AttributeOrderByWithRelationInput | Prisma.AttributeOrderByWithRelationInput[]
  cursor?: Prisma.AttributeWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.AttributeScalarFieldEnum | Prisma.AttributeScalarFieldEnum[]
}

/**
 * Range without action
 */
export type RangeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Range
   */
  select?: Prisma.RangeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Range
   */
  omit?: Prisma.RangeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RangeInclude<ExtArgs> | null
}
