
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `Table1` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model Table1
 * 
 */
export type Table1Model = runtime.Types.Result.DefaultSelection<Prisma.$Table1Payload>

export type AggregateTable1 = {
  _count: Table1CountAggregateOutputType | null
  _avg: Table1AvgAggregateOutputType | null
  _sum: Table1SumAggregateOutputType | null
  _min: Table1MinAggregateOutputType | null
  _max: Table1MaxAggregateOutputType | null
}

export type Table1AvgAggregateOutputType = {
  id: number | null
  col2: number | null
  col3: number | null
}

export type Table1SumAggregateOutputType = {
  id: number | null
  col2: number | null
  col3: number | null
}

export type Table1MinAggregateOutputType = {
  id: number | null
  col1: Date | null
  col2: number | null
  col3: number | null
  col4: string | null
  col5: string | null
  col6: string | null
  createdAt: Date | null
  updatedAt: Date | null
  deletedAt: Date | null
}

export type Table1MaxAggregateOutputType = {
  id: number | null
  col1: Date | null
  col2: number | null
  col3: number | null
  col4: string | null
  col5: string | null
  col6: string | null
  createdAt: Date | null
  updatedAt: Date | null
  deletedAt: Date | null
}

export type Table1CountAggregateOutputType = {
  id: number
  col1: number
  col2: number
  col3: number
  col4: number
  col5: number
  col6: number
  createdAt: number
  updatedAt: number
  deletedAt: number
  _all: number
}


export type Table1AvgAggregateInputType = {
  id?: true
  col2?: true
  col3?: true
}

export type Table1SumAggregateInputType = {
  id?: true
  col2?: true
  col3?: true
}

export type Table1MinAggregateInputType = {
  id?: true
  col1?: true
  col2?: true
  col3?: true
  col4?: true
  col5?: true
  col6?: true
  createdAt?: true
  updatedAt?: true
  deletedAt?: true
}

export type Table1MaxAggregateInputType = {
  id?: true
  col1?: true
  col2?: true
  col3?: true
  col4?: true
  col5?: true
  col6?: true
  createdAt?: true
  updatedAt?: true
  deletedAt?: true
}

export type Table1CountAggregateInputType = {
  id?: true
  col1?: true
  col2?: true
  col3?: true
  col4?: true
  col5?: true
  col6?: true
  createdAt?: true
  updatedAt?: true
  deletedAt?: true
  _all?: true
}

export type Table1AggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Table1 to aggregate.
   */
  where?: Prisma.Table1WhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Table1s to fetch.
   */
  orderBy?: Prisma.Table1OrderByWithRelationInput | Prisma.Table1OrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.Table1WhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Table1s from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Table1s.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Table1s
  **/
  _count?: true | Table1CountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: Table1AvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: Table1SumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: Table1MinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: Table1MaxAggregateInputType
}

export type GetTable1AggregateType<T extends Table1AggregateArgs> = {
      [P in keyof T & keyof AggregateTable1]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateTable1[P]>
    : Prisma.GetScalarType<T[P], AggregateTable1[P]>
}




export type Table1GroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.Table1WhereInput
  orderBy?: Prisma.Table1OrderByWithAggregationInput | Prisma.Table1OrderByWithAggregationInput[]
  by: Prisma.Table1ScalarFieldEnum[] | Prisma.Table1ScalarFieldEnum
  having?: Prisma.Table1ScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: Table1CountAggregateInputType | true
  _avg?: Table1AvgAggregateInputType
  _sum?: Table1SumAggregateInputType
  _min?: Table1MinAggregateInputType
  _max?: Table1MaxAggregateInputType
}

export type Table1GroupByOutputType = {
  id: number
  col1: Date | null
  col2: number | null
  col3: number | null
  col4: string | null
  col5: string | null
  col6: string | null
  createdAt: Date | null
  updatedAt: Date | null
  deletedAt: Date | null
  _count: Table1CountAggregateOutputType | null
  _avg: Table1AvgAggregateOutputType | null
  _sum: Table1SumAggregateOutputType | null
  _min: Table1MinAggregateOutputType | null
  _max: Table1MaxAggregateOutputType | null
}

type GetTable1GroupByPayload<T extends Table1GroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<Table1GroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof Table1GroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], Table1GroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], Table1GroupByOutputType[P]>
      }
    >
  >



export type Table1WhereInput = {
  AND?: Prisma.Table1WhereInput | Prisma.Table1WhereInput[]
  OR?: Prisma.Table1WhereInput[]
  NOT?: Prisma.Table1WhereInput | Prisma.Table1WhereInput[]
  id?: Prisma.IntFilter<"Table1"> | number
  col1?: Prisma.DateTimeNullableFilter<"Table1"> | Date | string | null
  col2?: Prisma.FloatNullableFilter<"Table1"> | number | null
  col3?: Prisma.FloatNullableFilter<"Table1"> | number | null
  col4?: Prisma.StringNullableFilter<"Table1"> | string | null
  col5?: Prisma.StringNullableFilter<"Table1"> | string | null
  col6?: Prisma.StringNullableFilter<"Table1"> | string | null
  createdAt?: Prisma.DateTimeNullableFilter<"Table1"> | Date | string | null
  updatedAt?: Prisma.DateTimeNullableFilter<"Table1"> | Date | string | null
  deletedAt?: Prisma.DateTimeNullableFilter<"Table1"> | Date | string | null
  columns?: Prisma.ColumnEListRelationFilter
}

export type Table1OrderByWithRelationInput = {
  id?: Prisma.SortOrder
  col1?: Prisma.SortOrderInput | Prisma.SortOrder
  col2?: Prisma.SortOrderInput | Prisma.SortOrder
  col3?: Prisma.SortOrderInput | Prisma.SortOrder
  col4?: Prisma.SortOrderInput | Prisma.SortOrder
  col5?: Prisma.SortOrderInput | Prisma.SortOrder
  col6?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrderInput | Prisma.SortOrder
  updatedAt?: Prisma.SortOrderInput | Prisma.SortOrder
  deletedAt?: Prisma.SortOrderInput | Prisma.SortOrder
  columns?: Prisma.ColumnEOrderByRelationAggregateInput
}

export type Table1WhereUniqueInput = Prisma.AtLeast<{
  id?: number
  AND?: Prisma.Table1WhereInput | Prisma.Table1WhereInput[]
  OR?: Prisma.Table1WhereInput[]
  NOT?: Prisma.Table1WhereInput | Prisma.Table1WhereInput[]
  col1?: Prisma.DateTimeNullableFilter<"Table1"> | Date | string | null
  col2?: Prisma.FloatNullableFilter<"Table1"> | number | null
  col3?: Prisma.FloatNullableFilter<"Table1"> | number | null
  col4?: Prisma.StringNullableFilter<"Table1"> | string | null
  col5?: Prisma.StringNullableFilter<"Table1"> | string | null
  col6?: Prisma.StringNullableFilter<"Table1"> | string | null
  createdAt?: Prisma.DateTimeNullableFilter<"Table1"> | Date | string | null
  updatedAt?: Prisma.DateTimeNullableFilter<"Table1"> | Date | string | null
  deletedAt?: Prisma.DateTimeNullableFilter<"Table1"> | Date | string | null
  columns?: Prisma.ColumnEListRelationFilter
}, "id">

export type Table1OrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  col1?: Prisma.SortOrderInput | Prisma.SortOrder
  col2?: Prisma.SortOrderInput | Prisma.SortOrder
  col3?: Prisma.SortOrderInput | Prisma.SortOrder
  col4?: Prisma.SortOrderInput | Prisma.SortOrder
  col5?: Prisma.SortOrderInput | Prisma.SortOrder
  col6?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrderInput | Prisma.SortOrder
  updatedAt?: Prisma.SortOrderInput | Prisma.SortOrder
  deletedAt?: Prisma.SortOrderInput | Prisma.SortOrder
  _count?: Prisma.Table1CountOrderByAggregateInput
  _avg?: Prisma.Table1AvgOrderByAggregateInput
  _max?: Prisma.Table1MaxOrderByAggregateInput
  _min?: Prisma.Table1MinOrderByAggregateInput
  _sum?: Prisma.Table1SumOrderByAggregateInput
}

export type Table1ScalarWhereWithAggregatesInput = {
  AND?: Prisma.Table1ScalarWhereWithAggregatesInput | Prisma.Table1ScalarWhereWithAggregatesInput[]
  OR?: Prisma.Table1ScalarWhereWithAggregatesInput[]
  NOT?: Prisma.Table1ScalarWhereWithAggregatesInput | Prisma.Table1ScalarWhereWithAggregatesInput[]
  id?: Prisma.IntWithAggregatesFilter<"Table1"> | number
  col1?: Prisma.DateTimeNullableWithAggregatesFilter<"Table1"> | Date | string | null
  col2?: Prisma.FloatNullableWithAggregatesFilter<"Table1"> | number | null
  col3?: Prisma.FloatNullableWithAggregatesFilter<"Table1"> | number | null
  col4?: Prisma.StringNullableWithAggregatesFilter<"Table1"> | string | null
  col5?: Prisma.StringNullableWithAggregatesFilter<"Table1"> | string | null
  col6?: Prisma.StringNullableWithAggregatesFilter<"Table1"> | string | null
  createdAt?: Prisma.DateTimeNullableWithAggregatesFilter<"Table1"> | Date | string | null
  updatedAt?: Prisma.DateTimeNullableWithAggregatesFilter<"Table1"> | Date | string | null
  deletedAt?: Prisma.DateTimeNullableWithAggregatesFilter<"Table1"> | Date | string | null
}

export type Table1CreateInput = {
  col1?: Date | string | null
  col2?: number | null
  col3?: number | null
  col4?: string | null
  col5?: string | null
  col6?: string | null
  createdAt?: Date | string | null
  updatedAt?: Date | string | null
  deletedAt?: Date | string | null
  columns?: Prisma.ColumnECreateNestedManyWithoutTableInput
}

export type Table1UncheckedCreateInput = {
  id?: number
  col1?: Date | string | null
  col2?: number | null
  col3?: number | null
  col4?: string | null
  col5?: string | null
  col6?: string | null
  createdAt?: Date | string | null
  updatedAt?: Date | string | null
  deletedAt?: Date | string | null
  columns?: Prisma.ColumnEUncheckedCreateNestedManyWithoutTableInput
}

export type Table1UpdateInput = {
  col1?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  col2?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  col3?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  col4?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  col5?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  col6?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  updatedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  columns?: Prisma.ColumnEUpdateManyWithoutTableNestedInput
}

export type Table1UncheckedUpdateInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  col1?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  col2?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  col3?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  col4?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  col5?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  col6?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  updatedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  columns?: Prisma.ColumnEUncheckedUpdateManyWithoutTableNestedInput
}

export type Table1CreateManyInput = {
  id?: number
  col1?: Date | string | null
  col2?: number | null
  col3?: number | null
  col4?: string | null
  col5?: string | null
  col6?: string | null
  createdAt?: Date | string | null
  updatedAt?: Date | string | null
  deletedAt?: Date | string | null
}

export type Table1UpdateManyMutationInput = {
  col1?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  col2?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  col3?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  col4?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  col5?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  col6?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  updatedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type Table1UncheckedUpdateManyInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  col1?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  col2?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  col3?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  col4?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  col5?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  col6?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  updatedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type Table1ScalarRelationFilter = {
  is?: Prisma.Table1WhereInput
  isNot?: Prisma.Table1WhereInput
}

export type Table1CountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  col1?: Prisma.SortOrder
  col2?: Prisma.SortOrder
  col3?: Prisma.SortOrder
  col4?: Prisma.SortOrder
  col5?: Prisma.SortOrder
  col6?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  deletedAt?: Prisma.SortOrder
}

export type Table1AvgOrderByAggregateInput = {
  id?: Prisma.SortOrder
  col2?: Prisma.SortOrder
  col3?: Prisma.SortOrder
}

export type Table1MaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  col1?: Prisma.SortOrder
  col2?: Prisma.SortOrder
  col3?: Prisma.SortOrder
  col4?: Prisma.SortOrder
  col5?: Prisma.SortOrder
  col6?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  deletedAt?: Prisma.SortOrder
}

export type Table1MinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  col1?: Prisma.SortOrder
  col2?: Prisma.SortOrder
  col3?: Prisma.SortOrder
  col4?: Prisma.SortOrder
  col5?: Prisma.SortOrder
  col6?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  deletedAt?: Prisma.SortOrder
}

export type Table1SumOrderByAggregateInput = {
  id?: Prisma.SortOrder
  col2?: Prisma.SortOrder
  col3?: Prisma.SortOrder
}

export type Table1CreateNestedOneWithoutColumnsInput = {
  create?: Prisma.XOR<Prisma.Table1CreateWithoutColumnsInput, Prisma.Table1UncheckedCreateWithoutColumnsInput>
  connectOrCreate?: Prisma.Table1CreateOrConnectWithoutColumnsInput
  connect?: Prisma.Table1WhereUniqueInput
}

export type Table1UpdateOneRequiredWithoutColumnsNestedInput = {
  create?: Prisma.XOR<Prisma.Table1CreateWithoutColumnsInput, Prisma.Table1UncheckedCreateWithoutColumnsInput>
  connectOrCreate?: Prisma.Table1CreateOrConnectWithoutColumnsInput
  upsert?: Prisma.Table1UpsertWithoutColumnsInput
  connect?: Prisma.Table1WhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.Table1UpdateToOneWithWhereWithoutColumnsInput, Prisma.Table1UpdateWithoutColumnsInput>, Prisma.Table1UncheckedUpdateWithoutColumnsInput>
}

export type NullableStringFieldUpdateOperationsInput = {
  set?: string | null
}

export type Table1CreateWithoutColumnsInput = {
  col1?: Date | string | null
  col2?: number | null
  col3?: number | null
  col4?: string | null
  col5?: string | null
  col6?: string | null
  createdAt?: Date | string | null
  updatedAt?: Date | string | null
  deletedAt?: Date | string | null
}

export type Table1UncheckedCreateWithoutColumnsInput = {
  id?: number
  col1?: Date | string | null
  col2?: number | null
  col3?: number | null
  col4?: string | null
  col5?: string | null
  col6?: string | null
  createdAt?: Date | string | null
  updatedAt?: Date | string | null
  deletedAt?: Date | string | null
}

export type Table1CreateOrConnectWithoutColumnsInput = {
  where: Prisma.Table1WhereUniqueInput
  create: Prisma.XOR<Prisma.Table1CreateWithoutColumnsInput, Prisma.Table1UncheckedCreateWithoutColumnsInput>
}

export type Table1UpsertWithoutColumnsInput = {
  update: Prisma.XOR<Prisma.Table1UpdateWithoutColumnsInput, Prisma.Table1UncheckedUpdateWithoutColumnsInput>
  create: Prisma.XOR<Prisma.Table1CreateWithoutColumnsInput, Prisma.Table1UncheckedCreateWithoutColumnsInput>
  where?: Prisma.Table1WhereInput
}

export type Table1UpdateToOneWithWhereWithoutColumnsInput = {
  where?: Prisma.Table1WhereInput
  data: Prisma.XOR<Prisma.Table1UpdateWithoutColumnsInput, Prisma.Table1UncheckedUpdateWithoutColumnsInput>
}

export type Table1UpdateWithoutColumnsInput = {
  col1?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  col2?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  col3?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  col4?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  col5?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  col6?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  updatedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type Table1UncheckedUpdateWithoutColumnsInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  col1?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  col2?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  col3?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  col4?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  col5?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  col6?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  updatedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}


/**
 * Count Type Table1CountOutputType
 */

export type Table1CountOutputType = {
  columns: number
}

export type Table1CountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  columns?: boolean | Table1CountOutputTypeCountColumnsArgs
}

/**
 * Table1CountOutputType without action
 */
export type Table1CountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Table1CountOutputType
   */
  select?: Prisma.Table1CountOutputTypeSelect<ExtArgs> | null
}

/**
 * Table1CountOutputType without action
 */
export type Table1CountOutputTypeCountColumnsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ColumnEWhereInput
}


export type Table1Select<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  col1?: boolean
  col2?: boolean
  col3?: boolean
  col4?: boolean
  col5?: boolean
  col6?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  deletedAt?: boolean
  columns?: boolean | Prisma.Table1$columnsArgs<ExtArgs>
  _count?: boolean | Prisma.Table1CountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["table1"]>

export type Table1SelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  col1?: boolean
  col2?: boolean
  col3?: boolean
  col4?: boolean
  col5?: boolean
  col6?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  deletedAt?: boolean
}, ExtArgs["result"]["table1"]>

export type Table1SelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  col1?: boolean
  col2?: boolean
  col3?: boolean
  col4?: boolean
  col5?: boolean
  col6?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  deletedAt?: boolean
}, ExtArgs["result"]["table1"]>

export type Table1SelectScalar = {
  id?: boolean
  col1?: boolean
  col2?: boolean
  col3?: boolean
  col4?: boolean
  col5?: boolean
  col6?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  deletedAt?: boolean
}

export type Table1Omit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "col1" | "col2" | "col3" | "col4" | "col5" | "col6" | "createdAt" | "updatedAt" | "deletedAt", ExtArgs["result"]["table1"]>
export type Table1Include<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  columns?: boolean | Prisma.Table1$columnsArgs<ExtArgs>
  _count?: boolean | Prisma.Table1CountOutputTypeDefaultArgs<ExtArgs>
}
export type Table1IncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}
export type Table1IncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}

export type $Table1Payload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Table1"
  objects: {
    columns: Prisma.$ColumnEPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: number
    col1: Date | null
    col2: number | null
    col3: number | null
    col4: string | null
    col5: string | null
    col6: string | null
    createdAt: Date | null
    updatedAt: Date | null
    deletedAt: Date | null
  }, ExtArgs["result"]["table1"]>
  composites: {}
}

export type Table1GetPayload<S extends boolean | null | undefined | Table1DefaultArgs> = runtime.Types.Result.GetResult<Prisma.$Table1Payload, S>

export type Table1CountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<Table1FindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: Table1CountAggregateInputType | true
  }

export interface Table1Delegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Table1'], meta: { name: 'Table1' } }
  /**
   * Find zero or one Table1 that matches the filter.
   * @param {Table1FindUniqueArgs} args - Arguments to find a Table1
   * @example
   * // Get one Table1
   * const table1 = await prisma.table1.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends Table1FindUniqueArgs>(args: Prisma.SelectSubset<T, Table1FindUniqueArgs<ExtArgs>>): Prisma.Prisma__Table1Client<runtime.Types.Result.GetResult<Prisma.$Table1Payload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Table1 that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {Table1FindUniqueOrThrowArgs} args - Arguments to find a Table1
   * @example
   * // Get one Table1
   * const table1 = await prisma.table1.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends Table1FindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, Table1FindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__Table1Client<runtime.Types.Result.GetResult<Prisma.$Table1Payload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Table1 that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {Table1FindFirstArgs} args - Arguments to find a Table1
   * @example
   * // Get one Table1
   * const table1 = await prisma.table1.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends Table1FindFirstArgs>(args?: Prisma.SelectSubset<T, Table1FindFirstArgs<ExtArgs>>): Prisma.Prisma__Table1Client<runtime.Types.Result.GetResult<Prisma.$Table1Payload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Table1 that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {Table1FindFirstOrThrowArgs} args - Arguments to find a Table1
   * @example
   * // Get one Table1
   * const table1 = await prisma.table1.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends Table1FindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, Table1FindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__Table1Client<runtime.Types.Result.GetResult<Prisma.$Table1Payload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Table1s that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {Table1FindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Table1s
   * const table1s = await prisma.table1.findMany()
   * 
   * // Get first 10 Table1s
   * const table1s = await prisma.table1.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const table1WithIdOnly = await prisma.table1.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends Table1FindManyArgs>(args?: Prisma.SelectSubset<T, Table1FindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$Table1Payload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Table1.
   * @param {Table1CreateArgs} args - Arguments to create a Table1.
   * @example
   * // Create one Table1
   * const Table1 = await prisma.table1.create({
   *   data: {
   *     // ... data to create a Table1
   *   }
   * })
   * 
   */
  create<T extends Table1CreateArgs>(args: Prisma.SelectSubset<T, Table1CreateArgs<ExtArgs>>): Prisma.Prisma__Table1Client<runtime.Types.Result.GetResult<Prisma.$Table1Payload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Table1s.
   * @param {Table1CreateManyArgs} args - Arguments to create many Table1s.
   * @example
   * // Create many Table1s
   * const table1 = await prisma.table1.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends Table1CreateManyArgs>(args?: Prisma.SelectSubset<T, Table1CreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Table1s and returns the data saved in the database.
   * @param {Table1CreateManyAndReturnArgs} args - Arguments to create many Table1s.
   * @example
   * // Create many Table1s
   * const table1 = await prisma.table1.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Table1s and only return the `id`
   * const table1WithIdOnly = await prisma.table1.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends Table1CreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, Table1CreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$Table1Payload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Table1.
   * @param {Table1DeleteArgs} args - Arguments to delete one Table1.
   * @example
   * // Delete one Table1
   * const Table1 = await prisma.table1.delete({
   *   where: {
   *     // ... filter to delete one Table1
   *   }
   * })
   * 
   */
  delete<T extends Table1DeleteArgs>(args: Prisma.SelectSubset<T, Table1DeleteArgs<ExtArgs>>): Prisma.Prisma__Table1Client<runtime.Types.Result.GetResult<Prisma.$Table1Payload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Table1.
   * @param {Table1UpdateArgs} args - Arguments to update one Table1.
   * @example
   * // Update one Table1
   * const table1 = await prisma.table1.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends Table1UpdateArgs>(args: Prisma.SelectSubset<T, Table1UpdateArgs<ExtArgs>>): Prisma.Prisma__Table1Client<runtime.Types.Result.GetResult<Prisma.$Table1Payload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Table1s.
   * @param {Table1DeleteManyArgs} args - Arguments to filter Table1s to delete.
   * @example
   * // Delete a few Table1s
   * const { count } = await prisma.table1.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends Table1DeleteManyArgs>(args?: Prisma.SelectSubset<T, Table1DeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Table1s.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {Table1UpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Table1s
   * const table1 = await prisma.table1.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends Table1UpdateManyArgs>(args: Prisma.SelectSubset<T, Table1UpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Table1s and returns the data updated in the database.
   * @param {Table1UpdateManyAndReturnArgs} args - Arguments to update many Table1s.
   * @example
   * // Update many Table1s
   * const table1 = await prisma.table1.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Table1s and only return the `id`
   * const table1WithIdOnly = await prisma.table1.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends Table1UpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, Table1UpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$Table1Payload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Table1.
   * @param {Table1UpsertArgs} args - Arguments to update or create a Table1.
   * @example
   * // Update or create a Table1
   * const table1 = await prisma.table1.upsert({
   *   create: {
   *     // ... data to create a Table1
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Table1 we want to update
   *   }
   * })
   */
  upsert<T extends Table1UpsertArgs>(args: Prisma.SelectSubset<T, Table1UpsertArgs<ExtArgs>>): Prisma.Prisma__Table1Client<runtime.Types.Result.GetResult<Prisma.$Table1Payload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Table1s.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {Table1CountArgs} args - Arguments to filter Table1s to count.
   * @example
   * // Count the number of Table1s
   * const count = await prisma.table1.count({
   *   where: {
   *     // ... the filter for the Table1s we want to count
   *   }
   * })
  **/
  count<T extends Table1CountArgs>(
    args?: Prisma.Subset<T, Table1CountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], Table1CountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Table1.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {Table1AggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends Table1AggregateArgs>(args: Prisma.Subset<T, Table1AggregateArgs>): Prisma.PrismaPromise<GetTable1AggregateType<T>>

  /**
   * Group by Table1.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {Table1GroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends Table1GroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: Table1GroupByArgs['orderBy'] }
      : { orderBy?: Table1GroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, Table1GroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetTable1GroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Table1 model
 */
readonly fields: Table1FieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Table1.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__Table1Client<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  columns<T extends Prisma.Table1$columnsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Table1$columnsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ColumnEPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Table1 model
 */
export interface Table1FieldRefs {
  readonly id: Prisma.FieldRef<"Table1", 'Int'>
  readonly col1: Prisma.FieldRef<"Table1", 'DateTime'>
  readonly col2: Prisma.FieldRef<"Table1", 'Float'>
  readonly col3: Prisma.FieldRef<"Table1", 'Float'>
  readonly col4: Prisma.FieldRef<"Table1", 'String'>
  readonly col5: Prisma.FieldRef<"Table1", 'String'>
  readonly col6: Prisma.FieldRef<"Table1", 'String'>
  readonly createdAt: Prisma.FieldRef<"Table1", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"Table1", 'DateTime'>
  readonly deletedAt: Prisma.FieldRef<"Table1", 'DateTime'>
}
    

// Custom InputTypes
/**
 * Table1 findUnique
 */
export type Table1FindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Table1
   */
  select?: Prisma.Table1Select<ExtArgs> | null
  /**
   * Omit specific fields from the Table1
   */
  omit?: Prisma.Table1Omit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.Table1Include<ExtArgs> | null
  /**
   * Filter, which Table1 to fetch.
   */
  where: Prisma.Table1WhereUniqueInput
}

/**
 * Table1 findUniqueOrThrow
 */
export type Table1FindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Table1
   */
  select?: Prisma.Table1Select<ExtArgs> | null
  /**
   * Omit specific fields from the Table1
   */
  omit?: Prisma.Table1Omit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.Table1Include<ExtArgs> | null
  /**
   * Filter, which Table1 to fetch.
   */
  where: Prisma.Table1WhereUniqueInput
}

/**
 * Table1 findFirst
 */
export type Table1FindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Table1
   */
  select?: Prisma.Table1Select<ExtArgs> | null
  /**
   * Omit specific fields from the Table1
   */
  omit?: Prisma.Table1Omit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.Table1Include<ExtArgs> | null
  /**
   * Filter, which Table1 to fetch.
   */
  where?: Prisma.Table1WhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Table1s to fetch.
   */
  orderBy?: Prisma.Table1OrderByWithRelationInput | Prisma.Table1OrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Table1s.
   */
  cursor?: Prisma.Table1WhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Table1s from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Table1s.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Table1s.
   */
  distinct?: Prisma.Table1ScalarFieldEnum | Prisma.Table1ScalarFieldEnum[]
}

/**
 * Table1 findFirstOrThrow
 */
export type Table1FindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Table1
   */
  select?: Prisma.Table1Select<ExtArgs> | null
  /**
   * Omit specific fields from the Table1
   */
  omit?: Prisma.Table1Omit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.Table1Include<ExtArgs> | null
  /**
   * Filter, which Table1 to fetch.
   */
  where?: Prisma.Table1WhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Table1s to fetch.
   */
  orderBy?: Prisma.Table1OrderByWithRelationInput | Prisma.Table1OrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Table1s.
   */
  cursor?: Prisma.Table1WhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Table1s from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Table1s.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Table1s.
   */
  distinct?: Prisma.Table1ScalarFieldEnum | Prisma.Table1ScalarFieldEnum[]
}

/**
 * Table1 findMany
 */
export type Table1FindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Table1
   */
  select?: Prisma.Table1Select<ExtArgs> | null
  /**
   * Omit specific fields from the Table1
   */
  omit?: Prisma.Table1Omit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.Table1Include<ExtArgs> | null
  /**
   * Filter, which Table1s to fetch.
   */
  where?: Prisma.Table1WhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Table1s to fetch.
   */
  orderBy?: Prisma.Table1OrderByWithRelationInput | Prisma.Table1OrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Table1s.
   */
  cursor?: Prisma.Table1WhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Table1s from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Table1s.
   */
  skip?: number
  distinct?: Prisma.Table1ScalarFieldEnum | Prisma.Table1ScalarFieldEnum[]
}

/**
 * Table1 create
 */
export type Table1CreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Table1
   */
  select?: Prisma.Table1Select<ExtArgs> | null
  /**
   * Omit specific fields from the Table1
   */
  omit?: Prisma.Table1Omit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.Table1Include<ExtArgs> | null
  /**
   * The data needed to create a Table1.
   */
  data?: Prisma.XOR<Prisma.Table1CreateInput, Prisma.Table1UncheckedCreateInput>
}

/**
 * Table1 createMany
 */
export type Table1CreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Table1s.
   */
  data: Prisma.Table1CreateManyInput | Prisma.Table1CreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Table1 createManyAndReturn
 */
export type Table1CreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Table1
   */
  select?: Prisma.Table1SelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Table1
   */
  omit?: Prisma.Table1Omit<ExtArgs> | null
  /**
   * The data used to create many Table1s.
   */
  data: Prisma.Table1CreateManyInput | Prisma.Table1CreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Table1 update
 */
export type Table1UpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Table1
   */
  select?: Prisma.Table1Select<ExtArgs> | null
  /**
   * Omit specific fields from the Table1
   */
  omit?: Prisma.Table1Omit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.Table1Include<ExtArgs> | null
  /**
   * The data needed to update a Table1.
   */
  data: Prisma.XOR<Prisma.Table1UpdateInput, Prisma.Table1UncheckedUpdateInput>
  /**
   * Choose, which Table1 to update.
   */
  where: Prisma.Table1WhereUniqueInput
}

/**
 * Table1 updateMany
 */
export type Table1UpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Table1s.
   */
  data: Prisma.XOR<Prisma.Table1UpdateManyMutationInput, Prisma.Table1UncheckedUpdateManyInput>
  /**
   * Filter which Table1s to update
   */
  where?: Prisma.Table1WhereInput
  /**
   * Limit how many Table1s to update.
   */
  limit?: number
}

/**
 * Table1 updateManyAndReturn
 */
export type Table1UpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Table1
   */
  select?: Prisma.Table1SelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Table1
   */
  omit?: Prisma.Table1Omit<ExtArgs> | null
  /**
   * The data used to update Table1s.
   */
  data: Prisma.XOR<Prisma.Table1UpdateManyMutationInput, Prisma.Table1UncheckedUpdateManyInput>
  /**
   * Filter which Table1s to update
   */
  where?: Prisma.Table1WhereInput
  /**
   * Limit how many Table1s to update.
   */
  limit?: number
}

/**
 * Table1 upsert
 */
export type Table1UpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Table1
   */
  select?: Prisma.Table1Select<ExtArgs> | null
  /**
   * Omit specific fields from the Table1
   */
  omit?: Prisma.Table1Omit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.Table1Include<ExtArgs> | null
  /**
   * The filter to search for the Table1 to update in case it exists.
   */
  where: Prisma.Table1WhereUniqueInput
  /**
   * In case the Table1 found by the `where` argument doesn't exist, create a new Table1 with this data.
   */
  create: Prisma.XOR<Prisma.Table1CreateInput, Prisma.Table1UncheckedCreateInput>
  /**
   * In case the Table1 was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.Table1UpdateInput, Prisma.Table1UncheckedUpdateInput>
}

/**
 * Table1 delete
 */
export type Table1DeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Table1
   */
  select?: Prisma.Table1Select<ExtArgs> | null
  /**
   * Omit specific fields from the Table1
   */
  omit?: Prisma.Table1Omit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.Table1Include<ExtArgs> | null
  /**
   * Filter which Table1 to delete.
   */
  where: Prisma.Table1WhereUniqueInput
}

/**
 * Table1 deleteMany
 */
export type Table1DeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Table1s to delete
   */
  where?: Prisma.Table1WhereInput
  /**
   * Limit how many Table1s to delete.
   */
  limit?: number
}

/**
 * Table1.columns
 */
export type Table1$columnsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ColumnE
   */
  select?: Prisma.ColumnESelect<ExtArgs> | null
  /**
   * Omit specific fields from the ColumnE
   */
  omit?: Prisma.ColumnEOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ColumnEInclude<ExtArgs> | null
  where?: Prisma.ColumnEWhereInput
  orderBy?: Prisma.ColumnEOrderByWithRelationInput | Prisma.ColumnEOrderByWithRelationInput[]
  cursor?: Prisma.ColumnEWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.ColumnEScalarFieldEnum | Prisma.ColumnEScalarFieldEnum[]
}

/**
 * Table1 without action
 */
export type Table1DefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Table1
   */
  select?: Prisma.Table1Select<ExtArgs> | null
  /**
   * Omit specific fields from the Table1
   */
  omit?: Prisma.Table1Omit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.Table1Include<ExtArgs> | null
}
