
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `TableE` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model TableE
 * 
 */
export type TableEModel = runtime.Types.Result.DefaultSelection<Prisma.$TableEPayload>

export type AggregateTableE = {
  _count: TableECountAggregateOutputType | null
  _avg: TableEAvgAggregateOutputType | null
  _sum: TableESumAggregateOutputType | null
  _min: TableEMinAggregateOutputType | null
  _max: TableEMaxAggregateOutputType | null
}

export type TableEAvgAggregateOutputType = {
  id: number | null
}

export type TableESumAggregateOutputType = {
  id: number | null
}

export type TableEMinAggregateOutputType = {
  id: number | null
  name: string | null
}

export type TableEMaxAggregateOutputType = {
  id: number | null
  name: string | null
}

export type TableECountAggregateOutputType = {
  id: number
  name: number
  _all: number
}


export type TableEAvgAggregateInputType = {
  id?: true
}

export type TableESumAggregateInputType = {
  id?: true
}

export type TableEMinAggregateInputType = {
  id?: true
  name?: true
}

export type TableEMaxAggregateInputType = {
  id?: true
  name?: true
}

export type TableECountAggregateInputType = {
  id?: true
  name?: true
  _all?: true
}

export type TableEAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which TableE to aggregate.
   */
  where?: Prisma.TableEWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of TableES to fetch.
   */
  orderBy?: Prisma.TableEOrderByWithRelationInput | Prisma.TableEOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.TableEWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` TableES from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` TableES.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned TableES
  **/
  _count?: true | TableECountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: TableEAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: TableESumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: TableEMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: TableEMaxAggregateInputType
}

export type GetTableEAggregateType<T extends TableEAggregateArgs> = {
      [P in keyof T & keyof AggregateTableE]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateTableE[P]>
    : Prisma.GetScalarType<T[P], AggregateTableE[P]>
}




export type TableEGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.TableEWhereInput
  orderBy?: Prisma.TableEOrderByWithAggregationInput | Prisma.TableEOrderByWithAggregationInput[]
  by: Prisma.TableEScalarFieldEnum[] | Prisma.TableEScalarFieldEnum
  having?: Prisma.TableEScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: TableECountAggregateInputType | true
  _avg?: TableEAvgAggregateInputType
  _sum?: TableESumAggregateInputType
  _min?: TableEMinAggregateInputType
  _max?: TableEMaxAggregateInputType
}

export type TableEGroupByOutputType = {
  id: number
  name: string
  _count: TableECountAggregateOutputType | null
  _avg: TableEAvgAggregateOutputType | null
  _sum: TableESumAggregateOutputType | null
  _min: TableEMinAggregateOutputType | null
  _max: TableEMaxAggregateOutputType | null
}

type GetTableEGroupByPayload<T extends TableEGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<TableEGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof TableEGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], TableEGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], TableEGroupByOutputType[P]>
      }
    >
  >



export type TableEWhereInput = {
  AND?: Prisma.TableEWhereInput | Prisma.TableEWhereInput[]
  OR?: Prisma.TableEWhereInput[]
  NOT?: Prisma.TableEWhereInput | Prisma.TableEWhereInput[]
  id?: Prisma.IntFilter<"TableE"> | number
  name?: Prisma.StringFilter<"TableE"> | string
  columns?: Prisma.ColumnEListRelationFilter
}

export type TableEOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  columns?: Prisma.ColumnEOrderByRelationAggregateInput
}

export type TableEWhereUniqueInput = Prisma.AtLeast<{
  id?: number
  AND?: Prisma.TableEWhereInput | Prisma.TableEWhereInput[]
  OR?: Prisma.TableEWhereInput[]
  NOT?: Prisma.TableEWhereInput | Prisma.TableEWhereInput[]
  name?: Prisma.StringFilter<"TableE"> | string
  columns?: Prisma.ColumnEListRelationFilter
}, "id">

export type TableEOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  _count?: Prisma.TableECountOrderByAggregateInput
  _avg?: Prisma.TableEAvgOrderByAggregateInput
  _max?: Prisma.TableEMaxOrderByAggregateInput
  _min?: Prisma.TableEMinOrderByAggregateInput
  _sum?: Prisma.TableESumOrderByAggregateInput
}

export type TableEScalarWhereWithAggregatesInput = {
  AND?: Prisma.TableEScalarWhereWithAggregatesInput | Prisma.TableEScalarWhereWithAggregatesInput[]
  OR?: Prisma.TableEScalarWhereWithAggregatesInput[]
  NOT?: Prisma.TableEScalarWhereWithAggregatesInput | Prisma.TableEScalarWhereWithAggregatesInput[]
  id?: Prisma.IntWithAggregatesFilter<"TableE"> | number
  name?: Prisma.StringWithAggregatesFilter<"TableE"> | string
}

export type TableECreateInput = {
  name: string
  columns?: Prisma.ColumnECreateNestedManyWithoutTableInput
}

export type TableEUncheckedCreateInput = {
  id?: number
  name: string
  columns?: Prisma.ColumnEUncheckedCreateNestedManyWithoutTableInput
}

export type TableEUpdateInput = {
  name?: Prisma.StringFieldUpdateOperationsInput | string
  columns?: Prisma.ColumnEUpdateManyWithoutTableNestedInput
}

export type TableEUncheckedUpdateInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  name?: Prisma.StringFieldUpdateOperationsInput | string
  columns?: Prisma.ColumnEUncheckedUpdateManyWithoutTableNestedInput
}

export type TableECreateManyInput = {
  id?: number
  name: string
}

export type TableEUpdateManyMutationInput = {
  name?: Prisma.StringFieldUpdateOperationsInput | string
}

export type TableEUncheckedUpdateManyInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  name?: Prisma.StringFieldUpdateOperationsInput | string
}

export type TableECountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
}

export type TableEAvgOrderByAggregateInput = {
  id?: Prisma.SortOrder
}

export type TableEMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
}

export type TableEMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
}

export type TableESumOrderByAggregateInput = {
  id?: Prisma.SortOrder
}

export type TableEScalarRelationFilter = {
  is?: Prisma.TableEWhereInput
  isNot?: Prisma.TableEWhereInput
}

export type TableECreateNestedOneWithoutColumnsInput = {
  create?: Prisma.XOR<Prisma.TableECreateWithoutColumnsInput, Prisma.TableEUncheckedCreateWithoutColumnsInput>
  connectOrCreate?: Prisma.TableECreateOrConnectWithoutColumnsInput
  connect?: Prisma.TableEWhereUniqueInput
}

export type TableEUpdateOneRequiredWithoutColumnsNestedInput = {
  create?: Prisma.XOR<Prisma.TableECreateWithoutColumnsInput, Prisma.TableEUncheckedCreateWithoutColumnsInput>
  connectOrCreate?: Prisma.TableECreateOrConnectWithoutColumnsInput
  upsert?: Prisma.TableEUpsertWithoutColumnsInput
  connect?: Prisma.TableEWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.TableEUpdateToOneWithWhereWithoutColumnsInput, Prisma.TableEUpdateWithoutColumnsInput>, Prisma.TableEUncheckedUpdateWithoutColumnsInput>
}

export type TableECreateWithoutColumnsInput = {
  name: string
}

export type TableEUncheckedCreateWithoutColumnsInput = {
  id?: number
  name: string
}

export type TableECreateOrConnectWithoutColumnsInput = {
  where: Prisma.TableEWhereUniqueInput
  create: Prisma.XOR<Prisma.TableECreateWithoutColumnsInput, Prisma.TableEUncheckedCreateWithoutColumnsInput>
}

export type TableEUpsertWithoutColumnsInput = {
  update: Prisma.XOR<Prisma.TableEUpdateWithoutColumnsInput, Prisma.TableEUncheckedUpdateWithoutColumnsInput>
  create: Prisma.XOR<Prisma.TableECreateWithoutColumnsInput, Prisma.TableEUncheckedCreateWithoutColumnsInput>
  where?: Prisma.TableEWhereInput
}

export type TableEUpdateToOneWithWhereWithoutColumnsInput = {
  where?: Prisma.TableEWhereInput
  data: Prisma.XOR<Prisma.TableEUpdateWithoutColumnsInput, Prisma.TableEUncheckedUpdateWithoutColumnsInput>
}

export type TableEUpdateWithoutColumnsInput = {
  name?: Prisma.StringFieldUpdateOperationsInput | string
}

export type TableEUncheckedUpdateWithoutColumnsInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  name?: Prisma.StringFieldUpdateOperationsInput | string
}


/**
 * Count Type TableECountOutputType
 */

export type TableECountOutputType = {
  columns: number
}

export type TableECountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  columns?: boolean | TableECountOutputTypeCountColumnsArgs
}

/**
 * TableECountOutputType without action
 */
export type TableECountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TableECountOutputType
   */
  select?: Prisma.TableECountOutputTypeSelect<ExtArgs> | null
}

/**
 * TableECountOutputType without action
 */
export type TableECountOutputTypeCountColumnsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ColumnEWhereInput
}


export type TableESelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  columns?: boolean | Prisma.TableE$columnsArgs<ExtArgs>
  _count?: boolean | Prisma.TableECountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["tableE"]>

export type TableESelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
}, ExtArgs["result"]["tableE"]>

export type TableESelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
}, ExtArgs["result"]["tableE"]>

export type TableESelectScalar = {
  id?: boolean
  name?: boolean
}

export type TableEOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "name", ExtArgs["result"]["tableE"]>
export type TableEInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  columns?: boolean | Prisma.TableE$columnsArgs<ExtArgs>
  _count?: boolean | Prisma.TableECountOutputTypeDefaultArgs<ExtArgs>
}
export type TableEIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}
export type TableEIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}

export type $TableEPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "TableE"
  objects: {
    columns: Prisma.$ColumnEPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: number
    name: string
  }, ExtArgs["result"]["tableE"]>
  composites: {}
}

export type TableEGetPayload<S extends boolean | null | undefined | TableEDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$TableEPayload, S>

export type TableECountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<TableEFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: TableECountAggregateInputType | true
  }

export interface TableEDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['TableE'], meta: { name: 'TableE' } }
  /**
   * Find zero or one TableE that matches the filter.
   * @param {TableEFindUniqueArgs} args - Arguments to find a TableE
   * @example
   * // Get one TableE
   * const tableE = await prisma.tableE.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends TableEFindUniqueArgs>(args: Prisma.SelectSubset<T, TableEFindUniqueArgs<ExtArgs>>): Prisma.Prisma__TableEClient<runtime.Types.Result.GetResult<Prisma.$TableEPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one TableE that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {TableEFindUniqueOrThrowArgs} args - Arguments to find a TableE
   * @example
   * // Get one TableE
   * const tableE = await prisma.tableE.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends TableEFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, TableEFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__TableEClient<runtime.Types.Result.GetResult<Prisma.$TableEPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first TableE that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TableEFindFirstArgs} args - Arguments to find a TableE
   * @example
   * // Get one TableE
   * const tableE = await prisma.tableE.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends TableEFindFirstArgs>(args?: Prisma.SelectSubset<T, TableEFindFirstArgs<ExtArgs>>): Prisma.Prisma__TableEClient<runtime.Types.Result.GetResult<Prisma.$TableEPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first TableE that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TableEFindFirstOrThrowArgs} args - Arguments to find a TableE
   * @example
   * // Get one TableE
   * const tableE = await prisma.tableE.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends TableEFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, TableEFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__TableEClient<runtime.Types.Result.GetResult<Prisma.$TableEPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more TableES that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TableEFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all TableES
   * const tableES = await prisma.tableE.findMany()
   * 
   * // Get first 10 TableES
   * const tableES = await prisma.tableE.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const tableEWithIdOnly = await prisma.tableE.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends TableEFindManyArgs>(args?: Prisma.SelectSubset<T, TableEFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TableEPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a TableE.
   * @param {TableECreateArgs} args - Arguments to create a TableE.
   * @example
   * // Create one TableE
   * const TableE = await prisma.tableE.create({
   *   data: {
   *     // ... data to create a TableE
   *   }
   * })
   * 
   */
  create<T extends TableECreateArgs>(args: Prisma.SelectSubset<T, TableECreateArgs<ExtArgs>>): Prisma.Prisma__TableEClient<runtime.Types.Result.GetResult<Prisma.$TableEPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many TableES.
   * @param {TableECreateManyArgs} args - Arguments to create many TableES.
   * @example
   * // Create many TableES
   * const tableE = await prisma.tableE.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends TableECreateManyArgs>(args?: Prisma.SelectSubset<T, TableECreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many TableES and returns the data saved in the database.
   * @param {TableECreateManyAndReturnArgs} args - Arguments to create many TableES.
   * @example
   * // Create many TableES
   * const tableE = await prisma.tableE.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many TableES and only return the `id`
   * const tableEWithIdOnly = await prisma.tableE.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends TableECreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, TableECreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TableEPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a TableE.
   * @param {TableEDeleteArgs} args - Arguments to delete one TableE.
   * @example
   * // Delete one TableE
   * const TableE = await prisma.tableE.delete({
   *   where: {
   *     // ... filter to delete one TableE
   *   }
   * })
   * 
   */
  delete<T extends TableEDeleteArgs>(args: Prisma.SelectSubset<T, TableEDeleteArgs<ExtArgs>>): Prisma.Prisma__TableEClient<runtime.Types.Result.GetResult<Prisma.$TableEPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one TableE.
   * @param {TableEUpdateArgs} args - Arguments to update one TableE.
   * @example
   * // Update one TableE
   * const tableE = await prisma.tableE.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends TableEUpdateArgs>(args: Prisma.SelectSubset<T, TableEUpdateArgs<ExtArgs>>): Prisma.Prisma__TableEClient<runtime.Types.Result.GetResult<Prisma.$TableEPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more TableES.
   * @param {TableEDeleteManyArgs} args - Arguments to filter TableES to delete.
   * @example
   * // Delete a few TableES
   * const { count } = await prisma.tableE.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends TableEDeleteManyArgs>(args?: Prisma.SelectSubset<T, TableEDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more TableES.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TableEUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many TableES
   * const tableE = await prisma.tableE.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends TableEUpdateManyArgs>(args: Prisma.SelectSubset<T, TableEUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more TableES and returns the data updated in the database.
   * @param {TableEUpdateManyAndReturnArgs} args - Arguments to update many TableES.
   * @example
   * // Update many TableES
   * const tableE = await prisma.tableE.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more TableES and only return the `id`
   * const tableEWithIdOnly = await prisma.tableE.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends TableEUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, TableEUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TableEPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one TableE.
   * @param {TableEUpsertArgs} args - Arguments to update or create a TableE.
   * @example
   * // Update or create a TableE
   * const tableE = await prisma.tableE.upsert({
   *   create: {
   *     // ... data to create a TableE
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the TableE we want to update
   *   }
   * })
   */
  upsert<T extends TableEUpsertArgs>(args: Prisma.SelectSubset<T, TableEUpsertArgs<ExtArgs>>): Prisma.Prisma__TableEClient<runtime.Types.Result.GetResult<Prisma.$TableEPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of TableES.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TableECountArgs} args - Arguments to filter TableES to count.
   * @example
   * // Count the number of TableES
   * const count = await prisma.tableE.count({
   *   where: {
   *     // ... the filter for the TableES we want to count
   *   }
   * })
  **/
  count<T extends TableECountArgs>(
    args?: Prisma.Subset<T, TableECountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], TableECountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a TableE.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TableEAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends TableEAggregateArgs>(args: Prisma.Subset<T, TableEAggregateArgs>): Prisma.PrismaPromise<GetTableEAggregateType<T>>

  /**
   * Group by TableE.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TableEGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends TableEGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: TableEGroupByArgs['orderBy'] }
      : { orderBy?: TableEGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, TableEGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetTableEGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the TableE model
 */
readonly fields: TableEFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for TableE.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__TableEClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  columns<T extends Prisma.TableE$columnsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.TableE$columnsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ColumnEPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the TableE model
 */
export interface TableEFieldRefs {
  readonly id: Prisma.FieldRef<"TableE", 'Int'>
  readonly name: Prisma.FieldRef<"TableE", 'String'>
}
    

// Custom InputTypes
/**
 * TableE findUnique
 */
export type TableEFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TableE
   */
  select?: Prisma.TableESelect<ExtArgs> | null
  /**
   * Omit specific fields from the TableE
   */
  omit?: Prisma.TableEOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TableEInclude<ExtArgs> | null
  /**
   * Filter, which TableE to fetch.
   */
  where: Prisma.TableEWhereUniqueInput
}

/**
 * TableE findUniqueOrThrow
 */
export type TableEFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TableE
   */
  select?: Prisma.TableESelect<ExtArgs> | null
  /**
   * Omit specific fields from the TableE
   */
  omit?: Prisma.TableEOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TableEInclude<ExtArgs> | null
  /**
   * Filter, which TableE to fetch.
   */
  where: Prisma.TableEWhereUniqueInput
}

/**
 * TableE findFirst
 */
export type TableEFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TableE
   */
  select?: Prisma.TableESelect<ExtArgs> | null
  /**
   * Omit specific fields from the TableE
   */
  omit?: Prisma.TableEOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TableEInclude<ExtArgs> | null
  /**
   * Filter, which TableE to fetch.
   */
  where?: Prisma.TableEWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of TableES to fetch.
   */
  orderBy?: Prisma.TableEOrderByWithRelationInput | Prisma.TableEOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for TableES.
   */
  cursor?: Prisma.TableEWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` TableES from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` TableES.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of TableES.
   */
  distinct?: Prisma.TableEScalarFieldEnum | Prisma.TableEScalarFieldEnum[]
}

/**
 * TableE findFirstOrThrow
 */
export type TableEFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TableE
   */
  select?: Prisma.TableESelect<ExtArgs> | null
  /**
   * Omit specific fields from the TableE
   */
  omit?: Prisma.TableEOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TableEInclude<ExtArgs> | null
  /**
   * Filter, which TableE to fetch.
   */
  where?: Prisma.TableEWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of TableES to fetch.
   */
  orderBy?: Prisma.TableEOrderByWithRelationInput | Prisma.TableEOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for TableES.
   */
  cursor?: Prisma.TableEWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` TableES from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` TableES.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of TableES.
   */
  distinct?: Prisma.TableEScalarFieldEnum | Prisma.TableEScalarFieldEnum[]
}

/**
 * TableE findMany
 */
export type TableEFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TableE
   */
  select?: Prisma.TableESelect<ExtArgs> | null
  /**
   * Omit specific fields from the TableE
   */
  omit?: Prisma.TableEOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TableEInclude<ExtArgs> | null
  /**
   * Filter, which TableES to fetch.
   */
  where?: Prisma.TableEWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of TableES to fetch.
   */
  orderBy?: Prisma.TableEOrderByWithRelationInput | Prisma.TableEOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing TableES.
   */
  cursor?: Prisma.TableEWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` TableES from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` TableES.
   */
  skip?: number
  distinct?: Prisma.TableEScalarFieldEnum | Prisma.TableEScalarFieldEnum[]
}

/**
 * TableE create
 */
export type TableECreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TableE
   */
  select?: Prisma.TableESelect<ExtArgs> | null
  /**
   * Omit specific fields from the TableE
   */
  omit?: Prisma.TableEOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TableEInclude<ExtArgs> | null
  /**
   * The data needed to create a TableE.
   */
  data: Prisma.XOR<Prisma.TableECreateInput, Prisma.TableEUncheckedCreateInput>
}

/**
 * TableE createMany
 */
export type TableECreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many TableES.
   */
  data: Prisma.TableECreateManyInput | Prisma.TableECreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * TableE createManyAndReturn
 */
export type TableECreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TableE
   */
  select?: Prisma.TableESelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the TableE
   */
  omit?: Prisma.TableEOmit<ExtArgs> | null
  /**
   * The data used to create many TableES.
   */
  data: Prisma.TableECreateManyInput | Prisma.TableECreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * TableE update
 */
export type TableEUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TableE
   */
  select?: Prisma.TableESelect<ExtArgs> | null
  /**
   * Omit specific fields from the TableE
   */
  omit?: Prisma.TableEOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TableEInclude<ExtArgs> | null
  /**
   * The data needed to update a TableE.
   */
  data: Prisma.XOR<Prisma.TableEUpdateInput, Prisma.TableEUncheckedUpdateInput>
  /**
   * Choose, which TableE to update.
   */
  where: Prisma.TableEWhereUniqueInput
}

/**
 * TableE updateMany
 */
export type TableEUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update TableES.
   */
  data: Prisma.XOR<Prisma.TableEUpdateManyMutationInput, Prisma.TableEUncheckedUpdateManyInput>
  /**
   * Filter which TableES to update
   */
  where?: Prisma.TableEWhereInput
  /**
   * Limit how many TableES to update.
   */
  limit?: number
}

/**
 * TableE updateManyAndReturn
 */
export type TableEUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TableE
   */
  select?: Prisma.TableESelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the TableE
   */
  omit?: Prisma.TableEOmit<ExtArgs> | null
  /**
   * The data used to update TableES.
   */
  data: Prisma.XOR<Prisma.TableEUpdateManyMutationInput, Prisma.TableEUncheckedUpdateManyInput>
  /**
   * Filter which TableES to update
   */
  where?: Prisma.TableEWhereInput
  /**
   * Limit how many TableES to update.
   */
  limit?: number
}

/**
 * TableE upsert
 */
export type TableEUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TableE
   */
  select?: Prisma.TableESelect<ExtArgs> | null
  /**
   * Omit specific fields from the TableE
   */
  omit?: Prisma.TableEOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TableEInclude<ExtArgs> | null
  /**
   * The filter to search for the TableE to update in case it exists.
   */
  where: Prisma.TableEWhereUniqueInput
  /**
   * In case the TableE found by the `where` argument doesn't exist, create a new TableE with this data.
   */
  create: Prisma.XOR<Prisma.TableECreateInput, Prisma.TableEUncheckedCreateInput>
  /**
   * In case the TableE was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.TableEUpdateInput, Prisma.TableEUncheckedUpdateInput>
}

/**
 * TableE delete
 */
export type TableEDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TableE
   */
  select?: Prisma.TableESelect<ExtArgs> | null
  /**
   * Omit specific fields from the TableE
   */
  omit?: Prisma.TableEOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TableEInclude<ExtArgs> | null
  /**
   * Filter which TableE to delete.
   */
  where: Prisma.TableEWhereUniqueInput
}

/**
 * TableE deleteMany
 */
export type TableEDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which TableES to delete
   */
  where?: Prisma.TableEWhereInput
  /**
   * Limit how many TableES to delete.
   */
  limit?: number
}

/**
 * TableE.columns
 */
export type TableE$columnsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ColumnE
   */
  select?: Prisma.ColumnESelect<ExtArgs> | null
  /**
   * Omit specific fields from the ColumnE
   */
  omit?: Prisma.ColumnEOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ColumnEInclude<ExtArgs> | null
  where?: Prisma.ColumnEWhereInput
  orderBy?: Prisma.ColumnEOrderByWithRelationInput | Prisma.ColumnEOrderByWithRelationInput[]
  cursor?: Prisma.ColumnEWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.ColumnEScalarFieldEnum | Prisma.ColumnEScalarFieldEnum[]
}

/**
 * TableE without action
 */
export type TableEDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TableE
   */
  select?: Prisma.TableESelect<ExtArgs> | null
  /**
   * Omit specific fields from the TableE
   */
  omit?: Prisma.TableEOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TableEInclude<ExtArgs> | null
}
